### ISSUE TITLE
Witch King can be seduced

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#100]

**Comment by RedArkady** [comment]
![WK](https://user-images.githubusercontent.com/20355423/120466435-fa7def00-c396-11eb-9220-56ecf7bded26.png)

**Comment by jj248** [comment]
Have made it so that Nazgul cannot be the target of schemes.

**Comment by RedArkady** [comment]
Yep this is now disabled on account of them having the trait: Nazgul. They can't be swayed either, which may or may not be intentional?

**Comment by jj248** [comment]
WaD.  Closing.  :)
