### ISSUE TITLE
Code error in lotr_buildings.txt

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#104]
"Was reading through the game code and found a bug. In the "lotr_buildings.txt" file in the buildings folder, line 445 "all_welcome_inn_01 = [# All Welcome Inn (for cities)" is missing the starting bracket for the code. [ should be {. This is also this way for the other 3 "all_welcome_inn" levels."

**Comment by MattTheLegoman** [comment]
Cannot find issue, the brackets are currently correct.
