### ISSUE TITLE
Raiding camp upgrade not showing properly in notification pop-up

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#105]

**Comment by RedArkady** [comment]
![Uploading Crusader Kings III Screenshot 2021.06.04 - 17.56.48.37.png…]()

**Comment by RedArkady** [comment]
![Crusader Kings III Screenshot 2021 06 04 - 17 56 48 37](https://user-images.githubusercontent.com/20355423/120837343-7c6c4480-c55e-11eb-9c29-5e120bfa90af.png)

**Comment by RedArkady** [comment]
Also the case with Hunting Outposts

**Comment by jj248** [comment]
This is due to those building levels still being unlocalised.

We have an issue for this already ( #92 ) so closing this as a duplicate bug.
