### ISSUE TITLE
Dunedain can recruit Axemen of Lossarnach

### ISSUE THREAD

**Issue by MattTheLegoman** [MattTheLegoman/RealmsInExile#110]
The Axemen of Lossarnach MaA should be restricted to the Lossarnach title.

The broad Dunedain culture should not have access to named unique MaA.

**Comment by jj248** [comment]
Not possible to restrict based on title using innovations alone.  Would need to implement an event based system which we won't have time for ahead of v2.1 release.  Moving to backlog for addressing in v2.2.

**Comment by VectorMaximus** [comment]
They were long ago re-localized as generic 'Gondorian Axemen'. Might still be worth thinking about removal for a general reduction in Gondorian MAA (as at present there are quite many), but closing this issue for now.
