### ISSUE TITLE
Sauron's triggered 3005 war for Osgiliath should have options to delay or cancel.

### ISSUE THREAD

**Issue by MattTheLegoman** [MattTheLegoman/RealmsInExile#112]
The delay should be 5 years.
Cancelling should cost prestige.

**Comment by jj248** [comment]
Vector has implemented these choices by event - ready to test.

**Comment by jj248** [comment]
Have tested and all working fine - works well... only one design question:  Why would I ever take the option not to go to war and take a prestige hit rather than just endlessly delay?  I'd suggest the second event that triggers after a further 5 years doesn't have deferral as an option.

**Comment by VectorMaximus** [comment]
Implemented this long ago - now closing
