### ISSUE TITLE
Add Orc commander traits for the icons made by Matt:

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#115]
https://discord.com/channels/751097183448727552/751097925509185666/836528001549205514

**Comment by jj248** [comment]
New commander traits added: Banner Orc, Whipping Master and Explosives Engineer.

Only need to figure out why non-orcs are getting these when they're flagged as commander traits.

**Comment by jj248** [comment]
Decided not to flag as commander traits.  Moving ready to test.

**Comment by JukeJukestar** [comment]
Working as intended, haha! Random orcs are getting them, though I have never seen a way to get it as an orc player.
