### ISSUE TITLE
Arwen does not die after Aragorn

### ISSUE THREAD

**Issue by VectorMaximus** [MattTheLegoman/RealmsInExile#116]
At present, Arwen does not die, since we cannot dynamically change her from immortal to mortal (at least we have not attempted, as of yet). I think the simplest solution would be, if she marries Aragorn, then a few years after his death she will receive an event where she dies.

**Comment by jj248** [comment]
Done - will now fade from grief exactly one year after Aragorn dies. Closing as pretty easy to test myself in game!
