### ISSUE TITLE
Is the reduced diplomatic range acceptable?

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#117]
Effectively, we're proposing to cut diplomatic range by a quarter for most characters to reflect the more 'local' nature of Middle Earth and want to understand whether that feels right or is too limiting for the player.

**Comment by RedArkady** [comment]
This seems to be working well, and the narrower range of mercenaries available feels better.

**Comment by JukeJukestar** [comment]
close? @jj248 i think it works well

**Comment by JukeJukestar** [comment]
works well.
