### ISSUE TITLE
Numenorian blood marriage modifier applies to player character, instead of person being offered for marriage

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#118]

**Comment by jj248** [comment]
Fixed - ready to test.

**Comment by RedArkady** [comment]
This is working well.

The only thing I'm twitchy about is that it can mean that younger sons with a a higher tier are better marriage prospects than an actual primary heir with a lower tier. I'm not sure how easy it would be to get around that, or whether it's desirable to do so.
