### ISSUE TITLE
Ravage the Land - Orc counsellor action

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#139]
A more brutal conversion action available to orcs.

Converts both culture and religion at cost of much higher revolt risk and drop in control and development.

Should have some associated random events to represent pillaging, looting etc.  Once artifact system is in, random loot could be given in inventories.

**Comment by jj248** [comment]
Pushing this to v3.0.  Might as well wait for the artefact system to be in place to implement it!

**Comment by Kyrenic** [comment]
A prototype for this has now been made, it still needs custom events and county modifiers but the basis is there. As mentioned in issue #469 , this is an expansion of base game mechanics, not a removal.

**Comment by Kyrenic** [comment]
Councillor tasks have been reworked a bit and are locked depending on the race of the character.

### **Orcs**
Orcs can:
- Ravage the land (Converts culture and faith)

Orcs cannot:
- Promote culture
- Promote cultural acceptance

### **Humans**
Humans can:
- Promote culture
- Promote cultural acceptance

Humans cannot:
- Ravage the land

### **Restricted cultures**
Think of characters like Sauron, the Nazgul, Saruman and the like, unique cultures not meant to be present on the map.

Restricted cultures cannot
- Ravage the land
- Promote culture
- Promote cultural acceptance

**Comment by RoughlyTheSizeOfAMOROOON** [comment]
For Elves, I'm perhaps thinking that they should only be able to do promote cultural acceptance, except perhaps counties that were traditionally Elven lands but have since been lost. In which case, maybe a decision to get Elves back in that land?

Sure you can play as an expansionist Elf, but I'd imagine that even IF we get a cultural conversion stuff for Elves, it should take literal centuries for a single county. Thus making getting your cultural acceptance high far more attractive.

**Comment by Kyrenic** [comment]
I think Elves should fade, slowly over the course of about 100 years after Sauron's death. Maybe we could make events to slowly feed Elvish lands to the wilderness?

**Comment by jj248** [comment]
This is probably done and ready to test.

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/213669148-d3a6f618-8022-4180-95bf-469eb7630a28.png)

![image](https://user-images.githubusercontent.com/76008882/213669267-5d16fb7e-d248-43b3-9e63-41903a410d73.png)

![image](https://user-images.githubusercontent.com/76008882/213669411-17703b7b-999f-478d-9015-32e006d54de5.png)

- There is no description of what the task will do ("increase development" here for comparison)
- There are no special random events associated with it right now. There should probably be negative events (bad steward) where popular opinion decreases heavily, control growth becomes worse.. on the other hand, positive events with the opposite effect.
- Has no effects other than converting culture and religion, perhaps using it could decrease development a bit every month, with the effect being lesser when you have a better steward.

**Comment by jj248** [comment]
OK - I've added more to this.  Should now display effects and have its own exclusively negative side effects.  I've removed the development reduction while I think on how best to implement.

**Comment by jj248** [comment]
County development reduction done - made it by half (rounded down) for now.

Ready to test for feedback.

**Comment by Jauffr** [comment]
The changes are functioning as of now. The differences between levels of stewardship are minor and the AI rarely decides to do this on mass at the moment

with an 11 stewardship steward
![Screenshot 2023-02-23 175543](https://user-images.githubusercontent.com/108106660/221065741-75e79cb8-86d8-4eb8-98e6-b96f15647656.png)

with 17 stewardship
![Uploading Screenshot 2023-02-23 175635.png…]()

with 30 stewardship
![Screenshot 2023-02-23 175653](https://user-images.githubusercontent.com/108106660/221065755-24ae1e8f-b5cb-4cd6-9ebe-46d478f12d1c.png)

**Comment by jj248** [comment]
Seems fine to me.  Closing.
