### ISSUE TITLE
Dúnedain Citadel fort level is overpowered

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#140]
Instead of the Dúnedain Citadel providing fort level, it could provide greater hostile attrition and control growth to maintain control of vital choke points.

**Comment by jj248** [comment]
These are still OP: 
![image](https://user-images.githubusercontent.com/26043074/150658724-a42a3a59-bbab-48e3-af50-1fe91f2ac70c.png)

The two extra insane things about this are the Fort Level +43 and knight effectiveness +20%.  Knights are already pretty strong, if you've got 5 holdings with these than your knights are twice as effective.  AND you'd get an extra 10 knights 😄

Better to think of these as "Hill Forts Plus" - a bit better than hill forts, but not by a huge amount

![image](https://user-images.githubusercontent.com/26043074/150658758-e8cb4fd8-712b-45be-8904-333e96a28bee.png)

**Comment by MattTheLegoman** [comment]
The design of the Citadel has been focused in its purpose. Some Númenórean Architecture buildings have been rebalanced in build-time.

**Comment by jj248** [comment]
These still feel very OP, all that's really changed is the reduction in fort level (with a few buffs to compensate) and an extended build time.  These are the current top 3 tiers:

![image](https://user-images.githubusercontent.com/26043074/151365816-804450d6-99bb-47be-9e90-475d727a5ad3.png)

**Comment by Vierwood** [comment]
The fort level should go up linearly, not double every level.

**Comment by jj248** [comment]
Balance notes:
- Fort level sky rockets for no reason in the last tier.  +26 is almost double the amount available from the most defensible vanilla fort buildings and more than three times the average.
- Defender advantage looks fine.
- Supply limit +40% is very large - most that any vanilla building chain seems to give is +15%.
- Tax is fine.
- Hostile raid time is very large - most that any vanilla building gives is +20%, the best *wonder* gives +50%.
- Control growth is fine.
- The knight bonuses are still crazy.  Each knight grants 100 Damage and 10 Toughness per prowess and most knights are at least prowess 10, so that's 1000 Damage and 100 Toughness per knight, bumped up even more by their effectiveness and expanding numbers.  This might be fine on a one off wonder but a player can get this bonus for *every* citadel they're able to hold. If I can hold 5 citadels then say, I can double my possible number of knights at double effectiveness. So 20 knights of say 15 prowess average results in a combined combat effectiveness of about 19,000 which is theoretically as strong as 7 units of heavy footmen MaA.  Oh and you'd get +4 piety a month for them too. :P

**Comment by jj248** [comment]
On their own, I think any of these 'higher than average' bonuses might be ok, but the fact that so many of them are way above vanilla is what gives me cause for concern.

**Comment by RedArkady** [comment]
Good argument to make Minas Tirith the benchmark and make any broadly similar citadel concept no better than, say, 70% of that with any one stat?

**Comment by MattTheLegoman** [comment]
The last two levels aren't available to the Gondorians.

**Comment by MattTheLegoman** [comment]
And you can check the commit for what did change.

**Comment by MattTheLegoman** [comment]
A better comparison is the Hill Forts, which has +16 fort level. And please look at the reworked costs, more suitable now with the plethora of bonuses that the Gondorians get, and please check the requirements of the last two tiers, the only tiers with knight bonuses, are locked for anyone other than a Númenórean.

I've rebalanced supply limit, we have very large armies in Gondor and this is suitable for them. It no longer reduces raid time.
