### ISSUE TITLE
Development growth buffs at holding level don't seem to work

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#142]
See:
![image](https://user-images.githubusercontent.com/26043074/123523792-fc00b580-d6bd-11eb-8535-c18ecb2a3dec.png)

Vs:
![image](https://user-images.githubusercontent.com/26043074/123523798-09b63b00-d6be-11eb-98ae-99f29b010e2b.png)

**Comment by Remerod** [comment]
I have not checked it's long time effect, but it is shown now in the tool tips on both the building and growth section. So i think it's all good and so i'm closing this! 

![image](https://user-images.githubusercontent.com/79544635/155861210-1cd00372-8581-423d-8ced-172a92c46415.png)

![image](https://user-images.githubusercontent.com/79544635/155861218-967f1388-12a3-4d78-8003-9f35fb116b8f.png)
