### ISSUE TITLE
Bellakaze custom calendar

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#145]
BELLAKAZE MONTH NAMES
Dahlat
Najam
Manjaz
Vetrashu
Ishat
Vatrul
Mizir
Kuralid
Darat
Tamum
Sumat
Oluj

**Comment by jj248** [comment]
Done - added a new game rule option for this.

Test will be to make sure this and the other calendar systems work in-game.

**Comment by Remerod** [comment]
I went in to the game rules, choice the Tumakveh Reckoning in the Calnder system
I played the game for a year, each month coresponse with this order

> BELLAKAZE MONTH NAMES
> Dahlat
> Najam
> Manjaz
> Vetrashu
> Ishat
> Vatrul
> Mizir
> Kuralid
> Darat
> Tamum
> Sumat
> Oluj

So if that's the intent it works! :)

**Comment by jj248** [comment]
Perfect - thanks.  Closing.
