### ISSUE TITLE
Tributaries & Protectorates

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#147]
Implement tributary system to replace Mordor tribute decisions and add Free Peoples Protectorate varieties.

**Comment by jj248** [comment]
Almost done, just need to finish off AI.

**Comment by jj248** [comment]
Ready to test.  Things that need to be confirmed as working:

**Protectorates**
- Can only be established by Good-aligned characters.
- Can only be established between independent rulers not at war.
- Tribal governments should not be able to form protectorates.
- Protector must be higher tier than protectorate and at least duchy tier.
- Should have a hint appear for neighbouring rulers you can make protectorates.
- Acceptance modifiers should _make sense_ and feel balanced.  Easier than vassalisation but not so simple as to be able to spam everyone.
- AI should only target neighbouring rulers and should not offer protection to those in the de jure area of their primary title (as presumably they'd rather take that territory for themselves!)
- Protectors should be called into defensive wars of the protectorate, except where they're already in said war on the other side.
- Protector and their vassals (and vassals of vassals) should not be able to declare war on the protected.
- Attacking a protectorate should give a warning that they're a protectorate in the war declaration UI.
- Protectorate should be able to be broken by either side, but AI should not break them.
- Protectorate should be broken if protector fails to defend protectorate in defensive war.
- Otherwise, protectorate should pass on through inheritance.

**Client States**
- Available to all independent, non-tributary / protectorate characters of duchy tier or higher.
- Can target any independent non-tributary / protectorate character.
- War cost should be reasonable (currently scales with target realm size).
- War should be invalidated if either ruler ceases to be independent, becomes a tributary, the attacker becomes a count or the defender loses all their titles.
- AI should use this CB and:
   1. Should only target neighbouring rulers and should not offer protection to those in the de jure area of their primary title (as presumably they'd rather take that territory for themselves!).
   2. Should be more common for evil / dominion of the dark faith characters.
   3. Should be less common for good / echoes of the ainur faith characters.
- Monthly gold contribution should be 20% of raw income to suzerain. This should feel balanced.
- Suzerain should be called to defensive wars against client states, except where they're already in said war on the other side, breaking if they fail to support.
- Should also not be able to intervene if it's a war between two tributaries.
- Suzerain and their vassals (and vassals of vassals) should not be able to declare war on the client state.
- Attacking a client state should give a warning that they're a protectorate in the war declaration UI.
- Client state should be able to break free from their suzerain via CB, with potential for other tributaries to join.
- Otherwise, client state should pass on through inheritance.

**Tributary States**
- Available to all independent, non-tributary / protectorate characters of duchy tier or higher.
- Can target any independent non-tributary / protectorate character.
- War cost should be reasonable (currently scales with target realm size).
- War should be invalidated if either ruler ceases to be independent, becomes a tributary, the attacker becomes a count or the defender loses all their titles.
- AI should use this CB and:
   1. Should only target neighbouring rulers and should not offer protection to those in the de jure area of their primary title (as presumably they'd rather take that territory for themselves!).
   2. Should be more common for evil / dominion of the dark faith characters.
   3. Should be less common for good / echoes of the ainur faith characters.
- Monthly gold contribution should be 30% of raw income to suzerain. This should feel balanced.
- Suzerain should be able to call their tributary states into any wars they're involved in, except where they're already in said war on the other side.
- Suzerain and their vassals (and vassals of vassals) should not be able to declare war on the client state.
- Attacking a tributary state should give a warning that they're a protectorate in the war declaration UI.
- Tributary state should be able to break free from their suzerain via CB, with potential for other tributaries to join.
- Otherwise, tributary state should break when the suzerain dies.

**UI**
- Suzerain / Protector should appear in the character window where a liege would normally appear for vassals.
- Game concepts should be readily available and explain mechanics well.
- For the Suzerain / Protector, a foreign tab should appear in the character window listing all protectorates / tributaries, along with their realm size, military strength and tribute (if tributary).
- Tributary map mode should be available in game, showing an accurate and useful summary of global tributary relationships.

**Comment by JukeJukestar** [comment]
If possible I think it would be great if tributaries were more integrated with existing vanilla mechanics

- Heregeld perk could also increase tributary tax by 10-20% in addition to 10% vassal tax

- "Assertive Rulers" (or one you consider more fitting without being OP) dynasty legacy could increase tributary tax by a furter 10%

- Suzerains should have the option to join into tributary states defensive wars, without it being legally binding (hate it when I make someone a tributary state, but they are immediately conquered by someone else cause theyre weakened)

- If possible, a successful claimant faction in the tributary realm should not end the tributary relationship

- Having a protectorate could also give a small piety or prestige buff

**Comment by Remerod** [comment]
While not having tested tributaries in great expense yet, I have to say that i think they work well in the capacities i've seen them playing out, with no obvious problems. 

Although there is a quality of life i miss, or rather that is a very big Issue. As the overlord i can see easily in the foreign tab how much income i get from my tributaries. But i would want that to be shown at my monthly income tool tip also. Especially as a tributary i have no way currently to see what i pay my Suzerain/overlord.

Having a control of your economy is important in ck3 and being able to see your income and expenses each month are vital.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150679918-ea4dd531-7adb-4331-a56f-7c4635eca15d.png)
the tab foreign shows money.

![image](https://user-images.githubusercontent.com/79544635/150679990-8e3e9801-e2a3-4f02-b56e-69ed5b35d81f.png)
Suzerains/overlords income.

![image](https://user-images.githubusercontent.com/79544635/150680061-c8ee098d-7b9a-4fc1-b40f-a39585c49e0c.png)
My Monthly expanses, as a tributary(Sûladan, as shown above) don't show what i pay my Suzerain/overlord.
</details> 

(i used an old save to showcase my pictures, but i double checked to see the case is the same as the current mod update)

**Comment by jj248** [comment]
Unfortunately it's not currently possible as the breakdown is a bit of a black box that we can't touch.  The modding coop seems to think that we might get this functionality in the future though so I'll keep an eye on it.

**Comment by Remerod** [comment]
is their no other way to see it then? since the overlord can see it in the foreign tab, maybe the tributary can get to see it under it's suzerain's head somehow?
