### ISSUE TITLE
Gondor and Rohan call on Oath of Eorl when army size is reduced to low figures in minor wars

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#166]
A better solution might be to adjust the AI to only guarantee answering the Oath in full when their partner is against (say) Forces of Evil opponents and is outnumbered, and some lower chance in other scenarios that we can adjust (e.g. more likely if not in a war themselves, less likely if the war has been going going for some time, more likely if they have good relations etc.)

https://discord.com/channels/751097183448727552/778645689089392730/902460042870145025

**Comment by jj248** [comment]
Not a huge issue for v2.2.  Going to push towards v3.0.

**Comment by JukeJukestar** [comment]
May also want to add a check so the oath is only answered when going against a king or emperor.
Reasonsing being they should be able to handle a duchy tier title themselves

**Comment by jj248** [comment]
Now requires you to be in a defensive war against an Empire
And you'll only be inviting the other party to join every war against another empire.
I've also localised the triggers and effects.

Ready to test.

**Comment by jj248** [comment]
Now tweaked to empires *and* kingdoms.

**Comment by JukeJukestar** [comment]
Works as intended, ran some tests.
There are still some situations, for example if rohan fights saruman with gondors help and is then attacked by mordor, where the cooldown is really detrimental. Maybe we could reduce it to five years, since its only used for specific circumstances now?

**Comment by jj248** [comment]
Have tweaked this down to 5 as suggested.

**Comment by JukeJukestar** [comment]
Works well. Reopen if any odd behavior is encountered or it is considered too harsh

**Comment by jj248** [comment]
Interesting - I'll consider this.

On the Protectorate point.  That feels fine... I might just disable the oath if a protectorate is in place.

**Comment by jj248** [comment]
OK @JukeJukestar - I've added an extra condition that you mustn't already be fighting alongside Gondor / Rohan in a war to invoke. 
![image](https://user-images.githubusercontent.com/26043074/215774453-016b8660-0a0b-49d8-b940-b9194de0dfb0.png)

**Comment by jj248** [comment]
Moving back to testing.

**Comment by savagesach** [comment]
I'm testing the issue and this makes no sense. For some reason gondor is unable to call rohan into a war against sauron because it says there's a cooldown despite the fact that the oath hasn't been called once this entire game.
![image](https://user-images.githubusercontent.com/86676697/221512088-fbe6ddfa-f535-4e8a-817e-4ce17ed25685.png)

**Comment by savagesach** [comment]
I got the golden realm to attack rohan to see if rohan could call upon the oath or not, and they can do it without any problems
![image](https://user-images.githubusercontent.com/86676697/221512330-f8891c77-dcad-4f54-b439-4acaf3880ebd.png)

**Comment by jj248** [comment]
> I'm testing the issue and this makes no sense. For some reason gondor is unable to call rohan into a war against sauron because it says there's a cooldown despite the fact that the oath hasn't been called once this entire game. 

I assume this is what's left to comment on?  How are you sure that they didn't take the decision?  Decision cooldowns can only really be initiated by the decision being taken, so I'm pretty sure this was taken here @savagesach ...

**Comment by savagesach** [comment]
okay yeah I tried it in another game and it's fine, I must have missed the war. In that case, the oath works as intended
