### ISSUE TITLE
'Orientated' sex dominance doctrines conflict when game rule is set equal

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#173]
https://discord.com/channels/751097183448727552/778645689089392730/879411376257392691

**Comment by jj248** [comment]
Fix applied, ready to test.  Equal should set all to equal.  Opposite should switch oriented doctrines.

**Comment by Remerod** [comment]
seems to be linked to [Issue 287 Certain Game Rule not working](https://github.com/MattTheLegoman/RealmsInExile/issues/287) (so a double issue have been made, my bad!) and if that is the case i don't think it's working now?

**Comment by Remerod** [comment]
tested the game rules for issue https://github.com/MattTheLegoman/RealmsInExile/issues/287 and it seems that he games rules are working now! Nice work! closing this issue on https://github.com/MattTheLegoman/RealmsInExile/issues/287 and here
