### ISSUE TITLE
Horse Master trait inheritance is scuffed

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#187]

**Comment by jj248** [comment]
See above issue for additional commentary

**Comment by jj248** [comment]
Have moved the most relevant benefits of the trait into a new regional tradition for Hadorim heritage cultures that Rohirrim start with.  I've culled the trait.

**Comment by Remerod** [comment]
checked the game at the start, let it runned for 30 years so characters could spawn and checked again in the rohan realm and surround ones, while also searching for the trait Horse Master, i could find nada. So i think it's safe to assume that the trait have been culled away for the game.
