### ISSUE TITLE
Numenorean Government

### ISSUE THREAD

**Issue by VectorMaximus** [MattTheLegoman/RealmsInExile#191]
A catch-all government for Numenorean and Numenorean-descended culture (working name Numenorean autocracy). Basically a feudal+ that also allows the holding of towns. A broader replacement for the old stewardship government type.

**Comment by jj248** [comment]
Easy to do in principle, but need to run through all the stuff that touch government type in triggers etc.  Let's defer to v3.0 and consider alongside republics at the same time.

**Comment by JukeJukestar** [comment]
Careful with how this affects balancing, if you have a lay clergy religion you could hold all holding types at once which may be overpowered

**Comment by Remerod** [comment]
I know that Vierwood is doing some stuff with this, so assign him this

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/194717951-c6801ed0-745f-4363-9845-53a3b2c45d2b.png)

It would appear that one of the recently added governments (elven, numenorean or despotic) has glitched feudal contracts, there is now a second religious excemption!

**Comment by JukeJukestar** [comment]
The government description should also explicity state what features the government has and how it differs from regular feudal.
This is also a vanilla issue tho, because unlike ck2 the ck3 government descriptions are pretty vague

**Comment by JukeJukestar** [comment]
As of 19.1.2023 we have decided to take numenorean government out for now.
we may revisit it in the future, ideally once PDX releases a governments DLC
