### ISSUE TITLE
Men at Arms for new cultures

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#192]
For:

Bellakar
Tedjin
Ray
Tulwang
An-Balkumagan
Abrakhan
Sand People

**Comment by JukeJukestar** [comment]
Abrakhan doesnt get their MAA because of the Nazgul culture
Balancingwise I havent seen anything gamebreaking, the only real thing I noticed is that as Bellakkar you dont get a Numenorean heavy infantry equivalent like the other RiEs and that impacts how well you do against foes that do get them like Umbar and the Stormhost

**Comment by Jermanlordy** [comment]
Abrakhan does not have any custom Men at Arms it can recruit, even though they have custom event MaA and start with special Abrakhani MaA

**Comment by Remerod** [comment]
just want to point out beside Abrakhan as Jerman pointed out, the Aukuag, Arysor, Mardrukan, Jelut, fariyin, gúsar, Gai, Bellanarûd nor the Tandi cultures have access to custom MAA while other "minor" culture like Qarsag or the Siaken culture does have access to MAA in thir culture groups.

**Comment by Remerod** [comment]
I also want to bring up a topic, should cultures have several options between the custom and normal MAA when they are the same type? I'm not saying I'm against it, as i can see it as a good option when some are cheaper while other is more expensive but better. But some are bot cheaper and better, and what's the point of having access to both of them then? maybe that's something that's need balancing out? 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150679455-136d34a0-b648-416d-8f00-b4beb25034d3.png)
several options between same maa types.

![image](https://user-images.githubusercontent.com/79544635/150679491-bef9c6ec-65f1-4812-b7f3-5a436f707f71.png)
basic armored footman.

![image](https://user-images.githubusercontent.com/79544635/150679512-40b8dfdd-9c4f-41b3-9da4-0e9099d7a2d2.png)
custom MAA that's better and cheaper then the normal armoured footman maa, with the only minus of them having some bad terrain modifiers
 
</details>

**Comment by VectorMaximus** [comment]
Those cultural MAA have less units per regiment, so their power roughly equals out with the regular heavy infantry.

**Comment by VectorMaximus** [comment]
> Balancingwise I havent seen anything gamebreaking, the only real thing I noticed is that as Bellakkar you dont get a Numenorean heavy infantry equivalent like the other RiEs and that impacts how well you do against foes that do get them like Umbar and the Stormhost

The Bellanarud Auxiliaries are meant to counter heavy infantry.

**Comment by Remerod** [comment]
It's only the Abrakhan MAA that's need to be fixing right for this issue to be resolved?

**Comment by Remerod** [comment]
I'm moving this to Bugs, because i am assuming Abrakhan should have access to some special MAA
