### ISSUE TITLE
Update surround map

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#198]
Update surround map to ensure appropriate border fog.

**Comment by jj248** [comment]
Updated mask.  May need one extra revision once impassable terrain around border of Abrakhan is trimmed back, so will keep this issue live until that is done.

**Comment by jj248** [comment]
Trimmed back now - leaving as an opportunity for Matt to refine if he'd like.

**Comment by MattTheLegoman** [comment]
Alongside the paper map, this has been updated.
