### ISSUE TITLE
Finalise terrain and heightmap painting

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#200]
Finalise terrain painting, particularly: 

- Oases and variety in the Dune Sea
- Adding source hills for Harnen tributary streams
- Fixing terrain clipping in shallow seas (particularly near Tulwang)
- Water colour map (particularly visible line in south and river colouring)

**Comment by jj248** [comment]
Committed my last map update pre release, covering all points except water colour map.

@MattTheLegoman - things to note, though not crucial for release:

- I shifted a river in Chelkar that was riding up a mountain - implications for watercolour map and flat map
- I added hills to act as sources to the tributaries of the Harnen and hills in the area between Chelkar and Pezarsan (as per map below) - implications for flat map. (Haven't gone as far as to add mountains like in map, but could if we wanted I guess). 
![harnendor](https://user-images.githubusercontent.com/26043074/149641480-f105a09e-237e-4867-930e-f2e8e098c9a1.jpg)

**Comment by MattTheLegoman** [comment]
The water colour map has been rebuilt with a new underwater heightmap generated in Gaea layered with real-world data.
As it has been rebuilt, there's no obvious cutoff line in the south.
The above tweaks to rivers in Harad have been included in the new water colour map.

**Comment by jj248** [comment]
All issues have been covered - only outstanding action is a potential tweak to the flat map, but not super urgent or release critical so closing this issue.
