### ISSUE TITLE
Rebalance existing MaA

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#201]
Existing MaA are quite unbalanced.  We should use combat effectiveness and cost efficiency measures to properly rebalance these.

**Comment by VectorMaximus** [comment]
Currently all cultures are able to recruit Horse Archers. Need to look into.

**Comment by jj248** [comment]
He's doing it... he's doing the rebalance... (moving to In Progress).  Please avoid adding any new MaA while I do this. <3

**Comment by Vierwood** [comment]
🙏

**Comment by jj248** [comment]
First pass of the rebalance is now done and ready for tester feedback.  Let me know of any remaining imbalances or oddities.

**Comment by jj248** [comment]
Wait a tick @JukeJukestar ... What's the base damage and toughness for these guys?  It *should* be 10, which makes the 2 more reasonable.  Are they just getting massively pumped up by Rohan horse buffs?

**Comment by jj248** [comment]
Closing this large issue as no huge issues raised so far - we can deal with any issues arising on a case-by-case basis.
