### ISSUE TITLE
Review of innovations

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#205]
Ensure all innovations per culture are appropriate.

**Comment by jj248** [comment]
These have been done - happy with them for release.

**Comment by jj248** [comment]
(Can tweak as needed from playtesting and feedback).

**Comment by Jermanlordy** [comment]
The Horse Archer MaA is available to everyone

**Comment by VectorMaximus** [comment]
Tweaks made to southern cultures - minor tweaks are still in the cards, but broadly, this is good
