### ISSUE TITLE
Random Entertainment and Informative Texts need to be given Middle-earth themed names

### ISSUE THREAD

**Issue by ercarp** [MattTheLegoman/RealmsInExile#21]
**Random Entertainment Texts** and **Random Informative Texts** (found in `localization\<language>\custom_localization\regional_custom_loc_<language>.yml`) need to be given Middle-earth themed names to prevent things like Jerusalem and Byzantium showing up in the mod.

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/78575425/113494457-f9dcef80-94f0-11eb-9622-382b6f415545.png)
![image](https://user-images.githubusercontent.com/78575425/113494456-f6e1ff00-94f0-11eb-9a3b-ecbe1b4fd309.png)

</details>

**Comment by VectorMaximus** [comment]
I think I've fixed it, but somebody should probably test it ingame before calling it closed.
