### ISSUE TITLE
Fix locators that are still in old positions from pre-province rework

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#210]

**Comment by jj248** [comment]
I've taken a look over the new areas and I'm pretty sure these have all been captured now, but I'll leave it as an open testing item to make serve as a reminder that if anyone sees any dodgy army or holding placements, or army pathfinding, it should go here! :D

**Comment by VectorMaximus** [comment]
Most if not all of these has been gotten. If we come across any, will make fixes as needed. Closing
