### ISSUE TITLE
Sauron can be killed by a feast event

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#216]
https://discord.com/channels/751097183448727552/778645689089392730/910206663187894322

**Comment by jj248** [comment]
I've forbidden Maiar, Istari and Nazgul from attending feasts as guests. They're already forbidden from starting them, I can't really imagine the Witch King accepting the invite, and he'd be poor company anyway...

Should test to make sure no Feast invites are received as these characters and one cannot organise a feast.

**Comment by Jermanlordy** [comment]
I Played Sauron for 10 years and never had an invitation to a feast
The Only way Sauron can join a feast if he hosts one himself thru descisision
