### ISSUE TITLE
Mechanics for becoming a sorcerer

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#218]

**Comment by jj248** [comment]
Gseg unavailable to complete ahead of February - pushing back to 3.0. :)

**Comment by JukeJukestar** [comment]
consider adding an event to choose wether to teach sorcery to one of your children or wards.
AI weight should be high on yes
Chance to teach it to wards and primary heir should be higher than other children

**Comment by jj248** [comment]
Closing and linking to #425
