### ISSUE TITLE
Spouse remains Ward despite character being an adult

### ISSUE THREAD

**Issue by ercarp** [MattTheLegoman/RealmsInExile#22]
_Reported by **Sevroh** on Discord._

> In my game i've still got my wife (31) as a ward, and the option to remove her as a ward is greyed out. Any ideas?

> i started a game as Faramir, and wanted her as a ward to keep an eye on her while i waited for the events to unfold..

In this person's game, their wife remained their Ward at an adult age and the option to remove her as their Ward was grayed out. The character they married is Theoden's niece, Eowyn (`ID: 6000035`) and they were playing as Faramir (`ID: linesteward40`).

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/78575425/113494680-3f022100-94f3-11eb-9b68-d8825256b95c.png)

</details>

**Comment by ercarp** [comment]
I wonder if this is somehow related to the `cannot_marry` trait Eowyn has.

**Comment by RedArkady** [comment]
I've not been able to replicate this. Recommend close.

**Comment by VectorMaximus** [comment]
Unable to replicated, has not come up again. Closing
