### ISSUE TITLE
Weird Blue Orbes

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#224]
In Lothlorien, Fangorn and Dunland there are strange blue orbes that appear when you zoom in to a certain point, But when you try to zoom in on them they dissapear.

**Comment by Remerod** [comment]
I've also seen this, in southern dunland or the place frecafort/castle was (speaking from memory), saw it during my small dunland run/review a couple of days ago, i also have seen it one time in southern harad i think? but it also was a showing/not showing when scrolling/zooming around

**Comment by jj248** [comment]
I've never once seen these... could it be a graphics setting issue?  I always run with the highest settings.

**Comment by jj248** [comment]
Confirmed caused by low object gfx settings.
