### ISSUE TITLE
Numenor-in-Exile

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#226]
New united title if Gondor, Umbar, Madruak, Bellakar and An-Balkûmagân de jure territory all held. Possible new culture attached to this.

**Comment by jj248** [comment]
Implemented and ready to test.

Requires player to be Gondor, Bellakar, Thani Hazad or Umbar; as well as being of numenorean cultural heritage and in possession of three of: Thani Hazad, Umbar, Bellakar and Gondor titles.

**Comment by jj248** [comment]
You end up having to conquer the exact same area regardless to take the decision. More importantly, the current setup means that both Gondor and Bellakar can get their maximum historical domains, and once Arnor is added the RK will naturally have the decision appear
