### ISSUE TITLE
Bellakar - Prophetic Dream

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#227]
Give the starting character an early 'prophetic dream' event. This would explicitly parallel Boromir and Faramir's dreams. Give him visions of the Return of the King and the Battle of Pellenor Fields - maybe with a link to the stories of Aragorn's travels into the far south, suggesting that he is known to Bellakar. This would give the character/player a starting dilemma and prompt - do you focus your efforts on local expansion and consolidation, protecting Bellakar against neighbouring threats? Or do you take the riskier but Eru-inspired focus on expanding north, with the explicit aim of reaching the diplomatic range of Gondor and being able to come to its aid

**Comment by RedArkady** [comment]
Seems to be working perfectly - recommend closing.

**Comment by JukeJukestar** [comment]
Works for me too. Funnily enough I got lunatic a few years later so maybe you shouldnt trust all of my prophetic dreams

**Comment by VectorMaximus** [comment]
Sounds good. Closing
