### ISSUE TITLE
Battle predictions are not displaying correctly

### ISSUE THREAD

**Issue by ercarp** [MattTheLegoman/RealmsInExile#23]
_Reported by **Pra1rieDog** on Discord._

> This is probably already known, but all my battle predictions are "evenly matched". Even though lets say I have 5 times the amount of troops, etc. I think this is causing my enemies to suicide rush me with tiny armies as well

In this person's game, all of their battle predictions were evenly matched. In the screenshot attached below, their army of 2350 men were approaching an army of 167 enemies sieging a castle.

He suggested this may also be affecting how the AI wages their wars, but I don't actually know if that's the case since I'm unsure how the army AI works in CK3.

> I think the ai are unknowingly fighting battles they cannot win (possibly even refusing to fight battles/wars they aren't aware they WILL win)  - I think that's how the ai functions in decision making anyway...?

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/78575425/113495230-ce5e0300-94f8-11eb-835d-55df8f0e4b22.png)

</details>

**Comment by jj248** [comment]
Closing - merging with related bug #39.
