### ISSUE TITLE
Small review of the Shattered realms in 2.2 and a proposal

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#233]
So i was wondering how the Shattered realms would work for the 2.2 update, so i had a look.
So I played a observer game for 100 years with everyone set as counties at start.

So as we see on this map after 50 years of gameplay, many are still 1 or 2 counties, a few duchies and as it is even was prior to the far harad update, Umbar is the fastest realm to reemerge (Most likely because claims + good position). In my prior experience the Witch king do well to. The other 2 major powers would be Isenguard unleashed and the independent de jure tribal above where bellakar usealle is. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/147292084-49716e1a-4a9a-404e-afeb-a803d4c26c2f.png)

</details>

After 100 years, a few more kingdoms have emerged, most counties have unified to duchies but not all. Overall I think it's start to look's like a typical shattered map now.  
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/147292130-2691c1a4-8301-45af-8878-6ec305bf1bd5.png)

</details>

So, i think people stay as counties for to long, especially in the 2.2 area, biggest reason is because there are mostly only religious wars as available to them. This is the reason why the more... warlike faiths have a easier time to form because they have access to war casus belli a lot earlier then other, and the first 20 years are essential to collect a realm (taken from my ck2 experience form the top of my head). But it's just not the 2.2 realms that have problem often, haradwaith and gondor often takes long to consolidate.

So as a small proposal i would like to see something return from ck2 for the Shattered World, the **Consolidation Cassus Beli**. The ck2 feature _Consolidation Cassus Beli_ allowed for vassalization of any neighbor and could be set to off, 25 years, or 100 years. This helped the early game for the shattered world to get along nicely, realms rulers around the map started to consolidate their realms as the same phase as the player, which meant when the player achieved to create a Kingdom chances where that the AI would do so at a similar time.

So my suggestion would be to add a Consolidation Cassus Beli for everyone at the start of a shattered realm playthrough, that either vassalizes or conquer target opponent, and just as before have the options of having it off, 25, 50 or 100 years.

**Comment by MattTheLegoman** [comment]
They should be creating claims.

**Comment by jj248** [comment]
As an experiment, I gave every ruler the county conquest CB.  It doesn't seem to be materially affecting their expansion imo.

@Remerod 

![image](https://user-images.githubusercontent.com/26043074/147373752-d2c53ec1-b210-486f-9897-3ddf66a7bd5c.png)

**Comment by Remerod** [comment]
I think it looks a little chunkier but not much no, although Umbar looks more held at bay and there also seem to be less single county counts.  Is there a opinion difference of vassalisation wars and conquest wars? like if you holy wars a certain faith those of that faith would dislike you right? (if i remember correctly). I still think your pic Jamie looks better then mine somehow.

Here's the wiki page for ck2 shattered world at least if it's any help:
https://ck2.paradoxwikis.com/Random_World

**Comment by Remerod** [comment]
Had a test with added conquest cb for shattered world
Overall i think this makes more "even" expansion for everyone, whatever you are of the "evil" or "good" folks of the middle earth. Where before the "evil" clearly had the advantage in expansion. 

<details>
<summary>Click to expand</summary>

25 years felt to me to almost have the same effect as for 50+ years of my first test in this issue (with the exceptions of umbar, with-king ithilien and bellakar tribal realm)
![image](https://user-images.githubusercontent.com/79544635/147626548-79691465-0363-4e6a-a5e7-3162218e4c3d.png)

Where 50 years most people have expanded, a lot have made duchies and some have reached kingdom rank. overall it's a lot more "even" in realm sizes around the world.
![image](https://user-images.githubusercontent.com/79544635/147626635-0528bd51-5703-4935-b682-b08fc90f9c74.png)

</details>

**Comment by JukeJukestar** [comment]
Found this yesterday while playing shattered counties:

Around sauron there are fallen maia counts, maybe have rulers based on county culture instead of previous owner culture if thats possible

**Comment by jj248** [comment]
Matt's fix is good.  Bringing this to a close.
