### ISSUE TITLE
Golden King of Abrakhan death

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#234]
The Golden King of Abrakhan needs to be added to the event chain that kills Sauron and the other Nazgul when you win the destroy Mordor war.

**Comment by JukeJukestar** [comment]
If alive, would be cool if the black vizier took over his counties and duchies, while his kingdoms and empires are destroyed

**Comment by jj248** [comment]
Going to roll this one in with #235 as it can fall as part of the review.
