### ISSUE TITLE
Random nudity

### ISSUE THREAD

**Issue by Foadar** [MattTheLegoman/RealmsInExile#236]
Random characters of various cultures appear without their clothes on. Possibly for similar reasons as Sauron and Saruman exposing it all. As this includes actual female nudity (boobs) instead of just bare chested men, this is probably something that should be fixed for release. From what I have personally seen, once a character is interacted with, such as moving court, clothing does appear.

**Comment by jj248** [comment]
Confirmed as being an issue with Barbershop mod and load order.  Closing.
