### ISSUE TITLE
Alignment map mode

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#238]
Map mode to show moral alignment of county holder's faith.

**Comment by jj248** [comment]
Ready to test, making sure it is intuitive and visually clear what it represents.

**Comment by JukeJukestar** [comment]
Seems to work, its hard to make out an individual men of darkness rulers color but its great for giving an overall impression of how the world is algined

**Comment by jj248** [comment]
Great - seems fine to me too.  Closing.
