### ISSUE TITLE
Schemes get stuck in an infinite loop

### ISSUE THREAD

**Issue by ercarp** [MattTheLegoman/RealmsInExile#24]
I've read three distinct reports on Discord from players experiencing issues with **Seduction** schemes (unsure if this is also the case for **Romance** and **Murder** schemes) getting stuck in an infinite loop.

From **Ryankarlsen1**:
> also the when someone tries to romance my character "the reading at dol amroth" keeps popping up no matter how many times i close it. The only way i got past it was to cheat murder the person romancing me.

From **GasPOGne**:
> I keep getting this event over and over again. I just tried saving, going to the main menu, and reloading, but it didn't work.
<details><summary>Attached screenshot</summary>

![image](https://user-images.githubusercontent.com/78575425/113504364-4ef42200-9540-11eb-9296-5ac1ba68b78f.png)

</details>

From **Jtd7**:
> currently the events for seducing/romancing/murdering are broken; they repeat, and they usually never give the effects

**EDIT**: **Dregorin** on Discord confirmed this bug doesn't seem to affect murder schemes. Or at least he was able to murder people successfully.

> Not the case for me, I succesfuly murdered Aragorn yesterday

**Comment by jj248** [comment]
Closing - merging with related bug #39.
