### ISSUE TITLE
Small Dunland review

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#241]
![image](https://user-images.githubusercontent.com/79544635/148485644-2972e76f-b9ce-44c0-b9fc-86c498f089dc.png)

So a smaller review, played only 30 years (i might play some more), I got distracted with all the discord streaming :P

**Test:**
So currently Dunland gameplay is very easy (up to a point). I easy expanded downwards the first 10 years, with both conquest and swaying people into vassalage 
<details>
<summary>Click to expand</summary>

10 years
![image](https://user-images.githubusercontent.com/79544635/148485770-c9d2e64c-e5bd-446d-8c09-a0e06cebddb5.png)

</details>

There was never really any threats, the only waiting and so on i did was to accumulate money, honor and prestige, then it was on to the next conquest. I never had problems with either feudal or tribal vassals, in fact most loved me with some exceptions (and then i forced most to convert religion and so on). Around 20+1-3 years into the game i had formed the kingdom title Dunland. But around the year 3030 Isengard attacks me with 20000 disciplined uruk hai army (But my lord there is no such army!), so i decided to make a stop there, (maybe it's winnable with some cheesing and so on). 
<details>
<summary>Click to expand</summary>

30 years
![image](https://user-images.githubusercontent.com/79544635/148486467-07a3ba23-4d2f-4ced-8724-16ceb25460db.png)

</details> 

**Summary/Result/Thought's:**
In the 30 years i played, i never needed to use the _Assemble the warbands_ decision, I never upgraded my MAA and i never did any alliances, because there was no need to, most wars was a cake walk, whatever it was against feudal or tribal enemies.

As i said earlier the feudal vassal vs tribal opinions didn't seem to matter to me. Most had 50-100+ opinion of me with some exceptions. So this was no issue for me.

One thing that greatly confused me was the _Draw Out Saruman's Influence_ because it's not obvious what that means, i haven't played Isengard since the rohan, isengard & dunland version so i have a vague remembrance that Saruman could influence people. but the decision here doesn't tell me this, it tells me that he is in my dreams, it tells me i can draw out his influence? i assume this mean that i can stop me for possessing me? but it could also mean that i want his influence? If i hadn't played Isengard in that earlier version this would have confused me tremendously. Maybe it's my English skills but the decision is far from obvious to me and should be a little clearer on what it means. 
<details>
<summary>Click to expand</summary>

the Event
![image](https://user-images.githubusercontent.com/79544635/148487493-0aebb618-cb1c-4eca-aabb-e111920e9800.png)

</details>

An other Isengard related issue is that he started to raid me (while he supposedly possessed me), while this was not a huge problem, not costing me much money i just needed to circumvent the raiding armies while i had my other wars, it felt.... not very lore friendly? 
With the new tributary i would rather have that tied to me, forced to contribute to the great machination of isengard, then having a stack of 9k troops raiding me every now and then. But that's my opinion. 

So currently the first 30 years playing Dunland was very easy, Isengard came knocking 30 year into the game and i guess i don't consider that easy but they wanted just one county, so it was not that devastating either. So from what i've played i guess i would want Dunland a little harder and have something more obvious connection with Isengard, whatever that is a good or bad one, because if Isengard wasn't to conquer me and the area in general then maybe that's something to expand upon? 

Hope this small review contributed somewhat, might play some more but i thought it answered the tribal vs feudal question at least. :)

**Comment by jj248** [comment]
Tribal vs feudal question answered - happy enough with where this is now.  Going to keep it in the v3.0 triage for the relevant comments around some of the Saruman interaction.  Saruman and Rohan in general could probably use some TLC in v3.0.

**Comment by JukeJukestar** [comment]
very old review, closing it
