### ISSUE TITLE
Juke's Personal Review of Umbar in 2.2

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#242]
Yesterday I played a game as Umbar, very interesting campaign for sure! Encountered some smaller bugs and issues though, especially towards the end of the campaign after regaining Gondor for the glorious Castamiri.

**Starting Out**

The first few years are pretty calm, because of Kahuphazgan's excellent diplomacy it is pretty easy to diplomatically annex most smaller states around you.
After you conquer the two small tribal counties above you on the coast, Shafra and Suk Oda, Abarloni, zimraloni and celebiant will accept vassalization. (getting them early is important because otherwise they will be crushed by gondorians or haradrim)
Later you will have to go to war with Haruzan to form the kingdom of mirlond.

On the west coast theres a similar situation, Annabrith will immediately accept vassalization on game start and after that you have to retake some coastal Tedjin counties in order to get close enough for the madrukans to accept vassalization.

I personally really enjoy diplomatic gameplay where you convince your neighbours to join you. However, forming Anadune early is currently very easy. I was able to get it 14 years into the game and I suspect I could have been quicker if I rushed it. I imagine this will get harder once Haruzan in the east and the Tedjin in the south get their event chains and buffs.

**Early Balancing**

- You should consider nerfing Kathuphazgans diplomacy a bit, possibly even giving him lvl 3 diplomat instead of lvl 4
(Side Note: he starts out with two diplomacy trees already finished, because of how ck3 works theres a ~33% chance he wont start with the "true ruler" perk, making vassalization far harder in those playthroughs.)

- Brodvaga of Zorthan, a tedjin ruler, starts out as a count without his duchy despite controlling most of it. If he had a duchy at game start he would be less likely to immediately accept vassalization to umbar

- To keep AI Umbar from pushing into the desert, they start out with two jelut tributary states there. This is a pretty cool idea, but it also means that on succession they are removed and Umbar starts pushing into the desert again. The solution would be to make them client states instead, but that would make it so they no longer join your wars, which would break the idea of having those jelut tribes as auxiliary troops/ support troops. I personally think that client states should also join your wars.

- To make Anadune slightly harder to form, you could consider having the special creation condition of fully controlling Umbar (forcing you to fight against the Tedjin a bit more and get some jelut counties). You could also require a certain prestige level.

- Umbarean culture is on the same tech level as Gondor, and should get a bit of a tech nerf that kicks them out of the Late third age at game start. Considering the Stormhost with their Southern Adunai culture group is now implemented, the Black Numenorean culture group should maybe be renamed to Adunai for consistency.

**Cassimir and Burodapan**

- Due to a bug Burodapan starts out as kingmen despite being described as corsair in the start date.

In my games Cassimir usually murders Burodapan and you are powerless to stop him because he starts with a strong hook on you.
Playing as one of the heirs from game start to try and change the outcome isn't a good option because you will be unable to control Umbar in those crucial starting years.

**The Midgame experience**

One thing I love about Umbar is that once you've consolidated your realm, the game really opens up to you. Until succession kicks in, you will be severely weakened because your heir(s) holds a large part of your core counties in the duchies of Umbar and Calenfalas, but after either of them inherits Umbar quickly becomes a force to be reckoned with.
You can raid from Gondor to Ray, attempt to conquer Andrast or consolidate your rule over the Harnen.
Taking on Aragon will be nearly impossible, I personally only managed to after I got lucky as Cassimir and managed to murder him and get an alliance with mordor.

A big issue I see currently is that, it is theoretically very much possible to rush Anadune and quickly take over Gondor from the Stewards before Aragorn can arrive at all. I havent tried this, but I heard its possible and. because of the difficulty of beating aragorn, much more desirable.

**Bugs with taking over Gondor**

- Choosing to change the capital of gondor to Umbar or Pelargir does not change the dejure capital of Gondor

- The new castamiri gondor doesnt copy the title history of the original kingdom of gondor! Pretty sure this is a thing decision effects can do. I also think the new "stained gondor" should be a bit greener/ "sicklier" in color

- If, once you win the Castamiri claimant war, the current ruler of Gondor or any of their vassal (kings) hold land outside dejure Gondor, they will keep it as independent rulers, meaning you have to usurp a lot of the Gondorian kingdoms and grant it to vassals (Example: ruler of Anfalas controls one county in non-integrated Andrast, becomes indep and keeps the kingdom, you get all his counties within gondor and all his vassals)
(Example 2: Because harondor wasnt integrated into gondor in my game, Aragorn's son, who was the king of gondor at the time, retained his lands in harondor and became independent)

- Castamiri Gondor is immediately able to use the decision to Integrate Umbar, which is at that point already part of dejure gondor and doesnt make sense since the event calls castamir a Usurper

- Regular (Non Castamiri) Gondor's decision to integrate Umbar does not integrate Mardruak or Unified Zimraloni (if it exists) Solution: Pretty sure theres a decision effect in vanilla where everything in another empire's dejure is integrated into yours, change the decision to Integrate Anadune instead of just Umbar

- (Untested) Make sure that if you take the decision to Unify Mirlond and Ramlond as Castamiri Gondor, it isnt added to the defunct empire of anadune

**Comment by Remerod** [comment]
A Very well written review! As a tester i'm agreeing with most of these but especially the topic about forming Anadûne to fast. 14 years is definitely to fast in my opinion to form it, maybe not nerfs to Umbar but forming Anadûne should definitely be made harder to form in my opinion.

**Comment by JukeJukestar** [comment]
Quick Update:

- After the castamiri claim war the previous king/steward retains any titles outside current dejure gondor (namely any titles and vassals in andrast and harondor if they werent previously integrated)

- previous king/ steward also retains any kingdom and duchy tier titles that arent given to you via event (example would be ithilien)

**Comment by JukeJukestar** [comment]
closing since its an older review now and I like to clean up issues
