### ISSUE TITLE
Re-establish main house on Castamiri reclaimation

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#243]
By the start of the game, the true house of Castamir has died out.

If any of the houses in the Castamiri dynasty retake gondor, there should be either an event or a decision to become part of the original dead house of Castamir.
There would be a few options how this could work (if its at all possible, this I am not sure of)

1. The "original founding" of your house never takes place, all the members of your house (including dead ones) are retaken into house castamir. Probably not possible.
2. The new ruler of the reclaimed Gondor and all their children that are part of their house become part of the original castamiri house, your dead ancestors and brothers, uncles etc. stay part of your cadet house. Probably possible (?)
3. Your house is renamed to Castamiri, and your house COA is changed to be the original Castamiri one. This would make two identical houses appear in the dynasty viewer (yours and the original house castamir) but that is a small price to pay. Probably possible.
4. Same as option 3, exept instead of changing your current house's features it founds a new Castamiri house with the original COA. Would also lead to two castamiri houses appearing in the dynasty view, but would not remove your old house and your brothers/ ancestors stay in their own separate house

Option 2 and 4 would have the small issue that if the reclaimer dies without an heir and your brothers inherit, the house of castamir dies permanently.

On a tangential note, alternatively all Castamiri houses could become part of the original numenorean royal dynasty (right up there with aragorn's), but I am unsure if this would work or make sense with the lore.

**Comment by JukeJukestar** [comment]
Working mostly as intended! Some stuff I noticed:

- If you choose to keep Anadune instead of Gondor during the Reigns of Castamir (hehe) event you stay in your old house, assuming thats intended?

- Children of daughters in a regular marriage also become part of your house, making it possible to cheese this (marry daughter to emperor of Stormhost, have them make babies, fire castamiri claim, their child is now of your dynasty)
- same goes for men in matrilinear marriages

**Comment by jj248** [comment]
Comments as follows:

- Yes.
- Makes sense - I'll change it so it knows what it's doing in matrilineal marriages.

**Comment by JukeJukestar** [comment]
@jj248 works like a charm now!

**Comment by jj248** [comment]
Effect is recursive so should pass down 4-5 generations.  Wonderful - closing.
