### ISSUE TITLE
My Review on Umbar in 2.2

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#247]
Today i played an Umbar game from 3000 to 3058. 
So the first 3 years i started with vassalizing Annabrith and Zôrthân and after that i invaded the realms to the north of me to aquire my dejure dutchy of Sakal an-Khâr after wich i could vassalize Abârloni aswell. After that i invaded a weak Tedjin under Bór to aquire my dejure dutchy of Dûsalan and after winning that i was able to vassalize Khibilkadar, Khasmanakôr, Narik-Zadan and  Nykkea. then in the following years i would conquer the AA and form my Empire. Then in 3025 an oppertunity arose with Gondor being smashed by Mordor so i pressed the Castamire claim and invaded, in 3028 i would win the war and become Castamirioni Gondor. for the rest of the 30 years i played i would consolidate my realm.

Opinions
The Starting Ruler of Umbar is very OP and should either have a reduce in the diplo stat or a trait that makes him die quit early in the game.
The event that lets you chose a capitol after winning the war for gondor is broken as when i picked pelargir it didnt work.
Perhaps there could be a event tree about the rivalry between Câssimir and Burôdapân for example that if your Câssimir you go down a path towards reconquering Gondor to avenge Castamir!, and if your Burôdapân you go down a path towards Corsair domination across the shores of southern middle earth and perhaps a Corsair Nation that you can form

![image](https://user-images.githubusercontent.com/96250463/149628846-2afa1ffa-d3b1-4d57-9df6-3439b5009cbd.png)

**Comment by JukeJukestar** [comment]
Nice review, I agree with you that the initial diplo stat is a bit too strong. I would say same goes for both of his sons with martial and intrigue respectively. Maybe reducing their "main stats" in favor of a better stat spread overall would be a good idea.

**Comment by Vierwood** [comment]
Adjustments have been made.
