### ISSUE TITLE
Rémerod's review of  the Tedjin civil war + some beyond

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#249]
**Intro:**
I was really curious about the tedjin's and wanted to see how the new tedjin events/themes and civil war played out in the Mod, so started some test runs on the Tedjin Confederacy. 

**Test:** 
Started out as Kataj Ayal, and got a cool event telling me of the situation in his realm. It also explains that his son converted abroad, but all of the southern part of the realm (including the capital, Thri Zirakhan that have been the capital for generations) is part of this faith. I think it would be wiser to tie this lore into the southern part of the kingdom.

Not to much times goes on before Ayal dies and you get to play Bór (which was the first one i decided tested out in the civil war sides). 
you have a decent economy, decent way to expand you military, sway vassals and build up your nation. Deciding to do the civil war i did focus on taking the decision pushing into that in the theme/narrative event chain. The event chain themselves are quite good, but the "we give you troops" event could be a little more fleshed out i think, the one i liked best/most well written was the one for Sauron on Azumen's side. Onto the start of the war, having build up a lot of men of arms (like 3 new ones with upgrades), you stand a decent but small chance at the start of the war to succeed, with the odd's roughly 6.6k vs 10k (including all allies)by attacking their side before all the vassal participants gather in one spot. First time i tried this i was crushed within a year. I did try several times (with ranging army balance but always in favour of the rebel side) and the other times i tried i lasted several years from around 4-9years. It was hard, but it was very fun, one of the more good wars i've had in the mod in fact! In my opinion there is 2 major advantages they have, obviously a larger army and a lot more knights (can't remeber the exact number but it's about 3 times more on the rebel side). The amount of Knights/champions is obviously a huge advantage when both sides armies is in one battle.

And when testing Azumen out, and geting to the civil war I got roughly a even sided war because falaya joined Bór. but even when fighting battles when the "Bór" side outnumbered me with say a thousand troops, i still won easily, and not because i had like more maa (becouse i never invested in anything with Azumen unlike when i played as Bór and had to) the reason i probably won was becouse i had like 4-5 allied armies alongside mine, and even though we might have had smaller number compared to the other side our big amount of knights/champions made up for that.

I continued to play some more on both sides to see how the tedjin cb acted and cheated some to form both sides special formables. I also quickly checked out some of the peaceful options to prevent the civil war.

**Conclusion:**
While just taking a quick look on the peaceful route, I am a big fan on it's existence, for those player that really likes the diplomacy in the game! But i mostly focused on the civil war and this review is mostly focused on that aspect. Overall i very much like the tedjin event driven civil war, especially playing Bór and having a real challenge, it was very fun, it had a great build up and conclusion. With a continuing arc to expand upon with the formables titles and the cb's that helps that along, giving the player something new to work towards at! Great stuff!

**Suggestions:**

* The starting event/narrative for Ayal should have a tool tip for the batal-an-izindi faith in my opinion. 
And while not outright saying it the text suggests in my opinion that Bòr converted outside the realm. And since so much of the southern Tedjin realm (including the capital) is batal-an-izindi and have been for a while? I think it's more logical that the son (Bór) is converted in the home realm rather then away? And that maybe should be clearer in the text if that's the case.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/149684098-7944ca9f-18a6-4968-a1d3-30800ebf7740.png)

</details>

* Getting contribution/troops from neighbors, I very much like this mechanic! it's very flavorful and straightforward, hyping up for the war! as i wrote earlier Sauron is my favorite, the others (on both sides), are very clear for the how & why, "mechanic" wise but it's very bare-bone. If possible i would suggest a little more flavour on the texts, the flesh out the drama in the region and stakes in this civil war.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/149684939-0c31af33-fe51-472e-8c60-29042c9c20b8.png)

![image](https://user-images.githubusercontent.com/79544635/149684949-0d494064-c878-4cd3-b5a8-5a2245424469.png)

</details>

* Civil War Balance; To me Bór is the Hard start and Azumen the easy one, I don't mind this but to balance it some while still having Bór be the hard part, i think that either making sure that Bór have 1000 more troops (like falaya and bellakar giving 500 more each) or taking away 1000 troops from Azumen, this would have Azumen still a lot stronger but not ridiculously so. Also if we could somehow even the champion scale a bit that would be great, they don't need to be even, but maybe the rebel side could have less then 3 to 1 champions/knights in favor of them.

* On a more regional note rather then the civil war or the nation itself, I think the holy sites need to be nerfed. Both sides have 5 (or 3 for cult of Maladûm ) holy sites in a "very" small area. In my opinion _both_ faiths could go down to 4 holy sites & spread out a lot more (unless there are some good lore reasons that say otherwise of course). I think the cult of Maladûm need to spread out the 3 down/near the tedjin, maybe one can actually go up into the actual place where they still worship the faith. Same with the Batân an-Izindi, the top 3 is way to close to each other.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/149684378-478287e8-2d01-48a7-aaed-06bb08cfbb02.png)

![image](https://user-images.githubusercontent.com/79544635/149684397-46c47dd1-bfde-45e1-a39e-181c3ff0152a.png)

</details>

*  Some localization and placements: 
-Should the Bór/Batân an-Izindi formable Tedyathâni really have it's de jure capital in Umbar? when the player and the both religous and cultural stronghold is down in the south (tedjin lands) ?
-the falayan troops they send don't have proper localisations. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/149684579-d7e96bee-8355-449e-be3b-52bd21455037.png)

![image](https://user-images.githubusercontent.com/79544635/149684563-4dafd808-f60c-437b-8e2b-8a922f48b159.png)

</details>

* I'm sure this is a subject to change but the Qadjajar flag looks very... random or numenorean with the white tree and not very tedjin/cult of Maladûm flavoured
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/149684667-14d4aa2c-79c4-4885-a0db-9b06f897cb9b.png)

</details>

* If the intent for the new Tedjin invasions cb as a tool to form the new tedjin formables within the lifetime as Bór and Azumen they work fine now, but if the intent is for the formables to be a long goal, for the decedents of these 2 characters to form then they are way to cheap to use currently in my opinion, I think they could cost 1/3 or 2/3 more of the current price of what they cost.

**Comment by JukeJukestar** [comment]
To add on this:
In both my recent Bellakar and Umbar playthrough I noticed that sending troops to Tedjin works fine, but is very expensive. (300-500 Gold for belakar), leading to me being several years in debt because I did want to support them. Considering your own gain is relatively small as the one interfering, maybe the support cost should be nerfed a bit.

Regarding the civil war balance: It heavily depends on wether you manage to convert a decent chunk of your vassals before the civil war. Its possible to convert all of them (if you get lucky they convert even with negative opinion in exchange for some favors)

**Comment by Remerod** [comment]
> Regarding the civil war balance: It heavily depends on wether you manage to convert a decent chunk of your vassals before the civil war. Its possible to convert all of them (if you get lucky they convert even with negative opinion in exchange for some favors)

you do make a good point. I did a lot but i did not spend much time religiously converting vassals. Perhaps doing more balancing to the army strength would be unnecessary then

**Comment by JukeJukestar** [comment]
It really depends how you want to balance it. For a player its doable but still a challenge, but the AI gets crushed in my games because it doesnt convert as agressively

**Comment by jj248** [comment]
I'm *less* worried about that as our 'canon' outcome is that Bor gets crushed.

**Comment by jj248** [comment]
More tweaks and fixes pushed based on suggestions above.  Closing review.
