### ISSUE TITLE
Sauron swears fealty to Saruman even though they are both Emperors

### ISSUE THREAD

**Issue by ercarp** [MattTheLegoman/RealmsInExile#25]
_Reported by **GasPOGne** on Discord._

> Sauron somehow swore fealty to Saruman, despite already having an Empire tier title.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/78575425/113504530-64b61700-9541-11eb-8c11-da7c4957e3da.png)

</details>

**Comment by jj248** [comment]
Does this not read that Saruman swore fealty to Sauron?

**Comment by jj248** [comment]
Fixed.
