### ISSUE TITLE
Nâfarati custom portrait modifiers and ethnicity

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#251]
I think with some "tools" we already posses we could make the Nâfarati culture group look more unique and flavorful in the Mod.

I do like the mods addition of Nafarati and their culture group. Being inspired/taken from the BFME2 AotR mod and although our ones are a little different it's still a great edition. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150011502-1a941c6a-2a44-4b95-bd48-8c177f534d49.png)

![image](https://user-images.githubusercontent.com/79544635/150011456-97733085-b75c-4f97-99d5-e28b258bffa6.png)

![image](https://user-images.githubusercontent.com/79544635/150011532-0992527f-109c-428d-9704-5ad1401f2a59.png)

</details>

But I think AotR really succeeded in creating a cool outlook(cloths) theme and warpaint's for them. I do also think AotR really succeeded in creating/giving them a thematic looking ethnicity/biological look, as tall, really dark skinned and very white eyed. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150012028-60746dba-3bd0-4111-bea0-591b1ff2fb19.png)

![image](https://user-images.githubusercontent.com/79544635/150012064-805aff05-722a-4dd8-a6b0-316971abcb42.png)

![image](https://user-images.githubusercontent.com/79544635/150012091-3b7cace7-e3dc-48c7-a850-e4044808b931.png)

</details>

So while the cloths and war paint might be great modeling effort away to get into the mod. Their current cloths are not the African cloths right? So maybe we could give it those to differentiate them more? Or maybe we can make it so they all wear the priest/shaman clothing from vanilla? For those resemble AotR ones better perhaps? But it could perhaps be boring to just have one set of cloths for a whole culture. Maybe just giving duchies/kings the feather head piece, which would make Caran-Lambar more similar to his AotR head-piece.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150017640-0eec2168-8c26-4efb-bec2-23136a2574d1.png)
priest/shaman clothing 

</details>

Also they currently don't have their own culture group right? they uses the Fariyîn ethnicity now if i'm right? I think we should change/give them a ethnicity that could be a little taller(if possible),Giving them a lot darker skin (although it's not currently possible in the base ruler designer i know for a fact that you can change the colours, since other mods have green skinned orcs and so on). and change their eyes irises colour to be more white to grayish. to look a little more mysterious as they appear in the AotR mod.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150013991-fdd74423-0511-402f-be25-5a65a0889f82.png)
more White/Grey eyes. (in the mod game).

(In an other Mod)
![image](https://user-images.githubusercontent.com/79544635/150016480-a6fc5cb6-47ec-48eb-923d-a6d2126abbe3.png)

![image](https://user-images.githubusercontent.com/79544635/150016512-0880673e-1c2f-4da2-ab4e-a84836496645.png)
So it's possible to make very dark (or colourful) skinned cultures

</details>

I think by doing these, or some of my suggestions would help making the Nâfarati culture unique and stand out among the other ones, making them and the whole of Far Harad feel more flavourful and diverse!

**Comment by Remerod** [comment]
[Forgetting that we now are in the **Expanded Mods Family** and have access to _Ethnicities & Portraits Expanded_ ]

> So while the cloths and war paint might be great modeling effort away to get into the mod. Their current cloths are not the African cloths right? So maybe we could give it those to differentiate them more? Or maybe we can make it so they all wear the priest/shaman clothing from vanilla? For those resemble AotR ones better perhaps? But it could perhaps be boring to just have one set of cloths for a whole culture. Maybe just giving duchies/kings the feather head piece, which would make Caran-Lambar more similar to his AotR head-piece.

Also these cloths from Ethnicities & Portraits Expanded ( East African Commoner Clothing 1,2,3, East African Low Clothing 1 & East African High Clothing 1) would really also look great for Nâfarati to give them a more similar look to the AotR look (and overall different from the rest of 2.2)

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150021871-b6df68bf-dca1-4e10-b961-ec55b5fa5910.png)
East African Commoner Clothing 1

![image](https://user-images.githubusercontent.com/79544635/150021921-2af1667a-127c-4769-a3bb-4d5f2329b2a8.png)
East African Commoner Clothing 2

![image](https://user-images.githubusercontent.com/79544635/150021966-bcefe378-70dc-432f-8293-c39a39aeb8a5.png)
East African Commoner Clothing 3

![image](https://user-images.githubusercontent.com/79544635/150022006-17d709d1-73a6-4d32-b737-041667bea984.png)
East African Low Clothing 1

![image](https://user-images.githubusercontent.com/79544635/150022058-ccfff462-1309-4059-b0fc-ed0ed63ad890.png)
East African High Clothing 1

</details>

**Comment by jj248** [comment]
We have limited permissions from EPE currently - we need to formalise the rest from their other 3D artists so that limits some of the clothing options noted above - will keep this open for v3.0 though.

Otherwise have given them their own ethnicity:  taller, dark skinned, more shaved heads, headgear can be used for dukes or higher, african clothing, pale eyes.

**Comment by Remerod** [comment]
@jj248  I think the changes made to the Nafarati from what they where prior was a very good step in the right direction! I honestly wish them to be darker, but if that is not possible for now because limitations we have on the character/ethnicity create then that's understandable. And we could close this for now or post pone it to the future?
