### ISSUE TITLE
North Haradrim flavourisation

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#255]
**Intro:**
Having written a small review & posting that on discord around the 19th December, I made a new test/review run tonight a month later :P , to see the new added stuff Haruzan gotten.

**Test:**
My main disappointment in the earlier version was that the cool flavors event at the start was just there, at the start, feeling left out or teased in how to deal with the Chelkar story. That has now been added to the mod! Alongside with a westward expansion narrative and more. The starting narrative for Haruzan is now filled with fun event stuff, with the chellakar, the mouth of harnen, Sauron saying hello every now and then and the Tedjin events! You are given so many options and ways to expand & do diplomacy now as Haruzen and Sûladan, whatever you wanna stay true to "canon" or do your own thing. The current gameplay balance for the region ain't to easy nor to hard, its a very _medium_ level of difficulty, which i think the majority of the people like! It is my opinion that Sûladan/Haruzan now is one of our most fleshed out character/nations, one of the most fun starting position that makes the mod feel alive and also will most likely be one of the most involving characters/nations starts with the 2.2 content that have existed from 2.1 and backwards.

**Suggestions:** 
Having said that Haruzan feels very done and playable. I would like to point out that i belive there is some things that still could be improved for them!

* I have noted this in the past but i'll repeat myself and say that i think the recommanded character screens difficulty description needs to change from Hard to Medium. ;)
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150242818-a66dbd93-6409-472e-a65f-a6a06a86cfaf.png)

</details>

* Many people have nicknames in the mod, like Saurman 'of many colours' or Ellesar 'Envinyatar'. I firmly believe that Sûladan should have have a iconic nickname like Suladân 'the Serpent Lord', or something along like what I saw that on new.notionclub/merp that he had the title 'Kâlakh-Hûl' so maybe that?(does this mean black serpent or just serpent? also the lotro name for Suladan) and/or 'the black serpent'.

* better localization/flavour titles for the Haruze, Harradrim culture group or the Khäs-gramaze faith. Like currently your council priest being called Riksgothi(norse high priest in ck3), this sounds weird to me.  I think at least title names such as baron & loremaster(if nothing else, i think priests and high priests works better) should change. Sheik and Emir is ok-ish, but if there are cooler lotr titles maybe they could be used? maybe takes these names?

> The Haradrim were divided in numberless tribes and clans. In Near Harad the Harûze were ruled by Autarbs or local petty-kings of which the most powerful ones were the Taskrals or Stone-Kings.

Source: the **Political Organisation** tab on https://notionclubarchives.fandom.com/wiki/Haradrim

So maybe **Autarbs** could be the title for dukes and **Taskrals** for Kings? 
And if **Kâlakh-Hû**l means something cool maybe that could be emperor title, for Khäs-gramaze faith? Because apparently there was some prophecy or something about a serpent lord in merp?.

> The Harad Timeline mentions a prophecy about a "Serpent Lord".It is possible that Suladân was this promised ruler, or at last took his role and used the legacy for his rise among the Haradrim tribes.

Source: https://notionclubarchives.fandom.com/wiki/Sulad%C3%A2n_the_Serpent_Lord

Not saying we need to add more religous features but maybe it could justify as a flavour name title?

* If possible I think dressing him in these colours fould fit him better and give him a more haradrim look. 
> Added to this, his dress was highly extravagant, with purple cape and all-red clothes, inlaid with jewels, and serpentine symbols.

 Source: Source: https://notionclubarchives.fandom.com/wiki/Sulad%C3%A2n_the_Serpent_Lord
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150238211-6f648133-a067-427f-ab11-10958372b15f.png)
His current look (As Emperor/High King) is ok but changing the green to more red colours would be cool. The movies often had the harradrim in red, black, brown and blueish colours after all. 

![image](https://user-images.githubusercontent.com/79544635/150240528-41375b7d-a2ec-4351-9ada-dd3e0c7a7556.png)
My son Mûktar, i thought his cloths looked more Suladân :p

![image](https://user-images.githubusercontent.com/79544635/150238511-2f7edb8c-d2c9-4632-996f-f86f39bcb578.png)
Did this with the current assets ingame, it does not look better to me then the current one he has, but it portrays the colour better i think. But most i found (in game while writting this sugestion) was purpleish, so would still be better as more red ones could be find? At least compared to the texts above.

![image](https://user-images.githubusercontent.com/79544635/150239872-eb80c4f8-8042-4655-bb55-ee7db03daf00.png)
Purpleish cape from Ethnicities & Portraits Expanded 

</details>

I know that some cloths have different colours but i dunno how easy/hard it would be to change them? But if not that hard then i think that having them look more Red-like and Purple-like would fit Sûladan, at least better then green. very nicely and having them alongside brown and darker bluish would work well for Haruze overall i think. But i understand that my suggestion ain't the easiest task either.

 When looking around in threw some of the headwear i wanted to point out that a lot of the Sahelian commoner & High Noble headwear would also look great on the Haruze culture i think. The majority of these might've already been added?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150239680-478799b3-0f3c-4c25-9e75-6abd6562b513.png)

![image](https://user-images.githubusercontent.com/79544635/150239704-2e0da13e-57d3-44ba-99af-104a7808370e.png)

![image](https://user-images.githubusercontent.com/79544635/150239747-271c8351-e195-47cd-8d4f-a9614d5e0c26.png)

![image](https://user-images.githubusercontent.com/79544635/150241922-5d8d6e88-200f-4e90-9039-e0c01fe83c0b.png)
I think this one the _Sahelian commoner headwear 4_ looks very harradrim, (and that we already have it in the mod right?) and i think it would be great if it was a lot more common among the harradrim culture group's commoners (with differant colours if those exist).

</details>
 
 **Conclusion:**
 And even if no one of my suggestion is added i think as i said, it no longer feel like just a thrown in area but something with a strong connection to the lotr lore & narrative like Rohan in our mod! I'm very content whit it's current status and i think it's worthy for the 2.2 update.

**Comment by jj248** [comment]
- Changed difficulty to medium
- Given nickname 'the Serpent Lord'
- Clothes changed to red gold and black palettes for Haradrim in general
- @VectorMaximus to pick up title localisation
- @VectorMaximus looking at chaplain localisation currently too.
- Added some more headwraps to Haruze commoners and counts.

**Comment by jj248** [comment]
Vector's bits are done.  Closing.
