### ISSUE TITLE
Haradrim tribal CoA are not used

### ISSUE THREAD

**Issue by MattTheLegoman** [MattTheLegoman/RealmsInExile#257]
`trigger = { government_has_flag = has_tribal_coa }`
This isn't giving the tribal Haradrim their CoA templates, it doesn't seem to work.

Using the trigger `trigger = { has_government = tribal_government }` will crash the game. Same with using `feudal_government`.

**Comment by jj248** [comment]
I've simplified this so that it's controlled purely by which CoA gfx a culture has.
