### ISSUE TITLE
Implementing Beren/Tuor History Exploration

### ISSUE THREAD

**Issue by VectorMaximus** [MattTheLegoman/RealmsInExile#258]
Currently both have localization, but need to have the events coded

**Comment by jj248** [comment]
Can we link the localisation in the discord here? :)

**Comment by jj248** [comment]
https://discord.com/channels/751097183448727552/857542930902417408/923148586752020530

**Comment by BriceLeduc** [comment]
Beren/Túrin are implemented and work fine.
Tuor's code is online but I commented the option out : the event doesn't fire and I can't figure out why

**Comment by BriceLeduc** [comment]
All histories are now working as intended, issue closed from my pov
