### ISSUE TITLE
Sauron is hemorrhaging gold

### ISSUE THREAD

**Issue by ercarp** [MattTheLegoman/RealmsInExile#26]
_Reported by **CavFra** on Discord._

At some point in this person's game, Sauron "went bonkers" and started losing a ton of gold, accumulating a debt of over 15,000 gold. Might be worth investigating why this is happening and if there's anything we could feasibly do about it.

> Not a bug but definitely a blunder to be kept under watch:  This guy at some point went bonkers and started hemorraging cash. I get the feeling like this is more of a CK3 issue, because you do not inherit debt and when you play a ruler that is constantly bombarded with attacks you are bound to go into unhealable debt.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/78575425/113504624-f6be1f80-9541-11eb-819b-7f549b7ec2af.png)

</details>

**Comment by jj248** [comment]
It's probably got a lot to do with the sheer number of MaA these guys field at times too.

**Comment by jj248** [comment]
New tributary mechanic can give Sauron gold.  One to keep on watch when we are balancing Mordor, but not really an active issue to keep track of so closing.
