### ISSUE TITLE
Abrakhan Subjugation: Nafarati empire reward.

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#261]
A while a go we talked on discord that both the making Nafarati tributari and keeping them under your domminion should reward the empire title. To my memory everyone agreed to this and i atleast think a update was assumed to fix this. it is not the case however, Keeping Nafarati under your dominion don'ät give you an empire title. It does however change the de jure Nafarati empire to Abrakhan empire, so it's formable at least. 

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150882053-37c0eed4-e95b-457d-95fb-9fc7cc421d7d.png)

![image](https://user-images.githubusercontent.com/79544635/150882082-b4fd07c3-3fde-458a-a11b-03b437b19b7c.png)

![image](https://user-images.githubusercontent.com/79544635/150882114-776b844a-68ef-4e7c-84d6-d9d73cf08428.png)

</details>

**Comment by MattTheLegoman** [comment]
Player gets a choice now. However, due to a rare potential bug in either my code or tributary code, the "Tributary" choice instead forms a Nafarat kingdom vassal.
