### ISSUE TITLE
Kingdom of Tedja costing 0 gold to form

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#262]
While checking the mission thing for Abrakhan i noticed that the kingdom of tedja costed 0 gold for Arani cultured character holding the Duchy of Kref Tuvvaj. I assume that this is not the intention and that this is a bug. 
![image](https://user-images.githubusercontent.com/79544635/150882634-17107f1b-2275-4dad-83c1-7ac193fb508c.png)

**Comment by jj248** [comment]
This is actually nothing to do with anything we've added, rather an interaction between two vanilla modifiers.  We might consider taking pursuit of power away from the relevant faith, but honestly, I think this is fine - won't fix and closing.
