### ISSUE TITLE
Abrakhan unusable buildings for the Pûstic vassals?

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#263]
I know that the Golden King had problem accessing his buildings, and while that seemed to be resolved the same issue seem to occurring for some of the Golden Kings Pûstic cultured Cult of Zigûr faithful vassals own orcish buildings, that are disabled because they can't use it. I assume this is not the intention? Should they be made so that certain faith's can use em? or (if that's not possible, or a good alternative) make it so that Pûstic also can use those buildings? Or use the same way that fixed the Golden King's issue? 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150885541-07e1ff71-7f51-40ad-b050-c52f9e70755d.png)

![image](https://user-images.githubusercontent.com/79544635/150885578-eb86ffa2-69b7-4ecd-9bc4-0cf4800cee7b.png)

</details>

**Comment by jj248** [comment]
Matt has fixed = closing.
