### ISSUE TITLE
Explore the Histories Re-Balance.

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#264]
So i've taken a look of **Explore the Histories** it's i was aware of existing but not something i had taken a look on ingame. (and while not having taken a look on all of them) I have to say that my first view of it made me feel like it was very-very strong, and given how it cost 200g i can see that? But honestly I think that lowering the cost to 50-150g and re-balance some stuff would be better. While some stuff is a % of getting something, a lot of it is guaranteed. I would like there to always be **20-25%** of getting nothing/failing (and although very rare, there should be a chance for the misfortune to gain nothing by reading it, but again that would be near impossible to get such a scenario). For a numenorean decedent that can live for 200 years being able to use this every 10 years with a bunch of great modifiers feels, as i said very strong if not over powered. 

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/151079167-ee1862a5-ba2e-4da7-8d57-03a15e265f74.png)

![image](https://user-images.githubusercontent.com/79544635/151079297-892bcde2-db19-46c0-b99e-c22b1c47ede1.png)

![image](https://user-images.githubusercontent.com/79544635/151079197-0f1e45ee-a436-41a4-a701-f3bff315433a.png)
These to examples above (from Fëanor and the Disquiet of Noldor) seem balanced to me (although i wouldn't have minded a 75% on the "stress loss".

![image](https://user-images.githubusercontent.com/79544635/151080456-d9241bad-3e74-4321-9446-ab05b397c717.png)

![image](https://user-images.githubusercontent.com/79544635/151080568-0ef4e9a2-6ad3-4efa-a719-c10b6a8a38c9.png)

![image](https://user-images.githubusercontent.com/79544635/151080606-21690b9e-c34e-47a5-b717-4ad31c8da682.png)

![image](https://user-images.githubusercontent.com/79544635/151079717-4ba5e05e-d872-40aa-89fa-539a3d85acbf.png)

![image](https://user-images.githubusercontent.com/79544635/151079773-9e1fa2f3-cf4b-40f2-ba91-e63959436dcd.png)

![image](https://user-images.githubusercontent.com/79544635/151079844-e4fbc2b8-a83b-4afe-9c90-bc18aa872e87.png)

![image](https://user-images.githubusercontent.com/79544635/151079899-03f39c63-2837-4bab-96d7-79371625de10.png)
Most of these examples just straight out gives you great stuff! While others don't. It does not feel balanced to me. 

![image](https://user-images.githubusercontent.com/79544635/151080041-35faff5c-598f-44dc-a274-bf4159a3f4f2.png)

![image](https://user-images.githubusercontent.com/79544635/151080059-6c576c85-118c-4aad-a4b4-5db6e5611c7b.png)
like these 2 T**he Korlean War** both give 150 piety while one of them also give a chance of holy warrior, why ever take the first one?

![image](https://user-images.githubusercontent.com/79544635/151080495-ad8422d2-a85b-4094-b667-2ba9e7912c89.png)

![image](https://user-images.githubusercontent.com/79544635/151080333-e8434492-c38f-411f-8152-d4cd81b8b964.png)
And while i've said that most thing should have % tied to them, i do think by spending resources to gain something (like the 2 examples above) is very fair!

</details>

I think these Decisions are cool! but to expensive and to buffed, lower the cost, make all these stuff more chance based and have some that cost stuff that give you cool traits (like i wanna train as a holy warrior to be like this person, I'll pay "something" to achieve this!). 
I'd heavily recommend that someone writes a **Github wiki page** where some guidelines for the events are lined out, how many events a story can have, the cost and bonuses they give and what kind of percentage all should give. Because i think this is something many people wanna continue doing (because you all are lotr nerds that live to cite poetry). So having a **standard** in order is important (because we're gonna end up with like 50 stories or something, that's a lot to test out for us testers! :P ) 

But please, write (here) if you agree or disagree with me! It is always good to hear many opinions on an issue!

**Comment by RedArkady** [comment]
Some could do with some gentle balancing to increase the number of bonus that are %chances, particularly mine, but I'd keep the rare really good bonus (like giving a trait) and I think the £cost is fine.

**Comment by BriceLeduc** [comment]
I'd say, rule of thumb, stress/prestige/piety gain should be 100% but limited to 50 or 100, 15 for stress. Lifestyle perks and skills should be 50% or 33% chance. For commander trait sure fire is ok, but for rare ones like hunter/blademaster/mariner/poet/herbalist it should be 33% or 25%

**Comment by jj248** [comment]
Another option available on to grant the stronger bonuses you have but to make them time limited by implementing them as a character modifier. e.g. Inspired by X bonus for 5yrs

**Comment by BriceLeduc** [comment]
That would work, but it's a lot more complicated to code :)

**Comment by Remerod** [comment]
On the chance of sounding nagging, I want to point out that I thinks it's very important to write a template on the [GitHub realms in exile Wiki](https://github.com/MattTheLegoman/RealmsInExile/wiki) on how to make these, so a decided numbers are set for the future. because i think these kind of event chains is something that will be continued to be done and it's very easy to forget or spin out the strength of these modifiers rewards. Having a set/recommended template on how to write (like how many events each one should contain) and what those rewards should be on a **Explore the Histories** wiki page will ensure that each history delving choice will give around the same amount of rewards so no one gets picked regularly over the other and as i pointed out that they won't become Op in the future.

**Comment by BriceLeduc** [comment]
I did some re-balancing of Arkady's events this morning, to bring them in line with the other event's bonuses. I'll look into making this wiki page, I've got a pretty clear idea of the general rules to apply

**Comment by BriceLeduc** [comment]
I have gone through the events and standardised the amounts and chances of bonuses.
A tutorial for the writing of future events is now in the wiki
