### ISSUE TITLE
Bridges to Fords 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#266]
Very glad to see we finally got crossings/fords to Khorsâj! 
![image](https://user-images.githubusercontent.com/79544635/151463644-0a108a8a-104f-4c4a-90db-7be17ab28f5b.png)

![image](https://user-images.githubusercontent.com/79544635/151463793-336b85e0-b556-40bf-9a5c-334a4d8ef4dd.png)
But i also want bridges (models) to Khorsâj pretty please.

I think that makes sense after all for the capital to have em (and maybe more areas where it make sense).

**Comment by jj248** [comment]
This should be fixed now - let me know if any look off or if I missed any in testing.

**Comment by Remerod** [comment]
Have tested it out, and while not the army don't always perfectly walk over the bridge, all bridges connect correct to the right baronies the fords are connected to! The main reason bridges are good is to showcase where the fords are, and i think it does so now, so i consider this Issue resolved and will close it ;)
