### ISSUE TITLE
Abrakhan Palace not upgradable for Golden King. 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#267]
![image](https://user-images.githubusercontent.com/79544635/151464464-f10a6a1b-fa89-42f1-b906-d3a6049ce383.png)

The Golden King ain't allowed to upgrade his own Palace.

**Comment by MattTheLegoman** [comment]
I missed an "is the Golden King or equivalent" trigger for the wonders.
Fixed in:
https://github.com/MattTheLegoman/RealmsInExile/commit/1e4ef04b4b3931f451265794452f4eddaf3e071d
