### ISSUE TITLE
Client State still has Sauron as Suzerain after Sauron dies

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#271]
After Sauron is taken out thru the destroy mordor event chain Haruzan is still a client state/tributary of Sauron.

![image](https://user-images.githubusercontent.com/96250463/151715239-9072af6a-5670-48c5-a62d-c594f3f9dcd2.png)

![image](https://user-images.githubusercontent.com/96250463/151715250-172bdf62-90a1-4d7d-a6cd-ef8c90bd188d.png)

**Comment by jj248** [comment]
Ready to test.

**Comment by Remerod** [comment]
the reason Chelakar stay is because they are a client state and not a normal tributary like everyone else, i think this issue can come to a close then!
