### ISSUE TITLE
Titualar Kingdom of Saralain Decision 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#275]
Got people confused on why they had the Titular Kingdom of Saralain Decision as King Madogh, the holder of the Titular Kingdom of Saralain. I believe the intent of this decision to be available only if the title is lost right? Should probably be hidden if someone holds the title already? 

![image](https://user-images.githubusercontent.com/79544635/151719797-d95f1817-ecd5-46bf-bc2c-8d964c532b26.png)

**Comment by VectorMaximus** [comment]
Made a fix so that it cannot be seen by somebody already holding the title
