### ISSUE TITLE
Custom Faith lacking holy sites Bug

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#276]
from bug report: 
>On the topic of custom faiths, my custom Elendili faith lacks any holy sites.

![image](https://user-images.githubusercontent.com/79544635/151720783-7300eee0-be1e-4b4e-bc83-05f9d66b4a00.png)

Seems to be a bug where some custom faiths don't re-create the holy sites

**Comment by jj248** [comment]
Thanks @Remerod - though I'll need steps to reproduce please.

**Comment by Remerod** [comment]
Me and jerman tried to recreate this bug but we're unable to, so i'm closing this one
