### ISSUE TITLE
Dark Ritual: A Success (missing localization) 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#278]
Reported on discord bug-reports, i got confirmation they only have our mod. I have not checked this out myself yet.

![image](https://user-images.githubusercontent.com/79544635/151831122-27162271-3c7e-42a6-8a1b-ec42bf8f6549.png)

**Comment by VectorMaximus** [comment]
Have for now commented out this possibility. It does not appear to have been fully implemented.
