### ISSUE TITLE
Unify the Realms of Harad broken becouse of Abrakhan Empire

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#280]
Discord bug-report input:

![image](https://user-images.githubusercontent.com/79544635/152027653-609465cd-3a14-4c66-a532-62d591d5a1c4.png)

This is true, we should change this:

![image](https://user-images.githubusercontent.com/79544635/152027700-debd333f-a548-43cc-af6e-56c24ec6984c.png)
the **You have the Title Náfarat** to you have should probably be "either **You have the Title Náfarat** or **You have the Title Abrakhan**" instead

**Comment by VectorMaximus** [comment]
Fixed. Closing
