### ISSUE TITLE
Princess Arphazêl is Celibate

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#281]
Discord bug-report:

![image](https://user-images.githubusercontent.com/79544635/152028990-a08eef33-51b4-4d92-a6ff-cc08c6f7cf11.png)

It's the same case for me:
![image](https://user-images.githubusercontent.com/79544635/152029054-8c4db977-0c8c-4296-aafc-13858033a6fd.png)

I very much doubt this is intended, so gonna bug list this

**Comment by VectorMaximus** [comment]
Unsure when this was added, but Burodapan should not have been married to her. Removed the marriage. Closing the issue.
