### ISSUE TITLE
Playable heir for Syâr-Rhul

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#282]
Discord Bug-report:

![image](https://user-images.githubusercontent.com/79544635/152029691-7555dc27-a4b9-443c-b2ff-62b492f25d8f.png)

I don't mind personally that he can't have children.

![image](https://user-images.githubusercontent.com/79544635/152029858-0be18f84-c74c-442d-8656-f986b04b33df.png)

It fits his personality to never have focus on family life, But maybe he could have a Brother that did, so Syâr-Rhul could have a Nephew or Niece that could inherit the title?

**Comment by Remerod** [comment]
We've come to a consensus that he himself should not have children, but he should have an extended family that can inherit his title so the player wont have a gameover, more is in favour that his extended family should be local culture

**Comment by JukeJukestar** [comment]
Added a dead father, dead brother and living cousin to the Black Vizier so he has an heir.
Ready to test. (There may be an issue with their dynasty since they are not assigned one in the files)

**Comment by BouenMarsh** [comment]
![image](https://user-images.githubusercontent.com/104737836/216839072-18a62453-558f-45f3-8f25-f76770aea9a2.png)
Still doesn't have an heir (Dead father and brother do exist, but no cousin.

Their dynastic tree only contains the character himself:
![image](https://user-images.githubusercontent.com/104737836/216839106-cc006be3-2384-4139-8a12-894e1f6358cb.png)

**Comment by jj248** [comment]
He can get married as he can now take over Abrakhan with the departure of the Golden King, so he needs heirs.

We also have him converting to Pustic if he takes over, so the culture issue shouldn't be a problem.

Not sure what the 'lore' issues are re: the nephew.  Otherwise it looks pretty safe to close for me.

**Comment by Remerod** [comment]
but he got an heir? that's why we added the nephew? he is supposed to be a theological dude (which we have very few off) not a prime candidate to play as (which is why we wanted the add the nephew so you could play him and have an heir) does he need to be able to have produce a child to be a able to take over abrakhan?

**Comment by jj248** [comment]
Not necessarily, no.  I don't feel overly strongly about it either way.

**Comment by jj248** [comment]
Made him infertile.  Closing.
