### ISSUE TITLE
Fix Bellakar decisions

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#283]
Integrate Fellaya : we need to add a trigger checking Fellaya is independent, or the decision will still appear if Fellaya has been absorbed, maybe even if Fellaya is another empire's vassal
Intervene in Tedjin civil war : we need to remove the decision once the war is over, or at least if Bor becomes unlanded

**Comment by BriceLeduc** [comment]
I added is_independent trigger to the Fellaya decision, but can't figure out the Tedjin one. It should be disabled if the whole event chain is over. 

Also, both Bór and Azumen should be made Zealous to avoid helping someone who has changed religious sides.

**Comment by jj248** [comment]
Fix committed - ready to test.

- Felaya integration should only be possible for Bellakar if Felaya is independent
- Tedjin support decisions should no longer show if the war has concluded or we're more than 10 years into the game.
- Zealous traits were already added.

**Comment by VectorMaximus** [comment]
Jerman has tested this. Closing
