### ISSUE TITLE
Exclude once-in-a-lifetime clauses for immortals

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#29]
Replace all instances of add_character_flag = { flag = used_lifetime_invasion } with add_character_flag = { flag = used_lifetime_invasion years = 100 } to make a lifetime = 100 years.

Might want to consider changing localisation.

**Comment by JukeJukestar** [comment]
The Vanilla kingdom tier casus belli for prestige and piety respectively are made so you can only use them once in a lifetime. In vanilla this makes sense, but with immortal characters there should instead be an incredibly long cooldown. (~80-100 years maybe)

This way they cant spam it, but characters like Saruman, Sauron, (Aragorn) or the Nazgul can still invade whole kingdoms in a longer playthrough.

**Comment by Remerod** [comment]
started as the golden king, took kingdom of ray with an kingdom invasion cb play a hundred years and i've not gotten the CB back, so i don't think it works 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150700962-85f94469-3450-469a-a467-0d29fdd5a7a3.png)

![image](https://user-images.githubusercontent.com/79544635/150700996-1b0ca4d5-1cec-4cf5-8295-ad5193b61c7d.png)

</details>

**Comment by JukeJukestar** [comment]
Fairly sure theres a tradition that allows infinite kingdom wars now, though Im not sure theres a cooldown so that might have to be fixed

**Comment by jj248** [comment]
Tested - confirmed working.  Closing.
