### ISSUE TITLE
Câssimirioni family member hanging at in Elronds court of Imladris 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#290]
Discord Bug Report:
![image](https://user-images.githubusercontent.com/79544635/152649838-226bb1e7-8bec-4a34-95e1-8a47e47d55aa.png)

I can confirm this, I suspect that something is very wrong. 
![image](https://user-images.githubusercontent.com/79544635/152649848-75321d2c-3495-476b-a4df-3cbd0282140a.png)

**Comment by JukeJukestar** [comment]
That explains a lot! I was wondering why she was Eldar-religion in the recent MP game. now we know!
