### ISSUE TITLE
Several Modifiers relating to Dune Sea terrain are broken or missing

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#296]
**Dune Sea Warfare tradition:**

<details>
<summary> Dune Sea Warfare tradition </summary>

<img width="729" alt="dune" src="https://user-images.githubusercontent.com/76008882/154293642-46175a57-09c3-4744-bf3b-0173c09bf1b2.PNG">

</details>

<details>
<summary> Dune Sea Warfare supply effect </summary>

![image](https://user-images.githubusercontent.com/76008882/154293167-36461d89-c2b5-43d7-b8e6-807be2c1ebcc.png)

</details>

the supply and levy effects are displayed in absolute numbers instead of being a percentage like the modifers for regular desert terrain.

**Desert Warrior commander trait:**

<details>
<summary> Desert Warrior trait and missing combat advantage </summary>

<img width="497" alt="desert warrior" src="https://user-images.githubusercontent.com/76008882/154294885-f06569ca-f73b-425a-aa92-cef6d8042c9c.PNG">

<img width="849" alt="warriorirl" src="https://user-images.githubusercontent.com/76008882/154294911-bc9367ed-196b-40a4-b8cf-ccdc4fe4aa63.PNG">

</details>

The desert warrior trait doesnt apply in the dune sea, since the modifer hasnt been added to it yet.

also, it would be nice for flavor if the scorpion king himself had the desert warrior trait at game start maybe :)

**Comment by jj248** [comment]
Ready to test.

**Comment by VectorMaximus** [comment]
Appears to be all in order - closing.
