### ISSUE TITLE
Suggestion for Rohirrim and Leofring

### ISSUE THREAD

**Issue by zartaxxx** [MattTheLegoman/RealmsInExile#300]
I noticed, that descendants of noble Rohirrim characters don't have horse master trait. Maybe it's better to make a special decision for Rohirrim and Leofring(AI and player) rulers to get Horse Master trait depending on prowess and martial skill? 
That mechanic with decision would also be good for Dunland and their Outrider Leader trait.

**Comment by zartaxxx** [comment]
It would be also good if at the end of military education there is an opportunity to get this trait.

**Comment by Vierwood** [comment]
The current plan is to incorporate the trait's bonuses into a unique tradition for the Rohirric culture.

**Comment by JukeJukestar** [comment]
Rohirrim currently have the "Horse breeders" tradition, if the "Horse Lords" tradition is added as well they will have pretty good cavalry buffs so this trait could be removed

**Comment by jj248** [comment]
Closing this as it's containted in #187
