### ISSUE TITLE
(Nearly) all vanilla regional traditions are avaiable to all cultures in the game

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#305]
(Nearly) all vanilla regional traditions are avaiable to all cultures in the game.

The terrain specific ones ("mountain herding" for example) can stay,
ones like "Visigothic codes" and "Eastern roman legacy" should probably be renamed or removed

"Dune Sea Warfare", "Abrakhani Magic Cities" and similar regional traditions should also be available for reforming cultures that settle in the area.

**Comment by jj248** [comment]
Went through and adapted / purged vanilla regional traditions.  Ready to test.

**Comment by Remerod** [comment]
It is now indeed where trimmed down, i think it's fine for now. These red areas have no regional trations for now though, but i thinks it's fine for the compatibility patch. 

![image](https://user-images.githubusercontent.com/79544635/155423522-93ffa3e8-46ee-4e79-b52f-95aea82bd40b.png)

**Comment by Remerod** [comment]
seems good enough to close for me
