### ISSUE TITLE
Tributary & Alignment Mapmodes

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#308]
the Tributary & Alignment Mapmode currently don't work in the dev version for 2.3

**Comment by jj248** [comment]
The general consensus among other modders that have used similar functionality in the past is that this is something that is trickier now in v1.5 and needs time to figure out, so I'll be reverting the map mode changes and switching back to vanilla mapmode ui.

Will look to reimplement for v3.0 when (hopefully) a community consensus on a fix is figured out.

**Comment by jj248** [comment]
Added these back in, ready to test.

**Comment by JukeJukestar** [comment]
They work well, personally I think the "dominion of the dark" color could be a bit darker - right now the map feels very light despite darkness reigning in a large part of the map

**Comment by jj248** [comment]
![image](https://user-images.githubusercontent.com/26043074/213717911-afc7d7e5-751b-41b6-8c9a-4cac1af62214.png)
Alternative committed - slightly darker.

**Comment by Remerod** [comment]
I think this works fine 

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/219281099-dad187fa-4bfa-4af8-a421-79564b387ee5.png)

</details>

I also think it's fine now, while there are some easier (green) to make the difference and some places harder (red) I overall think the differences are good enouth for not being a problem, if @JukeJukestar also give the thumbs up i think we're ready to go ahead and close this :)

**Comment by JukeJukestar** [comment]
Slap that issue on the ass and close it proper I say!
