### ISSUE TITLE
Great Work Wulfburg missing description

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#310]
the Great Work Wulfburg is missing it's description for all 3 levels (it had them at one point right? :P )

![image](https://user-images.githubusercontent.com/79544635/155122607-cc213853-9e6e-4302-80a9-85077e741672.png)

**Comment by jj248** [comment]
I don't believe it ever has had a description...  Also, definitely not a high priority bug. :)

**Comment by Remerod** [comment]
yeah, agreed

**Comment by VectorMaximus** [comment]
Added description. Closing
