### ISSUE TITLE
No innovations for Sauron's culture 

### ISSUE THREAD

**Issue by Chief305** [MattTheLegoman/RealmsInExile#311]
Sauron's culture has no innovations in the recent update 

![20220222080105_1](https://user-images.githubusercontent.com/99970173/155139730-071705f2-da7c-4aba-b739-35f14c4fe3af.jpg)

**Comment by Remerod** [comment]
Could this be an Issue about him being Úmaiar now and not _Fallen Maia_ ?

**Comment by jj248** [comment]
Fixed - ready to test.

**Comment by Chief305** [comment]
> Fixed - ready to test.

fixed
