### ISSUE TITLE
Bellacar gender succesion.

### ISSUE THREAD

**Issue by zartaxxx** [MattTheLegoman/RealmsInExile#313]
Bellakar Empire has Equal succesion law. Other Bellakar duchies that are vassals of the empire have Male Only law. Main Bellacar religion(Kathasaptha) has Male Orientated doctrine, so it's strange, that the succesion of the empire is Equal, despite these facts.

**Comment by VectorMaximus** [comment]
It's because of a historical situation which resulted in the kingship of Bellakar being made equal succession. Others of the Bellakaze group could make the change because their culture has the 'equal' tradition, but none have implemented such at our start date.

**Comment by VectorMaximus** [comment]
Closing
