### ISSUE TITLE
Trial by combat with saruman

### ISSUE THREAD

**Issue by Chief305** [MattTheLegoman/RealmsInExile#315]
![20220223051303_1](https://user-images.githubusercontent.com/99970173/155311656-f780e3a7-4fd8-4325-9bfd-622b87f7622b.jpg)
 i was doing my test run and this poped up out of nowhere

**Comment by Remerod** [comment]
Saruman shouldn't be able to murder by scheme because he is an fallen Istari, should trial by combat be added to this sphere of restrictions to or not?

**Comment by jj248** [comment]
Closing this as linked to #316
