### ISSUE TITLE
Trial by combat available against Nazgul, Saruman etc

### ISSUE THREAD

**Issue by Jorgeveji11** [MattTheLegoman/RealmsInExile#316]
The witch-king was killed by an orc in a single combat in the 3 year of the game

**Comment by Remerod** [comment]
related to the [Saruman Trial by combat](https://github.com/MattTheLegoman/RealmsInExile/issues/315) should the Nazgul trait protect this as the murder scheme restriction does or no?

**Comment by jj248** [comment]
![image](https://user-images.githubusercontent.com/26043074/155430594-475a5df2-eda4-451f-898e-b7b90933d65e.png)

**Comment by jj248** [comment]
Disabled valar, maiar, undead and nazgul as potential targets for trial by combat interaction.

Ready to test.

**Comment by Remerod** [comment]
I tested this from Faramir's point of view by making certain orcs, haradrim and the nazgul hardened criminals (console commands) i could challenge them by trial of combat but not the nazguls, Sauron nor Saurman. So i think this is fixed!
