### ISSUE TITLE
Boar trophy court bug 

### ISSUE THREAD

**Issue by Chief305** [MattTheLegoman/RealmsInExile#317]
![20220223080457_1](https://user-images.githubusercontent.com/99970173/155327663-89642a27-2457-4a9d-bcca-7af311d0075e.jpg)
the trophy is side ways when it is placed

**Comment by jj248** [comment]
Had a -90 degree direction - have tweaked.  Ready to test.

![image](https://user-images.githubusercontent.com/26043074/155432374-02a62241-c5d5-486b-959c-12ad9a052668.png)

**Comment by Chief305** [comment]
fixed
