### ISSUE TITLE
Uruk Berserker Needs a Loincloth

### ISSUE THREAD

**Issue by Vierwood** [MattTheLegoman/RealmsInExile#318]
When an Uruk gains the Uruk Berserker trait he also gains the confidence to walk in the nude, which looks as terrible as it sounds.

**Comment by JukeJukestar** [comment]
this problem still exists for women, who wear a top but nothing else

**Comment by jj248** [comment]
![image](https://user-images.githubusercontent.com/26043074/200084365-96da559a-bd8f-4836-a6a0-0e9c318fe803.png)

I'm unable to reproduce this issue - I believe I must have fixed it at some point along the way.  Pushing it back to testing to confirm.

**Comment by Remerod** [comment]
does not work

**Comment by jj248** [comment]
To deal with in #559
