### ISSUE TITLE
Rethink Numenorean blood inheritance logic

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#32]
Something that the players have been bringing up repeatedly is the inheritance logic for the Numenorean blood.  It seems you can only inherit the version from whoever is the 'dominant' parent in the marriage (men in patrilineal, women in matrilineal) if there are two different types.

**Comment by VectorMaximus** [comment]
Some players have even been commenting that its only what the father has, even in a matrilineal marriage - we should definitely test it and know for sure before making a call.

**Comment by jj248** [comment]
**Relevant comment from Discord:**

I've done a lot of testing on this already and I don't believe you can
Not sure if it is intentional or not but by setting the traits to 100% inherit chance and not making them genetic you do not put them into the games inheritance system
So you have a 100% chance of inheriting the dominant parents trait every time (I think)
I've just fixed it (I think)
Go into  lotr_traits delete the inherit_chance = 100. I left the both_parent_has_trait_inherit_chance = 100 as it makes no difference
Then add genetic = yes
to each of those traits making them part of the congenital inheritance
Which works off this formula.
I've literally only tested it 2 or 3 times and got promising results

https://ck3.paradoxwikis.com/Family_(relation)#Trait_inheritance

**Comment by jj248** [comment]
Committed WIP.

**Comment by jj248** [comment]
Fully rethought out mechanic.  Removed vanilla congenital trait inheritance and now dealing with it via a hidden on_action birth event.

Event will look at both parents' bloodline traits and will figure out the chance of retaining the higher of the two, with increased chances from being virtuous and lower chances from being wicked.

**Comment by jj248** [comment]
Added penalties for infamous traits like kinslayer and adulterer with greater penalties for more serious crimes.

**Comment by RedArkady** [comment]
This now plays really well. Encourages more effort to improve your heir's traits and marry well (both in terms of general traits and bloodline). Rare mysterious anomalies probably due to infidelity.

Recommend close.

**Comment by jj248** [comment]
Great, thanks - closing.
