### ISSUE TITLE
Artifact Banners cut the flag to early

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#320]
the banners are quite good, but the clip the emblem just a tiny bit to early for it all to be in there, would do a lot to the thematic if it's fixed 

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/155412298-022bc5ff-8240-4066-bed0-5506ac74624b.png)

![image](https://user-images.githubusercontent.com/79544635/155412344-a3df05b1-570e-4e32-9a63-e05be6c2d6a5.png)

![image](https://user-images.githubusercontent.com/79544635/155412383-fe25e0d8-2479-4a1f-824f-209111cf2284.png)

![image](https://user-images.githubusercontent.com/79544635/155412487-27762180-47c2-4915-8daf-6c913647ebc2.png)
Is it just me or does this one change it's colour slightly? 

</details>

**Comment by jj248** [comment]
I *believe* this is due to the green channel in the properties texture fading out too early?  Again, playing at the fringes of my knowledge here but I'll give it a go... 
![image](https://user-images.githubusercontent.com/26043074/155718690-2fd41352-0e77-46ae-b8cc-86d06fba031c.png)

**Comment by jj248** [comment]
That *seems* to have fixed it...  Testers should check for similar issues on other flags though.  Will commit and move to testing.

![image](https://user-images.githubusercontent.com/26043074/155719426-a2a5f90f-58ec-478d-b01b-8e37be8a5164.png)

**Comment by Remerod** [comment]
ok, now with the latest updates. 

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/155762194-8e334d2b-75a3-4acc-8ad8-5caa824820e8.png)

![image](https://user-images.githubusercontent.com/79544635/155762215-489c8226-1f6d-4159-b549-789a16ffcf7e.png)

![image](https://user-images.githubusercontent.com/79544635/155762238-dd8d4d73-adca-443c-83b0-5fa8c6c42c5c.png)
the above flags now cut a tiny bit to late, and the flags have a problem with the right side cutting into a new one. 

![image](https://user-images.githubusercontent.com/79544635/155762291-4eb8ffe8-a4ba-4d71-a359-626c71959cf6.png)

![image](https://user-images.githubusercontent.com/79544635/155762255-5fdd9c03-101f-4b04-b675-a2b964ec6de7.png)
the tringles cut a little to early
</details>

**Comment by Remerod** [comment]
This from the latest update [the EPE Heads and bodies]

and to pint stuff out, it's supposed to be random right of which type of flags people use based on game start, becouse each start makes "everyone, or most" use a certain type flag (the only exception to this rule I've seen is rohan).

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/155858562-6a2441c8-506e-48b7-86db-52444f48294c.png)

![image](https://user-images.githubusercontent.com/79544635/155858756-bfe029a4-38f8-4449-9fae-b19c1fb076e2.png)

![image](https://user-images.githubusercontent.com/79544635/155858589-e30a18a1-7963-42c8-a2ae-0fdf4d267e2a.png)
i think the majority now looks pretty good with these type of flags

![image](https://user-images.githubusercontent.com/79544635/155858614-f8bff9c4-797b-4023-951c-a3b0333f75a4.png)
I still think this flag would better if could see all corners. 

![image](https://user-images.githubusercontent.com/79544635/155858632-6e9abb07-639b-4cd8-878d-d0cb1eabdb5c.png)
this flag type still looks weird for most (But i guess it's okeyish). 

![image](https://user-images.githubusercontent.com/79544635/155858701-94d5efb0-62e4-45b4-a0f7-9c7f3f397ca1.png)
I've actually not seen this type of banner to often, it looks.. weird on this picture. 

![image](https://user-images.githubusercontent.com/79544635/155858719-3bc5c5c6-8016-457d-8670-01a304b1893e.png)
Same here, the upper part is good, but the lower, right & left sides are weird. 

</details>

Based on the other flags, i'm moving this back to Bugs to be judged there on whatever the other types need more adjustment or not.
