### ISSUE TITLE
Artifact Requirements for Nazgul don't work

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#321]
All Nazgul Artifact have this code in the template :

can_equip = {
		culture = { has_cultural_pillar = heritage_undead }
	}

In-game, the "Requirements" tooltip only shows the content of the previous artifact requirement tooltip that has been checked.
I suspect there might be a problem with the heritage

**Comment by jj248** [comment]
This was just a misunderstanding of the code - closing.
