### ISSUE TITLE
Jewelry box wont show 

### ISSUE THREAD

**Issue by Chief305** [MattTheLegoman/RealmsInExile#323]
![20220225091006_1](https://user-images.githubusercontent.com/99970173/155729848-169aceef-382a-4a6c-8c21-ff7bcca31c94.jpg)
jewelry box is invisible when displayed. i tired placing it in different slots and it still would not show. this is the first time i saw this and i will start a new game to see if i can recreate this issue.

**Comment by Chief305** [comment]
![20220225093237_1](https://user-images.githubusercontent.com/99970173/155732890-c4d4efa0-ebf8-4d46-9511-7383f0221c73.jpg) 
 I started a new game and i spawned in a chest and it still will not show when placed in a slot.

**Comment by Chief305** [comment]
![20220225094308_1](https://user-images.githubusercontent.com/99970173/155734977-c2617d37-92ec-40c5-8323-1fdfc337377d.jpg)
i tried the same thing in a vanilla court and the item showed up

**Comment by jj248** [comment]
Was able to get chest to show - might be a legacy issue?

**Comment by RedArkady** [comment]
This may be connected to a wider issue - some adventurer artifacts and possibly inspiration artifacts are not showing. Needs testers to look at various scenarios, especially different courtrooms. Some suggestion that this may be a vanilla issue.

**Comment by Chief305** [comment]
im gonna tinker with this more ill update soon

**Comment by Chief305** [comment]
this issue is fixed
