### ISSUE TITLE
Faith Conversion localisation error.

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#328]
Was reported on the bug-reports that if you convert from Garaudan to Ishtran there is a localization error, i have recreated this on the steam version and can confirm it! 

![image](https://user-images.githubusercontent.com/79544635/156349443-01640efe-86aa-4773-9428-6307c8632dc9.png)

**Comment by jj248** [comment]
@VectorMaximus - Please Fix.

**Comment by VectorMaximus** [comment]
Ready for testing.

**Comment by JukeJukestar** [comment]
Fixed.
