### ISSUE TITLE
Nazgul rebellious rather than subservient to Sauron

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#33]
Numerous accounts of Nazgul seeking to overthrow or plot against Sauron.

**Comment by MattTheLegoman** [comment]
They should have a trait or character modifier that makes them subservient to Sauron. Icon should be a ring.

**Comment by VectorMaximus** [comment]
Vier made a change so that Nazgul/Maiar lieges will not be targeted by AI factions. I believe this can now be closed, unless Matt wants us to finish it off with that character trait symbolizing their subservience.

**Comment by RedArkady** [comment]
I think this is fixed, I haven't see a Nazgul rebel in a while.

**Comment by jj248** [comment]
Great - matches anecdotes of others.  Closing.
