### ISSUE TITLE
Bug tradition won't allow you to castrate people 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#331]
Undesconocido in bug-report mentioned that they can't "There we go... only Realms on the list, Anbalukkhori but I cannot blind my own arrested child 😭 " So i checked it out in the steam version, and indeed it seems to be the case.

![image](https://user-images.githubusercontent.com/79544635/156853007-6462d5cf-e65e-4832-b9e1-8d00793e9422.png)

The tradition clearly says that you should be able to castrate and blind your prisoners, but you as a Anbalukkhori can not.

**Comment by jj248** [comment]
This looks to have been fixed... closing. 

![image](https://user-images.githubusercontent.com/26043074/193810355-06de40fc-5fab-4546-a672-6128b52d193f.png)
