### ISSUE TITLE
Half-Naked Duel 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#335]
So held a **Hold Court** in Kôanoz and got into a duel, can't remember the event, but i'm pretty sure it did not say anything about the challenge being half-naked 

![image](https://user-images.githubusercontent.com/79544635/157782555-011c6573-b9dc-45d2-bd16-64715d1f0297.png)

**Comment by jj248** [comment]
Hard to really reproduce.  Might need more details...
