### ISSUE TITLE
Ai Dynasty COA change after a custom one is made 

### ISSUE THREAD

**Issue by Chief305** [MattTheLegoman/RealmsInExile#336]
I was tinkering around with the my coa and i noticed that some of the ai's coa change after i finished mines I've repeated this three times here are some screenshots.

This is the character i was using 
<details>
<summary>Click to expand</summary>

![20220311131502_1](https://user-images.githubusercontent.com/99970173/157927809-389a090a-1fe1-4efb-a61e-d2d71e295cf5.jpg)

</details>

this is sauron's coa after i changed mines 
<details>
<summary>Click to expand</summary>

![20220311131518_1](https://user-images.githubusercontent.com/99970173/157928144-3adbaa45-b819-4cfd-b480-726866796bc5.jpg)

</details>

Thats denethor
<details>
<summary>Click to expand</summary>

![20220311131455_1](https://user-images.githubusercontent.com/99970173/157928793-a617be18-9bde-4591-bf32-5cc10c4a354f.jpg)

</details>

theoden
<details>
<summary>Click to expand</summary>

![20220311131516_1](https://user-images.githubusercontent.com/99970173/157929224-a4dcfb13-cdb2-4bf4-a889-3b379843b0c1.jpg)

</details>

a random generated ai 
<details>
<summary>Click to expand</summary>

![20220311131506_1](https://user-images.githubusercontent.com/99970173/157929464-37cee8c2-fc42-49fe-8dee-0a3dff961c02.jpg)

</details>

**Comment by Remerod** [comment]
Cheif33 tried this on the master, dunno if it is an issue for the 2.3 content

**Comment by Chief305** [comment]
its's not an issue for 2.3

**Comment by Chief305** [comment]
So i just tested the steam version of the mod and this issue is still a thing.

**Comment by Remerod** [comment]
I think we concluded that it is a paradox thing and not on our end, but i am not entirely sure.

**Comment by Chief305** [comment]
it is im gonna show some vanilla screenshots

**Comment by Chief305** [comment]
this is before i changed it 
<details>
<summary>Click to expand</summary>

![20220321220439_1](https://user-images.githubusercontent.com/99970173/159393035-f7ae39a6-b636-44f4-aac2-8a5232b14a3c.jpg)


</details>

this is after but it dosent change the other ai rulers on vanilla anymore from wat i seen 
<details>
<summary>Click to expand</summary>

![20220321220606_1](https://user-images.githubusercontent.com/99970173/159393893-18f2b206-d703-4f5a-8edf-5c9c915e4140.jpg)


</details>

<details>
<summary>Click to expand</summary>

![20220321220728_1](https://user-images.githubusercontent.com/99970173/159393999-a517dcd1-cefb-4bfa-a12d-3eef26472105.jpg)


</details>

**Comment by Remerod** [comment]
yeah, paradox will probably give us an other update soon

**Comment by Chief305** [comment]
yea hopefully this shit is annoying lol

**Comment by Chief305** [comment]
this is fixed
