### ISSUE TITLE
Diversify the Orcs of Mordor

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#340]
The Orcs/Uruks of mordor have been needing more deserve **culture texts** and **traditions** for a while now. Will work on this after i've done some stuff in Gundabad & others, feel free to write suggestions here though!

**Comment by MattTheLegoman** [comment]
Please check the Orc culture code for notes on each Uruk tribe.

**Comment by Remerod** [comment]
jepp, got aware of them when i coded in the Gundabad orcs in, will double check on them when i start working on it

**Comment by jj248** [comment]
Looks like we've diversified the traditions of the various orc tribes.  I'm just going to change their colours a little so they render a border and count this as done.

**Comment by JukeJukestar** [comment]
Orc traditions seem to be in  a solid state.
I added two more of the unlanded cultures to mordor and tweaked the setup a bit so the nurniags have more counties after their rework.
Cant comment on the skintones, they all seem to use the same one

**Comment by Remerod** [comment]
could people stop closing my issues that i have assigned myself into without asking me

**Comment by jj248** [comment]
> could people stop closing my issues that i have assigned myself into without asking me

But the scope of this issue has been met, no?  We added cultural descriptions to orc cultures and diversified their traditions, both of which have been reviewed both specifically by Juke above, and also as part of the wider culture review in #557.  What do we have left here that requires it to be kept open @Remerod ?

**Comment by Remerod** [comment]
well i had some stuff that i was still working on, and while i could have pushed those thing to the future on disregard them, the issue is still that i was assign to this issue and it was closed without my opinion on it

**Comment by jj248** [comment]
What are you working on?

**Comment by Remerod** [comment]
I'm not activing working on it and would most likely continue working on it later for 4.0, won't make it to 3.0 at least
