### ISSUE TITLE
Characters in History to Old

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#341]
There are some Characters in the history of a dynasty or house that were to old
IDs

An-Ostozâl Dynasty Chars that are to old: 4432, 3971.

Etulôhîn Dynasty Chars that are to old: 3043,

Nîthôr Dynasty Chars that are to old: 4132

Sîyan Dynasty Chars that are to old: 2929 ,2613, 1662

Isalok Dynasty Chars that are to old: 2122,

**Comment by Foadar** [comment]
I will take care of this tonight.

**Comment by Foadar** [comment]
> There are some Characters in the history of a dynasty or house that were to old IDs
> 
> An-Ostozâl Dynasty Chars that are to old: 4432, 3971.
> 
> Etulôhîn Dynasty Chars that are to old: 3043,
> 
> Nîthôr Dynasty Chars that are to old: 4132
> 
> Sîyan Dynasty Chars that are to old: 2929 ,2613, 1662
> 
> Isalok Dynasty Chars that are to old: 2122,

All of this barring the Siyan dynasty have been fixed. There's just no wiggle room in that one. Recommending a reroll with Jamie's character generator.

**Comment by jj248** [comment]
Seems fine now - closing.
