### ISSUE TITLE
Text improvements for Sailing

### ISSUE THREAD

**Issue by josejuanmartinez** [MattTheLegoman/RealmsInExile#342]
For @RedArkady:

Here is a new bunch of texts for the new sailing activities. I'm not a native speaker nor a good storyteller. So please, feel free to make any change you consider, even fully revamping them. My only request is to keep the same number of texts and the plot so that I don't need to change the code (I still want to add a lot of stuff to sailing).

<details>
<summary>[Coastal] The Gulf of Lune, the White Hills and the White Towers [DONE]</summary>

> sailing.5000.t:0 "The Gulf of Lune"
> sailing.5000.desc:0 "Several days ago, you entered the Gulf of Lune, heading to the White Hills. On the left, you can see Elven ships leaving the Grey Havens, most of them to never return. On your right you see the White Hills. "No, we are not seeing the Elves this time" - you try to explain to your crew. We are looking for something else, an ancient artifact..."
> sailing.5000.a:0 "Dock the ship!"
> 
> sailing.5001.t:0 "The White Hills"
> sailing.5001.desc:0 "You dock the ship and proceed to explore the White Hills with some of your crewmates. A few days after, you encounter a small elvish garrison guarding the path. You see Elves coming from the East and others leaving to the West. But you focus on a small group of guards who are not going anywhere and seem to be guarding the path ahead"
> sailing.5001.a:0 "Ask the Elves to grant you permission to proceed your journey"
> sailing.5001.a.success:0 "The elves grant you permission to go on"
> sailing.5001.toast.a.success:0 "Permission granted!"
> sailing.5001.a.failure:0 "The Elves don't allow you to go further"
> sailing.5001.toast.a.failure:0 "Permission denied!" 
> sailing.5001.b:0 "Try to sneak through"
> sailing.5001.b.success:0 "You continue your path indetected by the Elves"
> sailing.5001.toast.b.success:0 "You avoided the Elven garrison"
> sailing.5001.b.failure:0 "The Elves detect you while trying to sneak"
> sailing.5001.toast.b.failure:0 "You have been detected!" 
> 
> sailing.5002.t:0 "Watching the sea from the top"
> sailing.5002.desc:0 "What? Watching the see from above the hills? What kind of joke is this? Are you a hobbit?"... Alright, go ahead! But don't touch anything, we will be viligant."
> sailing.5002.a:0 "Farewell"
> 
> sailing.5003.t:0 "The way is shut!"
> sailing.5003.desc:0 ""The Towers hold a sacred artefact. This place is protected by the Noldo and we can not let you go. Turn back." - says the Elf"
> sailing.5003.a:0 "There may be another way..."
> 
> sailing.5004.t:0 "Elvish not-so-sharp eyes"
> sailing.5004.desc:0 "Elves have sharp eyes - but somehow you managed to remain unseen and avoid the Elvish watch."
> sailing.5004.a:0 "(sneak your way in)"
> 
> sailing.5005.t:0 "Elvish sharp eyes"
> sailing.5005.desc:0 "Elves have sharp eyes. "You think you can fool us? Go away, last warning!" - says the Elf"
> 
> 
> sailing.5006.t:0 "The White Towers"
> sailing.5006.desc:0 "You discover in front of you the majectic view of the White Towers, with the highest of them in the middle - the Tower of Elostirion. You reveal to your crew the true purpose of your journey - you seek for an arfifact of the ancient times, a Palantir, kept in the Tower of Elostirion. You enter the main White Tower and, in the main central room, you see a crystal ball covered with a dark cloth. It calls you, it wants to be used..."
> sailing.5006.a:0 "[first_mate.GetFirstNameNoTooltip] - Captain, to the top of the Tower!"
> sailing.5006.toast.a.success:0 "You feel relieved!"
> sailing.5006.b:0 "I should stay here and glance into the Palantir"
> sailing.5006.toast.b.success:0 "You glanced into the Palantir!"
> 
> sailing.5007.t:0 "The Sea from Above"
> sailing.5007.desc:0 "You take your time to meditate on the top of the tower of Elostirion. You lost count of the time you spent watching the Gulf of Lune and how Elven ship leave the Grey Havens. You feel relieved and restored from all the mundane problems, and longing to come back home soon"
> 
> sailing.5008.t:0 "The Palantir of Elostirion"
> sailing.5008.desc:0 "You find the Palantir of Elostirion and don't hesitate to use it. You feel your mind abandons your body to travel to far away lands. You acquire great knowledge of Tol Eressea, The Master Palantir, the Sea of Aman. However, soon your mind starts to get troubled with foul visions of old wars that torture your soul. You manage to make a step away from the Palantir, promising yourself not to use it again."

</details>
<details>
<summary>[Coastal] Ras Morthil and Druwaith Laur</summary>

> sailing.6001.t:0 "Ras Morthil"
> sailing.6001.desc:0 "You reach the Cape of Ras Morthil, that separates the Bay of Belfalas from the Sea of Belegaer. When you were prepared to turn right to the lands of Eriador, [first_mate.GetFirstNameNoTooltip] approaches. - "Commander, we have spotted a former Gondorian Fort with a Beacon on the top of Rash Morthil, that seems to signal all over Andrast. It seems to have been abandoned for a while now. What should we do?""
> sailing.6001.a:0 "Climb to the top of the tower and look around"
> sailing.6001.toast.a.success:0 "You observe Andrast from above"
> sailing.6001.b:0 "Light the beacon!"
> sailing.6001.b.success:0 "You bring alarm to these lands firing the beacon"
> sailing.6001.toast.b.success:0 "Ras Morthil Beacon lighted!"
> sailing.6001.b.failure:0 "The beacon is not functional anymore"
> sailing.6001.toast.b.failure:0 "Ras Morthil is ruined!" 
> sailing.6001.c:0 "Destroy the beacon!"
> sailing.6001.toast.c.success:0 "You destroy the beacon"
> 
> sailing.6002.t:0 "The Beacons of Gondor"
> sailing.6002.desc:0 "You enjoy a majestic view of the Bay of Belfalas and Anfalas, on one side, and Druwaith Laur and the Belegaer Sea on the other. You don't feel anything remarkable from this place, but the mere fact of standing at the most eastern point of the Cape of Ras Morthil looking to the surrounding lands South Gondor from above, makes you feel mighty."
> sailing.6002.a:0 "Time to move on"
> 
> sailing.6003.t:0 "Fear me, Andrast!"
> sailing.6003.desc:0 "You light the former Gondorian beacon of Ras Morthil. Soon, the signal will be sean from the surrounding beacons, and the alarm will raise in Andrast. You have made a bold statement - these lands will be yours some day."
> sailing.6003.a:0 "Stop the delusion and continue sailing"
> 
> sailing.6004.t:0 "The Ruins of Gondor"
> sailing.6004.desc:0 "This place is just a shadow of its former glory. The beacon is not functional anymore, probably is has been neglected for years, as if no one cared about these lands. There is no point in wasting time here, let's do business somewhere else."
> sailing.6004.a:0 "Leave the ruins"
> 
> sailing.6005.t:0 "Beacon destroyed!"
> sailing.6005.desc:0 "I guess now no signal from or to Gondor will reach this place. Andrast has been isolated from the signaling beacons. Soon the Dunlendings may be raiding this place and it will take years until Gondor knows. Let's leave this place to its fate"
> sailing.6005.a:0 "... muah-ha-ha (evil laugh)..."
> 
> sailing.6006.t:0 "Druwaith Laur"
> sailing.6006.desc:0 "You've left behind the Cape of Andrast and turn right into the shores of Eriador. Lands became wilder here, with places of dark wood and abrupt cliffs. You see the White Mountains and what seems to be the delta of the Isen far away. But something attracks your attention from the top of a hill near the shore. A bunch of dwarven-alike figures stand still. From your ship you can't distinguish what those humanoid figures are."
> sailing.6006.a:0 "Examinate the strange place"
> sailing.6006.a.success:0 "You figure out what this place is"
> sailing.6006.toast.a.success:0 "Stones successfully examinated!"
> sailing.6006.a.failure:0 "It's a bunch of rocks"
> sailing.6006.toast.a.failure:0 "Stones ignored" 
> sailing.6006.b:0 "Look for signs of civilization"
> sailing.6006.b.success:0 "Wait... what's this?"
> sailing.6006.toast.b.success:0 "Caves found!"
> sailing.6006.b.failure:0 "Another bunck of rocks..."
> sailing.6006.toast.b.failure:0 "No signs of civilization found!" 
> 
> sailing.6007.t:0 "These are Druedain stones!"
> sailing.6007.desc:0 "You know what exactly this places is! You have heard in ancient tales that a group of humanoid creatues, similar to Dwarves, were expelled from their home lands by the Numenorean. They say some of them found shelter in the forests, other digged caves in remote places of the White Montains. There are several evidences of their past existence in form of stones, as the ones in the Old Pukel Land. These stones seem very similar to those..."
> sailing.6007.a:0 "Do the Druedain still dwell in the White Mountains?"
> 
> sailing.6008.t:0 "Humanoid-alike rocks"
> sailing.6008.desc:0 "It's just rocks! That would explain why they didn't move. Were these once people turned into stones by some sourcery? Or are these rocks just a result of human craft? Why are they so similar to dwarves? And what are these runes carved in the rocks? This all may have an explanation, but clearly it is not known to you."
> sailing.6008.a:0 "Is there someone around who could explain this?"
> 
> sailing.6009.t:0 "The track to the mountain"
> sailing.6009.desc:0 "After exploring the area, looking for the creators of this figures of stone, you spot a caves going deep into the White Mountains. It may be just a bear den, or a spider one. But your guts tell you there may be something dwelling in the mountains, maybe the legend is true..."
> sailing.6009.a:0 "Explore the cave"
> 
> sailing.6010.t:0 "There is no one around"
> sailing.6010.desc:0 "Someone or something put those stones there, but it was probably long time ago and that civilization must be gone by now... Now, this is more silent than an orc graveyard"
> sailing.6010.a:0 "Time to come back home..."
> 
> sailing.6011.t:0 "Woses!"
> sailing.6011.desc:0 "As you approach the cave, you spot more and more cracks in the mountain. This is clearly not a bear den, it's a whole dwelling! One of your crewmates stumbles over a stone and falls, emitting a loud noise. At first, you don't notice anything. After some seconds, you get surrounding by a group of short humanoid criatures wearing loincloths, pointing directly to you with their spears. Beware of this land, stranger! You are not welcome here!"
> sailing.6011.a:0 "How do they dare? Attack!"
> sailing.6011.a.success:0 "You defeat the Woses"
> sailing.6011.toast.a.success:0 "Group of Woses defeated!"
> sailing.6011.a.failure:0 "You are defeated by the Woses"
> sailing.6011.toast.a.failure:0 "You are poisoned!"
> sailing.6011.b:0 "Retreat!"
> sailing.6011.b.success:0 "You successfully run away from the Woses"
> sailing.6011.toast.b.success:0 "Retreat!"
> sailing.6011.b.failure:0 "You are injured in your retreat"
> sailing.6011.toast.b.failure:0 "You have been slightly poisoned!"
> sailing.6011.c:0 "Let me do the talking..."
> sailing.6011.c.success:0 "You convince the Woses you mean no harm"
> sailing.6011.toast.c.success:0 "Woses levied!"
> sailing.6011.c.failure:0 "The Woses don't trust you"
> sailing.6011.toast.c.failure:0 "Leave us, you bring trouble..."
> 
> sailing.6012.t:0 "You draw back the Woses to their caves!"
> sailing.6012.desc:0 "You overrun the small group of warriors. The rest, run away deep back into the mountains. You don't see any track of them, and you don't feel like entering the caves with a small crew of sailors is a good idea. You feel yourself satisfied with being a survivor in this wild place, and will remember this experience for the rest of your life."
> sailing.6012.a:0 "Heil to the champion of Druwaith Laur!"
> 
> sailing.6013.t:0 "You were overrun by the Woses"
> sailing.6013.desc:0 "As you decide it's not a good idea to confront these warriors, you give the order to your crew to run for their lives. In your way back to your ship, the Woses start firing at you with their wood arrows. You successfully sneak most of your way, but when you were close to reach the ship, you feel an arrow impacting on your left calf. You pull it out and continue running, but you feel weak and you fall down to the ground. Everything before you gets blurry, you only can distinguish the figure of [beachcomber.GetFirstNameNoTooltip] dragging you back to the ship."
> sailing.6013.a:0 "Rest and recover from the poison"
> 
> sailing.6014.t:0 "You successfully retreat"
> sailing.6014.desc:0 "You only see a group of warriors, but there might be more of them hidden in the caves. You decide to run back to your ship. Fortunately, they Woses seem very peaceful, and had not intention at all in chasing you back. They stand from afar watching you run back to your ship, and then they fade in the shadows of their caves, not to be seen anymore."
> sailing.6014.a:0 "Come back home for medicine"
> 
> sailing.6015.t:0 "A clumsy retreat"
> sailing.6015.desc:0 "You only see a group of warriors, but there might be more of them hidden in the caves. You decide to run back to your ship. Unfortunately, the Woses start to chase you, and one of them fires an arrow that impacts directly on your right foot. The wound is not very deep, and you manage to pull the arrow out. However, the wound leaves you a weak and feble, as if it was imbued with some toxic sustance..."
> sailing.6015.a:0 "I will call it a day..."
> 
> sailing.6016.t:0 "Woses convinced!"
> sailing.6016.desc:0 "The Woses don't see any danger on you. Their chief comes close to you and seems willing to start a conversation. He asks you for news from the world. You feel they have been isolated for many years now, as they don't seem to be aware of the tidings of Middle Earth. You deliver a very inspiring speech about the War in the East, that lights the fire in the eyes of the Woses. After they mumble something in their mother tongue, they decide not to hide anymore and to fight by your side."
> sailing.6016.a:0 "There is place for you on my ship"
> 
> sailing.6017.t:0 "You scared the Woses!"
> sailing.6017.desc:0 "Their chief comes close to you and seems willing to start a conversation. He asks you for news from the world. You feel they have been isolated for many years now, as they don't seem to be aware of the tidings of Middle Earth. However, as you start describing the War in the East, you bring memories of old times of war and dispare. After mumbling something in their mother longue, the Woses thank you for your information and go back to their dwellings in the mountain.""
> sailing.6017.a:0 "Why am I so explicit sometimes?"

</details>
<details>
<summary>[River] Anduin River: Ethir Anduin, Pelargir, Osgiliath, Cair Andros, Wetwang, Falls of Rauros [DONE]</summary>

> sailing.8001.t:0 "Mouths of Anduin"
> sailing.8001.tt:0 "Let's navigate the Anduin River!"
> sailing.8001.desc:0 "Our ship has reached the Anduin Delta, also known as Ethir Anduin. Here, the Great River ends its course to finally flow into the Bay of Belfalas. This place has witnessed many naval battles between the Gondorian Fleet and the Corsairs Dark Ships. But it has also symbolized during peaceful times the prosperous naval trading system between Gondor and other coastal nations. The Delta is quiet now, disturbed only by the activityof Fishermen and Sea-crafty folk. Not far from the Delta, on the Lebennin side of the Anduin River, you see a small fishing settlement, where probably these boats sell their goods."
> sailing.8001.a:0 "Plunder the boats! Raid the settlement!"
> sailing.8001.a.success:0 "You successfully raid the fishermen"
> sailing.8001.a.failure:0 "You are forced to retreat"
> sailing.8001.toast.a.success:0 "You successfully raided the settlement!"
> sailing.8001.toast.a.failure:0 "Retreat!"
> sailing.8001.b:0 "Bribe the fishermen"
> sailing.8001.toast.b.success:0 "You bribed the fishermen!"
> sailing.8001.c:0 "Ask about rumours about far away lands"
> sailing.8001.c.success:0 "The fishermen share with you the latest news from travelers crossing the Anduin"
> sailing.8001.c.failure:0 "The fishermen won't share any piece of news with strangers"
> sailing.8001.toast.c.success:0 "Intrigue improved!"
> sailing.8001.toast.c.failure:0 "Unable to know any recent rumours"
> sailing.8001.d:0 "Continue sailing"
> 
> sailing.8002.t:0 "Raiding the fishermen"
> sailing.8002.desc:0 "The fishermen raise their rudimentary tools to offer resistance, but soon the settlement is set on fire by your crew and most of the boats start to sink. You proceed to plunder the settlement to then return to the ship with the bounty."
> sailing.8002.a:0 "Is that a giant catfish?"
> 
> sailing.8003.t:0 "Where did you come from?"
> sailing.8003.desc:0 "As your ship approaches the settlement, the Fishermen sound a tower bell. Men and women gather at the harbor with all the kind of wooden and metal tools, decided to protect their goods and their homeland. You realise you probably are not the first raider trying to plunder these lands. They are well organize and have only one objective - to drive back any pirate from the Anduin River. Unfortunately, they gather much more people than you counted on in the beginning, and you are forced to retreat and continue your course along the Anduin"
> sailing.8003.a:0 "At least I stole a catfish for dinner"
> 
> 
> sailing.8004.t:0 "An army of fishermen"
> sailing.8004.desc:0 "The fishermen ring the bell on the main tower of the settlement and a reunion starts. You are not allowed to assist, but when the conversation heats up, you manage to catch part of the discussion - "These lands are not safe any more. I can see more and more strangers gathering at the other side of the river. Black ships navigate the Delta again. We need the money to build a fort, proper weapons, or we won't stand a war. We must agree!" - The assistants loudly agree."
> sailing.8004.a:0 "My homeland is after the second turn on the right"
> 
> 
> sailing.8005.t:0 "Royal Dockyard of Pelargir"
> sailing.8005.desc:0 "[first_mate.GetFirstNameNoTooltip] approaches - "Captain, we are getting closer to the City of Pelargir. Have you seen that?" Using your spyglass you manage to see a majestic dockyard, one of the most impressive you have ever seen. You can see many gigant docked ships. "Those should be the famous Gondorian Ship-kings..." you say out loud. Beyond the dockyard, you discover the view of a vibrant trading city."
> sailing.8005.a:0 "Let's wait until the night and burn the Ship-kings"
> sailing.8005.a.success:0 "You manage to start a fire in the shipyard and come back unseen"
> sailing.8005.a.failure:0 "The borders in Pelargir are well guarded. You suffer several losses and are forced to abandon the city"
> sailing.8005.toast.a.success:0 "Pelargir dockyars sabotaged!"
> sailing.8005.toast.a.failure:0 "Retreat!"
> sailing.8005.b:0 "Let's make some coin!"
> sailing.8005.b.success:0 "Pelargir traders are willing to start a trade route to your kingdom"
> sailing.8005.b.failure:0 "Pelargir traders are not willing to trade with you"
> sailing.8005.toast.b.success:0 "Trade route established!"
> sailing.8005.toast.b.failure:0 "Unable to impress Pelargir merchants"
> sailing.8005.c:0 "That Ship-King is now mine."
> sailing.8005.c.success:0 "You manage to steal the Ship-King"
> sailing.8005.c.failure:0 "Your steal attempt is discovered"
> sailing.8005.toast.c.success:0 "You have stolen a Ship-King!"
> sailing.8005.toast.c.failure:0 "You have been discovered while stealing!"
> sailing.8005.d:0 "Upgrade my boat to a Ship-King"
> 
> sailing.8006.t:0 "Stealing at night"
> sailing.8006.desc:0 "Your men wait until the sunset and prepare for sneaking into the dockyard at night. As the naval activity ceases, and taking advantage of the darkness and the fog, you take a boat from your ship and reach the dockyard. While [first_mate.GetFirstNameNoTooltip] makes some noise outside the yard to distract the guards, you are able to sneak in the ship and release the anchor. You meet your crew back on your new ship"
> sailing.8006.a:0 "Come on, crew of the Royal Ship!"
> 
> sailing.8007.t:0 "Shame on you!"
> sailing.8007.desc:0 "Your men wait until the sunset and prepare for sneaking into the dockyard at night. As the naval activity ceases, and taking advantage of the darkness and the fog, you take a boat from your ship and reach the dockyard. While [first_mate.GetFirstNameNoTooltip] makes some noise outside the yard to distract the guards. Unfortunately, the guards bump into you while you where trying to sneak in the ship. One of them hits you and takes you down to the floor. You are escorted back to you ship, where you will heal your wounds and recover the prestige lost..."
> sailing.8007.a:0 "It was [first_mate.GetFirstNameNoTooltip]'s fault"
> 
> 
> sailing.8008.t:0 "Osgiliath, the Citadel of Stars"
> sailing.8008.desc:0 "Your crew announces that before the dawn we will have reached Osgiliath. The city seems to have been abandoned for a while now, as a result of the constant struggles between the forces or Mordor and Gondor. The city seems partially in ruins - the Great Hall, the Great Bridge, and even the Dome of Stars. You can wait to the sunset to explore the city."
> sailing.8008.a:0 "Raid both sides of the city, look for any valuable items!"
> sailing.8008.a.success:0 "Raid successful!"
> sailing.8008.a.failure:0 "You come back empty-handed"
> sailing.8008.toast.a.success:0 "Osgiliath plundered!"
> sailing.8008.toast.a.failure:0 "Unable to find anything valuable"
> sailing.8008.b:0 "I need to find the Dome of the Stars!"
> sailing.8008.b.success:0 "You find the Dome of Stars"
> sailing.8008.toast.b.success:0 "Dome of the Stars found!"
> sailing.8008.b.failure:0 "You don't find traces of the Dome of the Stars"
> sailing.8008.toast.b.failure:0 "No signs of the Dome of the Stars"
> 
> sailing.8009.t:0 "Trinkets left behind"
> sailing.8009.desc:0 "Your crew comes back to the ship with a trunk and someone's belongings. They seem to have been left behind during one of the recent attacks to the city. When you open the trunk, you find the riches of some Gondorian lord, including gold coins, jewellery and some trinkets, that are definitely worth some coins."
> sailing.8009.a:0 "Sell these items"
> 
> sailing.8010.t:0 "Ruins and devastation"
> sailing.8010.desc:0 "Your crew returns empty-handed. - "There is only ruins and devastation, Commander. The city has been plundered, nothing was left behind". Suddenly, you hear steps approaching ... "We must go, now!""
> sailing.8010.a:0 "Let's leave before we are detected!"
> 
> sailing.8011.t:0 "The Dome of Stars"
> sailing.8011.desc:0 "[first_mate.GetFirstNameNoTooltip], this is it! Or at least it remains! The Dome of the Stars, where the Palantir of Osgiliath was kept! I can't believe we lived to see this place. The Palantir was lost time ago lost, they say during one of the attacks to Castamir the Usurper. They say it rolled all the way down to the Bay of Belfalas. But maybe is still in the Anduin."
> 
> sailing.8012.t:0 "Were these rocks a tower?"
> sailing.8012.desc:0 "The Great Bridge, all along with the place where the Dome of Stars standed, is now just a bunch of rocks. You can only imagine the former glory of this place, but now you find no trace trace of the tower where the Palantir was kept."
> 
> sailing.8013.t:0 "Cair Andros"
> sailing.8013.desc:0 "[first_mate.GetFirstNameNoTooltip] approaches in the middle of the night and says - "Commander, there are chains in the river that prevent us to move on. We have been forced to stop, and now a boat of the nearby garrison of Cairn Andros has approached. The Commander says the pass to the upper Anduin is shut". What should we do?"
> sailing.8013.a:0 "Let me do the talking..."
> sailing.8013.a.success:0 "The guards grant you passage"
> sailing.8013.toast.a.success:0 "You earned a free passage through Cair Andros"
> sailing.8013.a.failure:0 "The guards force you to turn back"
> sailing.8013.toast.a.failure:0 "You are scouted out of Cair Andros"
> sailing.8013.b:0 "There is no time to talk, and we are not going back. ATTACK!"
> sailing.8013.b.success:0 "You take down the small garrison"
> sailing.8013.toast.b.success:0 "You successfully lift the chains on the river"
> sailing.8013.b.failure:0 "Your crew is overrun!"
> sailing.8013.toast.b.failure:0 "Defeat!"
> sailing.8013.c:0 "Time to come back home"
> 
> sailing.8014.t:0 "You earn the trust of the guards"
> sailing.8014.desc:0 "Your diplomatic skills grant you a free passage throught these lands. The guards don't see in your any threat to them or to the security of these lands. - "You can continue your course up the Anduin, until the falls of Cair Andros. After that point, you should be forced to come back or abandon the ship there and continue on foot. Be careful at the marshes near the Entwash."
> sailing.8014.a:0 "Let's head for the Wetwang!"
> 
> sailing.8015.t:0 "End of the journey"
> sailing.8015.desc:0 "You see chains blocking the way up the Anduin. The guards gather to deliberate whether they should lift up the chains and let you go, or force you to go back. After some minutes of deliberation, the Chief Commander of Cair Andros approaches. - "There is a war going on. We don't know if you are friend or foe, there is no way we can let you through. Go back where you belong.""
> sailing.8015.a:0 "Damn!"
> 
> sailing.8016.t:0 "You can't stop me"
> sailing.8016.desc:0 "Fortunately, the garrison consisted of just a few remaining men from the war. The rest were already dead or fighting for their lifes in other fronts. You easily overrun their defenses and lift the chains to continue your journey. There is no other signs of resistance in Cair Andros."
> 
> sailing.8017.t:0 "Go back to where you belong!"
> sailing.8017.desc:0 "Unfortunately, the garrison was heavily protected. On the first signal of fight, guards from both Gondor and Ithilien sides of the Anduin river come out of their hidden places to join the Commander of Cair Andros to bring you down. You suffer several injuries, but at least the ship remains undamaged to turn back and go home."
> 
> 
> sailing.8018.t:0 "Wetwang"
> sailing.8018.desc:0 "[first_mate.GetFirstNameNoTooltip] - "Commander, Do you smell that? The foul smell, the flies... They  come from upstream. I can see a river flowing into the Anduin on the left. That should be the Entwash. We should be approaching the WetWang. I don't like this place, we should leave it as soon as possible. Who know what danger may be awaiting for us in those marshes...""
> sailing.8018.a:0 "Let's explore this lovely place"
> sailing.8018.a.success:0 "This place is full of treasures of the fallen..."
> sailing.8018.toast.a.success:0 "Artifact found in the Marshes!"
> sailing.8018.a.failure:0 "This is not a marsh, this is a graveyard"
> sailing.8018.toast.a.failure:0 "You return totally frightened to the ship"
> 
> sailing.8019.t:0 "A treasure among the lights"
> sailing.8019.desc:0 "You dock the ship on the shore and decide to explore the Marshes. The Wetwang is just the extension of an even more dreadful place, the Dead Marshes, the place were the ancient Battle of Dagorlad took place. Walking becomes more and more difficult, as you partially step of ponds and water basins whose depth is unknown from the surface. The sun starts to set, while you see lights in the water, in form of candles. You get hyptonized by these dancing candles and lose control over body and find. Sudenly, you find yourself falling into the water, swiming across incorrupted corpses. You hear a voice from the surface calling your name, but something grabs you and takes you deeper and deeperIt was [first_mate.GetFirstNameNoTooltip] calling your name. Fortunately, [first_mate.GetSheHe] gets you to the surface at time. In your way out, you manage to grab an artifact from a fallen warrior"
> sailing.8019.a:0 "Ok, I'm done with this place"
> 
> sailing.8020.t:0 "Stay away from the lights"
> sailing.8020.desc:0 "You dock the ship on the shore and decide to explore the Marshes. The Wetwang is just the extension of an even more dreadful place, the Dead Marshes, the place were the ancient Battle of Dagorlad took place. Walking becomes more and more difficult, as you partially step of ponds and water basins whose depth is unknown from the surface. The sun starts to set, while you see lights in the water, in form of candles. You get hyptonized by these dancing candles and lose control over body and find. Sudenly, you find yourself falling into the water, swiming across incorrupted corpses. You hear a voice from the surface calling your name, but something grabs you and takes you deeper and deeperIt was [first_mate.GetFirstNameNoTooltip] calling your name. Fortunately, [first_mate.GetSheHe] gets you to the surface at time."
> 
> sailing.8021.t:0 "The Falls of Rauros"
> sailing.8021.desc:0 "[first_mate.GetFirstNameNoTooltip] - "Captain, these are the Falls of Rauros, end of the journey." You can see the Anduin River above the falls, and the Gate of Kings - the figures of two Gondorian Kings and a stair allowing go up on foot. You ask your crew to stay in the ship, while you take your time to go up and contemplate the Argonath. Images from old times come to your mind - Isildur, Anarion, the glory of the former Realm of Gondor. They both look north, to the Wold and the Vale. There are many places still to explore, but next time without a ship."
> sailing.8021.toast.a.success:0 "You feel more powerful now"

</details>
<details>
<summary>[River] The Harnen River: The Harnen Delta, The Harad Crossroads at Amrûn, a Variag Camp [DONE]</summary>

> sailing.8101.t:0 "The Harnen Delta"
> sailing.8101.tt:0 "Let's explore the Harnen!"
> sailing.8101.desc:0 "After many days sailing along the Bay of Belfalas, you reach the delta of the Harnen River. As you approached this land of Pirates, you have been trying to sneak and remain unseen. You have only came across a few merchant ships, so your way here was smooth...so far. As you approach the Delta, you see a Black Ship approaching at high speed. You should prepare for the worse"
> sailing.8101.a:0 "Prepare the defenses!"
> sailing.8101.toast.a.success:0 "Your crew defeates the Black Ship!"
> sailing.8101.toast.a.failure:0 "Your crew resists the Black Ship but your ship gets damaged"
> sailing.8101.b:0 "Prepare the defenses (ship damaged)!"
> sailing.8101.toast.b.success:0 "Your crew defeates the Black Ship!"
> sailing.8101.toast.b.failure:0 "You suffer a shipwreck!"
> sailing.8101.c:0 "Prepare a naval maneuvre!"
> sailing.8101.toast.c.success:0 "Your navigation skills allow you to avoid the attack!"
> sailing.8101.toast.c.failure:0 "Naval maneuvre failed!"
> sailing.8101.d:0 "Cancel the plan. This is too dangerous..."
> 
> sailing.8102.t:0 "The Harad Crossroads at Amrûn"
> sailing.8102.desc:0 "Your journey becomes much easier as you leave the Harnen Delta and the pirates behind. On your journey across the Harnen, you find different Haruzan forts and small trading posts on both sides of the river. But as you approach the Amrûn, you discover a very peculiar place. Here, the Harnen river splits into two effluents, one going North to Ephel Duath and the Kingdom of Chelkar, the other flowing onwards into Pezarsan. This fact, and the presence of a tall bridge allowing the crossing over the effluents of the River, make this point a natural meeting point from travellers from around the world."
> sailing.8102.a:0 "Sabotage the bridge!"
> sailing.8102.toast.a.success:0 "Bridge sabotaged!"
> sailing.8102.b:0 "Talk to the travellers on the Harad Road"
> sailing.8102.b.success:0 "You get to know the latest news about this far-away lands"
> sailing.8102.toast.b.success:0 "Intrigue improved!"
> sailing.8102.b.failure:0 "You don't find any friendly face in this place"
> sailing.8102.toast.b.failure:0 "No one to talk to"
> sailing.8102.c:0 "Find a scribe to teach me Northern Apysaic"
> 
> sailing.8103.t:0 "The Scribe"
> sailing.8103.desc:0 "You find the tent of an old Haruzan man, selling manuscripts, scrolls, and books about the history of the Middle Earth. He sees you come from a place far away and calls you in your mother tongue. When he attracted your attention, he asks where are you from, and starts speaking almost perfectly your mother tongue. He tells you his story - he has been historian and a scribe, and spent all his life registering the events on Middle Earth. He has been to many places in Middle Earth, where he learnt the languages and the cultures of their people."
> sailing.8103.a:0 "Can you teach me Northern Apysaic?"
> sailing.8103.toast.a.success:0 "You learn Northern Apysaic!"
> 
> sailing.8104.t:0 "An Variag Tradepost"
> sailing.8104.desc:0 "You decide to turn left on the Crossroad of Amrûn, heading north to Ephel Dual, to then turn right into the Kingdom of Chelkar. You feel the temperature raises as you progress on the course of the Harnen. The little vegetation you could find in Haruzan now is almost inexistent. A dreadful view to Ephel Duath, the Mountains of Shadow opens up in front of you. Fortunately, as you approach the mountaints, the river starts to take a turn right into the lands of Chelkar. After some days of sailing, your crew starts to despair, given the rugged and remote nature of these lands and the little supplies left. When you were considering turning back, you see a vibrant tradepost upstream. You decide to dock your ship to find the supplies you require and take a look at the activity of this big Variag Tradepost"
> sailing.8104.a:0 "Look for weapons or armour"
> sailing.8104.toast.a.success:0 "You find people biding for weaponry"
> sailing.8104.b:0 "I want to visit the Luxury Items post"
> sailing.8104.toast.b.success:0 "You visit the Luxury and Delicacies spot"
> 
> sailing.8105.t:0 "A tiny little something"
> sailing.8105.desc:0 "You are attracted by the activity in a very popular tent. As you come close, you realize the crowd is participating in a strange auction - you are shown an item covered in fabric, and you can only bid for what you guess the item is. You arrived at the end of the action, and everything has been sold except one very last item. It seems to you a piece of armour, but you can't distinguish what it is exactly. The assisstants of the auction decide not to bid for it, that gives you the opportunity to acquire this secret item for a modest fee."
> sailing.8105.a:0 "Place a bid on that item"
> sailing.8105.toast.a.success:0 "Artifact acquired!"
> 
> sailing.8106.t:0 "Caravans from Khand"
> sailing.8106.desc:0 "The last spot you find in the Tradepost has many local delicacies (dates, figs, nuts, tea, spices...) and several luxury items (silk, ivory, wool...). "Stranger, come closer! You are not from these lands, aren't you? Let's make a deal. We have plenty of supplies - you have a big ship. Nobody would forgive you coming back empty-handed! For a reasonable price, all my stock is yours.""
> sailing.8106.a:0 "Bring a cargo of Luxury items home"
> sailing.8106.toast.a.success:0 "Luxuries from Khand purchased!"

</details>

**Comment by Remerod** [comment]
remember to move this to testing when all code is done and localization is in ;)

**Comment by josejuanmartinez** [comment]
Yeah we are 75% done with the revamp, in short it will be finished and I'll move it to testing.
