### ISSUE TITLE
Game concepts for Rhovanion

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#344]
I am starting to add game concepts for Rhovanion. I will make the entries for the canon parts (Lorien, Greenwood, Dol Guldur, Lakerown, Dale). Feel free to add some for the newly added Mannish realms.

The game concept files is the encyclopedia, that allows the insert tooltips in events and descriptions.

**Comment by jj248** [comment]
Dealing with these in a Discord forum thread now given it's a constantly evolving list of requests.  Closing.
