### ISSUE TITLE
Meme Suggestion

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#345]
This is Kinda a meme suggestion but perhaps somewhere in the brownlands there could be a county ruled by a ingame version of Rémerod and in his court have all the testers.:))

**Comment by Remerod** [comment]
If i'm gonna be anywhere it be in forodwaith :P

**Comment by Jermanlordy** [comment]
or better idea, could do Remerod as a count in forodwaith me as a count in arnor juke as a rando orc count etc.

**Comment by JukeJukestar** [comment]
Thought about this before, would be very fun!
Perhaps we could be courtiers in Valinor instead so we dont interfere with the game ; )
Would be fun if all the devs got characters there too similar to the vanilla ck3 dev team chilling in scandinavia at game start
We should LotR-ify our names though.

Jûk of Hammerburg would be honored to be the first Uruk in Valinor (he is very nice for an orc)

**Comment by Remerod** [comment]
Dev already do have characters in, that is what they call their "vanity" characters.
