### ISSUE TITLE
Vineland Guard attire 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#347]
Trying to get the Vineland Guard attire into the mod for an armour that the Dorwinrim can use. 

here is the schematic design? 

![image](https://user-images.githubusercontent.com/79544635/159390034-3b68abc5-c139-4e49-8094-ea0cb045fb5e.png)

**Comment by Remerod** [comment]
Some progress, but more to do.

![image](https://user-images.githubusercontent.com/79544635/159390299-e224f312-fe1c-44e0-9d57-05ac90633d44.png)

The reason "I assume" it look this way is because it's missing it's properties.dds texture file (which i don't even understand what that is) so will try figure out a way to solve this, help wanted.

**Comment by jj248** [comment]
I like the armour, I still really dislike the helm.  It looks so much like a gimp mask... 👯

**Comment by jj248** [comment]
Wrapping into #559
