### ISSUE TITLE
MaA for Woodmen and Valemen

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#348]
Looking into adding some Specialist longbowmen MaA that would be lore-friendly for both Woodmen and Valemen, neither of which need many other unique MAA according to RedArkady

**Comment by JukeJukestar** [comment]
I could also see special pikemen as an option,would fit the woodsmen nicely as they like putting spikes around their settlements

**Comment by RedArkady** [comment]
Ipsanets has added:
-Vale Spearmen
-Woodmen Axemen
-Woodmen Hunters

**Comment by JukeJukestar** [comment]
The MAA show up for the correct cultures, are solidly balanced and have fitting terrain effects. Closing the issue for now.
