### ISSUE TITLE
Rhûn Name List

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#349]
Currently working on a List of Names for Rhûn. While not the easiest task, since they are one of the most illusive languages in the setting. I do have found some good stuff for them. But if anyone have any suggestions feel free to post here.

**Comment by Vierwood** [comment]
No

**Comment by Vierwood** [comment]
Don't mind that. Fat fingers on a phone.

https://namenookdotcom.wordpress.com/category/world-names/sumerian-names/

https://www.behindthename.com/names/usage/sumerian-mythology

Here are some Sumerian names.

**Comment by Vierwood** [comment]
Needs as many circumflexes as possible, obviously.

**Comment by Vierwood** [comment]
Ancient Persian names

http://www.avesta.org/znames.htm#op

**Comment by jj248** [comment]
Can always take the approach that we used with Adunaic, Gwathiurim and Apysaic families too (i.e. compile a name list, make it consistent, use this as a proto language ancestor, apply systematic sound shifts to generate name lists for different cultures in the same family).

**Comment by Remerod** [comment]
First Draft:

So according to MERP the main language on the rhûnic people seem to steem from [Ulgathig](https://notionclubarchives.fandom.com/wiki/Ulgathig) and derived into Igathig, Sagathing, Lothrag & [Logathig](https://notionclubarchives.fandom.com/wiki/Logathig).
> The Ulgathic languages, made up the the ICE Authors, were spoken mainly in Central Middle-Earth and are loosely based on Turk vocabulary. 

So based on that they've used Turkic vocabelary i've used some of their rules when placing names later.

Taken from [Bozorganush](https://notionclubarchives.fandom.com/wiki/Bozorganush)
> The Bozorgana language was sometimes called Rhûnic by outsiders. It was in fact a late descendant of Igathig with a strong Westron and Rhovanian element in it as well as loan-words from Khandian and Haradaic. 

Rhûnic seem to be based on the Ulgathig-core language group with elements of westron and rhovinian.
So i suggest that either Rhunic should be the language group that includes Ulgathig or one that is derived from it. 

https://sites.google.com/site/aboutharadrimandeasterlings/the-easterlings-and-haradrim-s-mutual-language
site tells me that Easterling have more in common with dwarvish then elvish. 

So some nordse/gothic elements into rhûn? a turkic-norse/gothic hybraztion? with hints of Adûnaic

according to https://en.wikipedia.org/wiki/Turkish_name, many names are female, male and unisex. 

https://www.fantasynamegenerators.com/lotr-easterling-names.php
List of Rhûn names

https://namesfrog.com/lotr-easterling-names/
very good source, helps with bending the names also. 

https://www.wattpad.com/stories/easterlings
The Sands of Rhûn, fanfic. but maybe a good source of some names.

canon list of names: Khamúl, Brodda, Lorgan, Ulfang, Uldor, Ulfast, Ulwarth, Bór, Borlach, Borlad and Borthand

So based on the first 3 list of easterling names i found on the web i put together this list. But as Vierwood pointed out earlier, it could possible do with some more circumflexes.  Just wanted everybody's thoughts on these. And of course some could be shuffled around the sexes.

(info: basically stuff that end with "z" is male. Oğ/"ok(h)" means "arrow" and is also very "maasculine")
Male: Kirun Yinez Arkiz Verkiz Kerkez Mîgkiz Kogez Mogan Arkaz Aruz Razan Unaz Nigkuz Vilkiz Zaguz Kinuz Gugkaz Zinu Zîru Menu Matu Digku Yizun Vugun Ilun Yîlun Urken Tugken Megken Tugken Milkul Atul Urul Yareg Mîreg Yogkug Zînug

(info: from what i can see stuff that ends with e is more feminine, might be wrong)
Female: Murale Nirkeke Agkake Yirege Tagkele Gogke Zure Rîtike Varene Igule Rulkine Rîlege Nîrkeke Ogkile Oluke Zîlkune Yiteke Yelune Ruzane Aruke Uzule Yorege Durike Îgkige Kogkele Mituke Gazale Rîteke Kilike Nilene Agke Tezake Ureke Kuzele Ilkine Erkuke Rutige Igane Zînine Denike Gîgkage Nizene Kanage Manane Înege Gonike Yîlkuke Kogane Tirkule Kalage Zigkeke Karkake Ganune Gozike Utile Mirkine Îlkale Nîtene Kozeke Vigez Mitele Kilkule Ilkege Rîteke Kilike Nilene Agke Tezake Ureke Kuzele Ganake Ulkige Urkale Zînine Layala

(Apparently there is a lot of Unisex names in the turkic languages. and since the [Igath](https://notionclubarchives.fandom.com/wiki/Igath) having more prominent women "their women fought just as did their men" i thought it be neat to have some unisex names for the Rhûnic languages)
Unisex: Kutan Gutan Dilan Dîgkun Dalan Ugan Îlin Îzin Nîlin Nolin Nazin Mulkin Zagin Yînig Erki Kîgki Mugki Nuri Tigi Vîni Gurki Runi Dîte Vizag Yugkag Nîrag Tura Îla Ula Kula Gulig Gîril Zugil Donil Rukil Talkil Utel Igel Rîrken Khanar

**Comment by VectorMaximus** [comment]
You've done some good work on this Remerod.

My basic thoughts at this stage.

There are two broad Easterling tongues - Ulgathig, and Ioradya (of the Igath and Ioriags respectively, with Varadia, the language of Khand, being a derivative of Ioradya). One could use the list you've put together, and the other could use a list more based in Old Persian and Semitic languages, if we wanted them to see more delineated. Alternatively, could use one list for both, to show how they've mixed and mingled.

**Comment by Remerod** [comment]
Lol, my work/research might have ben in vain seeming how there is a MERP nonotionarchive list of [MERP names](https://notionclubarchives.fandom.com/wiki/Names) for [Near Rhûn Easterlings](https://notionclubarchives.fandom.com/wiki/Names#Near_Easterling_Names_.28Balchoth.2CRh.C3.BBn_Easterlings.2CWainriders.2C_Ironfists.2C_Blacklocks.29)

**Males:**
<details>
<summary>Click to expand</summary>

Aara Aasan Adajo Adek Akonîd Alaup Aluap Aluenda Alûpa Amdûr Amnac Amôv Ara Aran Aren Ari Aris Arpa Arpov Art Artri Ash Aski Atakûl Atilik Avas Avos Ayric Aztaur Baisheuin Balam Balan Bana Barakat Barsa Bascam Bassan Baudana Begli Bisc Biscovic Bleda Blyga Bohlman Bom Bragha Breja Brem Brojasht Bruad Brûdhan Bruka Brun Brûst Búlin Bura Calinz Carfe C'ha Chosam Chosum Cileto Coeshay Côl Conúl Dame Dár Darath Darric Dasakûn D'Breh Deniroik Derrim Derrud D'Mallo Dolg Drâg Draik Drek Drexle Durac Dûran Durban Dûrthin Edgu Esgathig Estaban Estus Etha Ethacali Evit Fain Falen Fef Figilu Filgo Fruhar Fuqkazam Fuqkatam Gaffnin Gardagd Garny Gartog Gendo Gerdo Gergeli Gizikh Gontram Gontran Gorka Gorku Gorovod Gov Gozef Gozev Grada Gradu Grallon Gras Grasti Grasty Grell Grena Grilic Grimling Grof Grólin Gulla Gurin Guton Halla Hanaen Harf Harfar Harkmar Harv Harizän Haurl Hesnef Hesnev Hestan Hilic Hoamurath Hodya Hossadam Huil Hurdriak Hurm Hûst Hûz Ida Ikûs Ilsnef Ioghul Iorga Iuganoth Ivêk Jalor Jardan Jatar Jax Jellek Jey Jissom Jukath Jyka Kalcuna Kalporin Kam Karamar Kargi Karghiz Katrisel Karyn K'aun Kav Kay Kemik Kerit Khanli Khârsh Khôrni Khûrthan Kilic Klalg Korl Koumiss Krulla Kub Kull Kur Kustig Kuzu Leärdinoth Leôrdinoth Lís Lisgarin Lothrax Maalon Mahlic Maijesk Makôv Makow Malforr Mara Maraz Margoz Marig Meonid Michl Mîonid Mira M'loy Mohrig Nabin Natak Navrati Nara Natak Nedilli Neffar Nevido Obad Ôgdei Ôgedei Oldur Onree Onri Orad Oran Orash Orbul Ormid Orvid Oyan Pad Paji Paku Palman Palol Parnelion Pebro Polig Portik Pôs P'trich Pultar Rekka Relin Reluka Rên Rhukar Rov Rolm Ross'a Rôzi Rûdaz Rult Ryykaar Sadun Samêl Sarkan Selnoi Sen Sey Shabun Shagelda Shârk Shakal Sharikan Sharzig Sheynk Sherkôz Shorab Shorob Shug Shurn Skauril Skog Skulif Slabu Slovas Slubu Smod Sorr Striuk'ir Suralic Súrk Susymog Suvac Svelm Syr Taichu Talfar Talin Tam Tanhuz Tarlo Tetnak Thredin Threlin Thuric Torak Treyan Tigkîz Tiglin Tôsti Tumna Turga Turgarin Tyga Tyoh Udra Ugus Ukaag Ukog Ulam Ulapic Uldul Ulgin Ulor Ulrag Ulruth Ulthang Ûonid Urai Urdrath Urga Urig Urunshar Utra Vacroz Val Varchaz Vargloth Varig Vellser Velsya 

</details>

**Females:**
<details>
<summary>Click to expand</summary>

Adasha Aivavi Akoi Allit Amal Amûrat Ancanli Aradre Arditi Aril Astrith Ayitula Ayni Baigu Bais Bári Barw Basri Blymiras Borgu Braga Bregg Bregu Bril Brogi Bruam Brue Brusfa Calinli Carrin Chinta Cila Cilis Cilze Closk Coefa Crym Cüce Daer Dáma Damah Damya Darva Dejyk Dhanli Dinu Diravin Dirkal Doli Dregani Dûmra Dûoerris Durcat Durde Durna Ecuris Edian Elyen Emûrath Eona Erennis Esgân Estâris Estûra Êvikel Ethâphel Evîge Evit Faigi Falri Fefdia Fen Ferrin Figilin Filan Fiolla Frella Fruli Fûril Fyen Gafâla Gardâlia Garlana Gârnesa Ge Gênina Gêrlai Gergênas Giziva Gontrarin Gordlin Gorêke Gôrode Govli Gozym Grahaba Gralea Grasphel Grel Grelgu Grenina Grîlaesa Grimist Grisha Grofani Grulian Gûlepse Gulshi Haddil Háin Halli Harila Harmir Haurva Henva Hesnian Hilisha Hillia Hinrel Hisala Hôampa Hôdis Hodya Hossagi Huikel Hujai Hureke Husis Huyai Hûzula Ialdida Iamukha Iarde Iasala Iataris Idag Ieppa Iyislan Ikuli Ilaesa Ilset Ilsil Ioghali Iorris Irista Iugampa Iula Irfelien Iveya Jan Jasala Jeshan Kadida Kaidia Kalkuya Kalpôni Kamhali Kangu Karârag Kargi Kari Kaunis Kavelian Kelai Kemudur Kêrira Khôreke Khûruphel Kililak Klalshi Konirhaba Kôrli Kôumai Krina Krulnas Kubris Kufina Kulgi Kursufa Kusko Leärgi Lahira Lhân Lisri Lisgagani Lito Lôthraphel Mâliya Mahlrin Mareke Mariya Marja'Pur Makôli Makôslan Malfoli Marari Mararân Magochil Mayenva Meôgi Meriya Merkampa Michiril Mionil Mikel Mir Mirag Mirali Mogshi M'raj Morinas Nabirin Nas Nataris Nedilfa Neffalin Neviri Nicoli Ôbalan Ôgdâni Oldirin Ônaris Ôranil Ôrbila Orlteh Ormêris Orvani Ôygu Padilin Pakúsko Palmirde Parnaësha Pebrelis Pode Polgu Pôrtona Poskel Princat Pultinas Raesha Rêkirde Relde Rêlist Remlis Renril Rhugen Reya Rhona Rovla Rugi Sahali Saranda Saym Selachil Serrin Serris Set Shagelda Shagu Shagym Skakaym Shân Shanva Shardani Shargi Shen Sheylis Shergani Shiril Shorala Shugin Shuko Shurdani Silens Sinuphel Skaumia Skôgit Skulëa Skabil Slôvian Sluko Smey Smôdil Sorsufa Stea Striûrin Sudúr Suraris Susufa Susyko Sûvali Sûvalian Svelgi Syrin Taigin Tako Talagani Talfanas Taliset Tamaphel Tamhûge Tarlaris Tetnëa Thîst Thredâni Thuriko Tôranas Treyni Tikgaris Tigulrin Tôstegi Trichin Tumgi Turgaël Tuva Tyragin Tyohli T'ze Ucaphel Udni Ulaphel Undaphel Urdrarde Urgani Urilis Urunya Utnëa Vachrode Valêke Valla Varchani Varglian Varide W'ricke Yelta Yirfelian Y'rage 

</details>

**Comment by josejuanmartinez** [comment]
I used to play Middle Earth Play by Email with Rhun, here are some names, not many though (about 10)
https://wiki.mepbm.com/2950/rhun-easterlings
https://wiki.mepbm.com/1650/easterlings

**Comment by Remerod** [comment]
we went ahead and just used the merp names so closing this
