### ISSUE TITLE
Anduin Vale & Greenwood Valemen/Woodmen work

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#352]
**Done**
12 new dynasties/tribes
- Character histories
- DNA for Beorn & Grimbeorn
- Title histories
- Dynasties
- Mottos
- COAs
- COA templates
- Standard buildings added across key baronies
- Artifact (Skull of Bolg)
- MAA
- Buildings and clothing
-Two new cultures 
-New woodmen faith 
- New starting Event for Beornings
-New ‘Aladegan’ de jure empire Decision
-Three new special buildings
-County development levels

**To do**
Consider unique tenets for Woodmen faith?
Consider separate Beorning religion (seen as righteous by other woodmen faith and vice versa) 
Skinchanger Decision & events - WIP
Encyclopaedia - tribes, geography
Consider making Aladegan elective?

**Comment by Remerod** [comment]
pasting that https://github.com/MattTheLegoman/RealmsInExile/issues/348 issue to this issue
