### ISSUE TITLE
Is the relatively high domain limit desirable?

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#36]
Caused by being relatively far through the tech tree on game start.

**Comment by MattTheLegoman** [comment]
The innovation tier should not equal the "Age of Middle-earth". That way, Gondor doesn't need to be in the renaissance/Third Age, where really they should be lower in the CK3 system and tie their advanced technology to appropriate cultural innovations.

**Comment by jj248** [comment]
Closing and merging with #52 .
