### ISSUE TITLE
Bug: Saruman has no Palantir minor decision

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#361]
As the title says, after using the initial palantir major decision, no minor decision becomes avaiable for saruman.

Denethors palantir works though (although the decision is always a major decision for him, seems like it should be streamlined)

**Comment by Remerod** [comment]
I don't think this a _bug_ but rather _undeveloped_ content, so am tagging this with **suggestion** rather then **bug**
