### ISSUE TITLE
Elven RNG courtier culling

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#368]
Once Mandos is implemented we need to find a way to cull randomly generated courtiers (such as the ones created in activities/lifestyle events).

"Disappeared without a trace" cause of death should maybe be left in

**Comment by jj248** [comment]
Is this still an issue @BriceLeduc ?  The gui is set up so any 'dead' elves show as being in the Halls of Mandos now.  Looking to close.

**Comment by BriceLeduc** [comment]
No that was back when we wanted to move the dead Elves to Mandos' court. No longer relevant
