### ISSUE TITLE
Holy orders vanishing, leaving provinces locked and rulerless

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#37]
**From the Discord:**
Holy orders can sometimes "vanish". They continue existing under the rule of absolutely nobody, and the land they own goes to you, but you cannot lease it or grant it to a Mayor, this results in the piece of land being stun locked until the order leaves it willingly (which doesn't happen.) Also you can't revoke the lease on the order. This happened for an order of a faith I reformed, while the order I had patronage of before converting continued their lease properly. they vanished as well at some point but I don't know under which circumstances.  To add, the holy order still pesters me about me granting them land. If I accept I send yet another domain into the void...

![](https://cdn.discordapp.com/attachments/778645689089392730/828058269385490452/unknown.png)

**Comment by jj248** [comment]
To deal with in v2.2.

**Comment by jj248** [comment]
Was an issue with *all* titles being given primogeniture.  I've moved this now so that only Feudal, Clan and Tribal get primo.

**Comment by JukeJukestar** [comment]
As of 2.2 (14th of January 2022) I have only seen this once, with a castle barony at the black gate. Belonged to a Lidless eye holy order, the holy order didnt disband on saurons death but the barony was irrecoverable

**Comment by jj248** [comment]
Please can a tester try to replicate this and send me a save file?

**Comment by Remerod** [comment]
I've recreated the issue and confirm, the orcs of the same culture and religion can revoke the holy orders they have after saurons death with the destroy mordor, but Denethor can't revoke the orc holy order outside of Minas ithil.

![image](https://user-images.githubusercontent.com/79544635/155382360-a36dda2c-0d8c-429f-9488-34580876a6e6.png)

I'll see to it that you get the save

**Comment by jj248** [comment]
Save: https://discord.com/channels/751097183448727552/751097880101650532/946110338951163974

**Comment by Remerod** [comment]
I'm moving this back to bugs, since a save file been provided and further stuff need to be sorted out

**Comment by jj248** [comment]
This is a vanilla issue I can't really fix I'm afraid.  Will keep on the backlog.
