### ISSUE TITLE
Are Gondor's vassals too loyal?

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#38]
**From the Discord:**

Everyone freaking loves the kings of Gondor, so they can just increase crown authority at will and still have most vassals at 100. So basically factions are impossible to form to decrease crown authority.

While this tracks well with the lore, is it too limiting in terms of gameplay?

**Comment by VectorMaximus** [comment]
I could see us lowering the bonuses for Numenorean blood, since at the moment I believe it does a double dip - once for same religion, once for sharing blood of Numenor. We could drop both of those to 5 or 10, and would go a long way to reducing that overwhelming positive opinion.

**Comment by ercarp** [comment]
I think we should probably nerf it to allow for more interesting things to happen. Peace is great and all but if the ruler is being tyrannical or raising crown authority, I don't think their vassals should be too happy about it.

It should be possible for civil wars and such to happen within Gondor as a consequence of poor or questionable rulership.

**Comment by VectorMaximus** [comment]
I've nerfed the Numenorean Blood now, but I'll leave this unclosed in case we want to further adjust the situation.

**Comment by isam0** [comment]
would be cool if there is more infighting but is mordor than not to strong ?

**Comment by jj248** [comment]
Agreement on Discord that this is largely where we want it to be now.  Closing and keeping an eye on things as part of regular balance watch.
