### ISSUE TITLE
Elven life cycle mechanics

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#384]
Base game life cycles need to be adapted to make sense for elves.  Specifically:

**Ages of Maturity**
Physically mature at 50, adult at 100 - will need some thought!

**Courtship**
Elves are monogamous and have their own courtship and marital rituals.  Extra-marital affairs and non-consensual acts are entirely unheard of.  Usually elves are betrothed for a period before the marriage.  We should speak to Tobbzn about the potential to use WoK's courtship system as it feels well-suited here - investigation required.

On death of their spouse - they should not remarry.

**Childbirth**
Number of children should be limited, with elven couples rarely having more than 3 / 4 children.  Childbirth only occurs within marriage and is a conscious decision on both parties.  This should therefore be decision based with elves having zero fertility - the implications of this on marriage acceptance modifiers should be considered.

Elven gestation periods are longer and so pregnancy should be handled via event.  Need to check if pregnancy trait will auto-pop a child after 9 months.  May want unique stats anyway for both male and female to show spiritual commitment and nurturing of the child.  Will also need to think of how that interacts with the pregnancy blendshape transition.

Events during pregnancy could offer chances to expend even more mental and spiritual energy to provide buffs to the future child.

**Death**
Elves should not die from any illness.  Any death should only be caused in battle, murder (though they should be *very* hard targets!) or through sorrow.  Upon death, they should receive the Unembodied trait, and be moved to The Halls of Mandos, which would be landed in Valinor. While in this title’s court and having this trait, they are essentially disabled, unable to inherit or take actions, but still alive in game terms. This way we can simulate if necessary the ‘return to life’ of characters such as Glorfindel, Finrod, and Gandalf.

**Comment by Jauffr** [comment]
After Playing a few games as either custom elves, or elves who can still have children. I can say that their entire life cycle functions as intended. The AI is also capable of and does in fact make use of all the intended systems as well. My only question is whether or not putting more spiritual energy into your children makes you less likely to want more. I have literally always put the max effort into them and I have never been able to have more than 2 before deciding the family is complete. Here are screencaps from the major moments across a lifespan of an elf, working as intended. Its a lot, so prepare yourself
![Screenshot 2023-02-23 222102](https://user-images.githubusercontent.com/108106660/221103732-708719b7-b1e8-4c30-b586-35d146eaf0c8.png)
![Screenshot 2023-02-23 222417](https://user-images.githubusercontent.com/108106660/221103739-db57cd2d-ca35-429f-a9fe-6b3dd3f1de89.png)
![Screenshot 2023-02-23 222431](https://user-images.githubusercontent.com/108106660/221103746-68562549-7fbf-4d64-b70b-fdb175f9924a.png)
![Screenshot 2023-02-23 222622](https://user-images.githubusercontent.com/108106660/221103751-5ce9aeb5-4bc3-4c1b-b5de-3f08e102315f.png)
![Screenshot 2023-02-23 222632](https://user-images.githubusercontent.com/108106660/221103756-d101bafe-532c-4c01-b5ac-68a137ca9e4e.png)
![Screenshot 2023-02-23 222710](https://user-images.githubusercontent.com/108106660/221103760-ddb8ede4-1f31-4a7c-8c54-7bc6da220674.png)
![Screenshot 2023-02-23 222819](https://user-images.githubusercontent.com/108106660/221103762-ceab650d-9ecc-4209-a524-d7d81a648566.png)
![Screenshot 2023-02-23 222920](https://user-images.githubusercontent.com/108106660/221103763-6f7d5d86-35a3-4d33-9d25-ffaea8600cf1.png)
![Screenshot 2023-02-23 223002](https://user-images.githubusercontent.com/108106660/221103766-4bc2b904-ae58-4751-8bc0-0e837bb21716.png)
![Screenshot 2023-02-23 223032](https://user-images.githubusercontent.com/108106660/221103770-b3330b7d-5301-41e8-9464-662ff0cf9e9e.png)
![Screenshot 2023-02-23 223620](https://user-images.githubusercontent.com/108106660/221103772-9f683480-8ad1-4e4a-abf2-d18ee2b02af0.png)
![Screenshot 2023-02-23 223646](https://user-images.githubusercontent.com/108106660/221103776-afd1952e-92aa-4712-9e79-35440eaf875b.png)
![Screenshot 2023-02-23 223703](https://user-images.githubusercontent.com/108106660/221103778-610ba01d-d903-423c-a649-613be18abfd1.png)
![Screenshot 2023-02-23 225249](https://user-images.githubusercontent.com/108106660/221103779-5e84337e-aa54-4a7a-914d-dd05686b18ad.png)
![Screenshot 2023-02-23 225307](https://user-images.githubusercontent.com/108106660/221103786-e6f1e05c-40ae-4c04-9551-4092aae5e5c8.png)
![Screenshot 2023-02-23 225400](https://user-images.githubusercontent.com/108106660/221103788-68fc9503-be4e-4ad7-a48b-ccb9f405fcff.png)
I have never seen an elf be killed by a disease by the way
