### ISSUE TITLE
Harolestad bug

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#387]
if you play as a custom char at Harolestad after 5-6 ingame days you get game-overed and the land transfers to Reedwater
my personal gues is that even though Elegost does not own Harolestad he still gets the event and since ai always picks the option that gives the county to reedwater i think thats what causing it could make it so that elegost only gets the event if he owns harolestad

**Comment by jj248** [comment]
Fixed - closing.
