### ISSUE TITLE
Multiplayer Empty-Event pop-up

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#393]
So we've had this bug for a while but i think we've pinpointed it now! It occurs during multiplayer, it pop ups a fast empty event and closes withing a second. Some of us are pretty sure it's tied to when armies moves from one province/barony to an other. We should probably try to host an mp internally and try to find thus bug in the error log or something while playing multiplayer together (along someone who knows how to pinpoint that stuff in the error log)

**Comment by MattTheLegoman** [comment]
The file `army_on_actions` is a place to look.
