### ISSUE TITLE
Suggestion: Less internal struggles in Gondor

### ISSUE THREAD

**Issue by josejuanmartinez** [MattTheLegoman/RealmsInExile#398]
Hi! I play a lot with South Gondor and what I find everytime I play is the internal regions start struggling with each other even during times of war with Mordor. I'm talking not only about South Gondor, but North Gondor too. This is an example: 

These guys decided is the best time to have internal combats...

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/36634572/162634721-263900b0-7175-4bd8-81d9-4ac41c224a74.png)

</details>

... while this is happening on the borders are they are almost not reacting...

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/36634572/162634746-71aab755-c8c3-43ed-9445-fe91cf1f4ac9.png)

</details>

Maybe we could reduce the internal wars in gondor at least while they are at war?

**Comment by JukeJukestar** [comment]
I think that internal struggles are an integral part of playing a vassal of gondor and without them it would be far less fun/ rewarding. Adding an extra mechanic for this also seems a bit redundant.
Gondor can get Low Crown Authority at game start and move up to Medium after 20 years (at which aragorn arrives)

As a solution to this issue, make the event that makes Aragorn king also give him medium crown authority

**Comment by josejuanmartinez** [comment]
One thing is some internal struggles. Another thing is being unable to fight Mordor because all of your neighbours are in wars among them or against you, all game long. It's almost a constant civil war. I don't think it's something that makes sense with how Gondor is described in the books.

**Comment by Vierwood** [comment]
I agree, and I know we've been meaning to make a custom government type for the Dunedain/Gondorians, so maybe implementing that and connecting it to the likelihood of factions would be the right course.

**Comment by Remerod** [comment]
This is something to still think about, but with it getting a new government, people wanting internal gameplay and needing to balance gondor vs new mordor in 3.0 anyway i don't think we need this issue opened, i've talked with @josejuanmartinez and we're closing shops
