### ISSUE TITLE
Non-Orc players can get Orc characters through invites to court

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#41]
This appears to be both when summoning knights and physicians, example below:

![](https://cdn.discordapp.com/attachments/778645689089392730/828256916651900948/20210404_142305.jpg)

**Comment by jj248** [comment]
And random characters in other events it seems: 

![](https://cdn.discordapp.com/attachments/812635981265109054/828249048305631272/unknown.png)

**Comment by jj248** [comment]
Can place some additional restrictions on knight candidates under the invite knights hidden event.

**Comment by jj248** [comment]
Looking at the code for the unpleasant guest in this scenario, it's picked from a random vassal party guests.  The 'problem' is more that the ruler has an orc vassal here which I believe Arsonium has largely fixed, so I won't look at this but keep it under monitor.

**Comment by jj248** [comment]
Fix applied for knight options with the following restrictions:

 - Free Peoples or Free Peoples aligned Men of Darkness do not allow Forces of Evil or orc candidates.
 - Forces of Evil or Forces of Evil aligned Men of Darkness do not allow Free Peoples candidates but don't discriminate on race.
 - Non-aligned Men of Darkness accept anyone

**Comment by RedArkady** [comment]
I think this is fixed. Only time orcs show up in a weird way is when they sometimes come to offer you gossip that so-and-so is conspiring against you.

**Comment by jj248** [comment]
Mercenaries are based on the cultures around you, so it'd make sense that you'd start to see orcish merc bands if you got closer to their territory.

By the sounds of comments from Red and Juke, guests seem a lot more sensible than before.  Suggest we close but just keep it in mind as something to look out for in the future.  Closing.
