### ISSUE TITLE
Localisation error in Return of the King event if Minas Tirith has fallen

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#421]

**Comment by RedArkady** [comment]
![a61eb76a-5ef1-43f5-a2e6-bc01eb438c97](https://user-images.githubusercontent.com/20355423/166435898-a04c505e-9a03-4246-98c9-173f224ce0d7.png)

We might want to switch 'Minas Tirith' here to realm capital, as I've just seen it happen on @garius's stream after Minas Tirith has already fallen...

**Comment by jj248** [comment]
Done - closing.
