### ISSUE TITLE
Suggestion: Struggle for The lands of-/Greater Bellakar 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#422]
### Introduction
One of the closest world parallel region to vanilla ck3 is Bellakar, or Greater Bellakar to the Iberia situation. And I really think it would make an almost 1:1 conversion for the upcoming Fate of Iberia DLC along it's free content (obviously it's not 1:1, because we don’t have Christians and Muslims and so on).  
 
![image](https://user-images.githubusercontent.com/79544635/166668783-7e848ce9-230b-44ed-8318-2c727825c67b.png)
**The Lands of Bellakar** "map"

### What we Know so Far
The Majority what we know so far comes from [Dev Diary 94]( https://forum.paradoxplaza.com/forum/developer-diary/crusader-kings-3-dev-diary-94-anatomy-of-a-struggle.1522115/) & [Dev Diary 95]( https://forum.paradoxplaza.com/forum/developer-diary/crusader-kings-3-dev-diary-95-flavor-of-iberia.1522983/)

A struggle is a long-form conflict (generally not just a war, though they likely include them) covering a particular chunk of the map. They have different phases, each of which have different variant gameplay rules (e.g., “holy wars are disabled”, “characters of different religions may marry without”, or “Jerusalem can’t declare or be declared war on”). The Struggle are Local to large areas, the struggle region - a predefined group of titles that the rules of the struggle apply within.
Cultures and faiths are regarded as either involved or not. Cultures become involved either on first starting a struggle, manually via script, or automatically when a certain percentage of their total counties are within the struggle region. Neither cultures nor faiths lose their involvement automatically. Once they’re in, they’re in permanently, unless manually removed via script.

Within the region, characters are defined by their personal involvement, which comes in 3 stages; Involved (part of conflict), Interloper (not part of the struggle, but the character is either landless or hold land and capital in the region but ain’t of the affected cultures or faith) and Uninvolved (characters are outsiders and outlanders. Their concerns are remote to the struggle region, basically they are not counted for the struggle, and can get maluses for involving themselves in the struggle). 

Phases progress between each other by way of catalysts, specific gameplay actions (“declare war on an involved character”, “two involved characters become soulmates”, etc.) that accrue points towards a future phase. When enough points are accrued, the phase changes to the new one. Transitioning from a phase to any of its future phases requires the activation of catalysts: notable events, gameplay actions, and consequences to existing mechanics that drive the current phase towards a specific future phase.

![image](https://user-images.githubusercontent.com/79544635/166669348-4c81f728-42d4-463c-9509-309c1d9dae0b.png)
Phases and cataclysts

Struggles can be resolved, permanently affecting their area in some way, through dramatic and difficult ending decisions. We know of 3 ending decisions currently, but these can probably be moddable. 

* Batalyaws Dominance, Hostility’s ending decision is Dominance, reflecting the final ascension of one of Iberia’s warring states to a position of not just military dominance, but social and spiritual hegemony.
* Détente, Conciliation’s ending decision is Détente, making temporary accommodations into more permanent ones.
* Status Quo, Compromise’s ending decision is Status Quo. Where Dominance is enforcing will and Détente finding accommodation, Status Quo is accepting that times have changed, that attempts to unite the peninsula are futile, and that its peoples and realms should go their separate ways and leave their neighbours be.

They are assumed to last at least a couple of centuries: a conqueror carving out a new realm from the ruins of an old giant wouldn’t be a struggle by itself, but if it includes dramatic aftershocks that last for generations, then it just might be.

new shared Head of Faith mechanic will add dynamism to Iberia’s fractured religious landscape.

Fate of Iberia contains a multitude of events and decisions ranging from struggle-specific events which shake-up plans, struggle events help add a bit of chaos to the overall equation, presenting many opportunities themed around the current phase for cunning strategists to turn one’s disaster into another’s advantage during the greater conflict. Struggle events are exclusive to characters partaking in the struggle. flavour events that help bring the Iberian peninsula to life and create a greater breadth of content for players in the region to experience. Many of these events are inspired by recorded happenings in the region, while others are simply classic Crusader Kings’ events in a Mediterranean flavour.

New Decisions, Fate of Iberia also features unique decisions which can be taken throughout the duration of the struggle at specific phases.

![image](https://user-images.githubusercontent.com/79544635/166668948-2b3cdec7-20aa-44d0-96e6-d6774e15869f.png)
As the sponsor, you will receive various positive modifiers, though everyone else in the struggle will receive a weaker version of them too. This decision is not exclusive and anyone can “steal” the golden age from you

![image](https://user-images.githubusercontent.com/79544635/166668964-045e3305-c4f0-4415-84cf-b059e5970dcf.png) 
“Iberian Foothold” decision, which encourages large foreign powers to make a dash for their piece of the metaphorical Iberian cake by letting them end the struggle from the outside. Though the military investment will certainly be large and the many disunified states in Iberia won’t take their conquest laying down

### The Lands of Bellakar
So Why Bellakar? As I mentioned above it’s very Similar to Iberia, Bellakar itself have a similar Christian & Muslim syncretism both in faith and cultural with the Kâthasaptha, pagan cults and Bâtan an-Izindi, and the cultural ties with Bellakarani, Bellanarûd & Bellakaze which is kinda visigothi/celt, Berber/Arab and a mixed culture respectively. And that’s just Bellakar proper. 

![image](https://user-images.githubusercontent.com/79544635/166669160-11a04aab-ea39-4dec-b5aa-08fb3e169001.png)
Blue: Involved the lands of-/Greater Bellakar. Green: Interlopers. Red: Uninvolved. 

**“Involved”**
As mentioned, we got ton of stuff for bellakar proper, we’d could reconstruct the Rapproachement Between Bellakar and Felaya decision into a proper struggle mechanic. The struggle with reconquer greater Bellakar as a Kâthasaptha (with no holy wars) or try a more multi-religious realm, or maybe some great new syncretism or conversion to Bâtan an-Izindi. 

Then we have the Felayans and Bâtan an-Izindi which could grow to a greater contender with this maybe? Maybe they can get a greater roll to convert (and help) the Bor align tedjin and other bellakar chanigans.

The Tedjin confederacy feels like it was made for this System, you have so many struggle things, so many marriage arrangements that could be done

And then we have the Mardrukan, who would most likely be the minor participants but still a fun goal to try to resolve the Greater/Lands of Bellakar conflict with. 

**“Interloper”**
to be fair the Mardrukan rather could be “interlopers” yes they are in the region, but they are pirates and don’t really care, this would make it harder to play them, but that could be fun in itself.

As Cultures can be coded into the system, bot the Umberians and Anbalûkkhôri as people with an investment in the region, Umberians most likely will go south and we can have them become interlopers by taking a county in Mardrûak (or just have it so they still hold relevance ´but just lost lands) and make them “Involved” once they successfully form the kingdom of Mardrûak, this way it won’t get obvious for Umbarians to get involved in the region but would give them a certain flavour if ai or player choice so.

the Anbalûkkhôri also could get some thing maybe for them to get involved, but maybe both the Anbalûkkhôri and the Umbarians simply would benefit from a “Iberian Foothold” decision.

**“Uninvolved”** 
there are several factions who would start as uninvolved but would soon be able to maybe become at least an Interloper

Ray for one, they could either start as an Interloper to show that they have ambition to get involved with Bellakar affairs

then we have all the Qarsa and Aukar just north-east of Bellakar, while bellakar is strong it’s unlikely they do anything but the chance is not 0%. 

### Conclusion
There is just so much here, there is 6 base cultures with maybe 9 or more with interlopers. 8 faiths, with potential of more. The events seem “easier” than other areas to convert to, because of the similarities of Iberia and The lands of-/Greater Bellakar region.

Now there is of course the question of, is it worth it? Would the area gain a lot by converting it into the struggle system? Yes but maybe no? the system we have are already quite ok and the effort in converting it to the struggle system might be effort better spent elsewhere rather then back here, but having said that I do think The lands of-/Greater Bellakar would make the ideal “testing” ground for the struggle system. But if that is unwarranted then yeah maybe this is better off for the future, but I do think it would one day benefit by a struggle system!

Faiths and Cultures
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/166669539-0f8f779e-28a4-41ac-8582-42fafe1bcb1d.png)
A Smörgåsbord of faiths!

![image](https://user-images.githubusercontent.com/79544635/166669642-8c46683c-dd43-4b7a-82cf-964ddce79e86.png)
So many cultures!

![image](https://user-images.githubusercontent.com/79544635/166670842-4a4286b5-ddd2-47b4-835c-3ef3fd5c6ab3.png)
It's the perfect opportunity to "_make Bellakar **Teal** again_"

</details>

**Comment by JukeJukestar** [comment]
The Bay of Tulwang might be an interesting area to consider for a struggle as well, with bellakar, Rây, the Stormhost, the Tulwangi natives and potentially Abrakhân all having aspirations to rule

**Comment by Remerod** [comment]
to my dismay this have sadly been rejected, in favour to the bay of tulwang, so i'll close this issue
