### ISSUE TITLE
Intermarriage and buy truce unlocked

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#434]
Intermarriage and buy truce interactions are unlocked in some regions (Harondor is where I encountered it)

**Comment by jj248** [comment]
Buying truces only are available for characters with Defensive Measures lifestyle perk - this is working as intended.

Need more information on what intermarriage is please @BriceLeduc  👯

**Comment by BriceLeduc** [comment]
By intermarriage I mean between hostile faiths
