### ISSUE TITLE
Dunedain court doesn't show up

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#435]
In 2.4 Dunedain characters all have the vanilla Mediterranean court room

**Comment by jj248** [comment]
Looks to be working fine now.  Closing. @BriceLeduc - let me know if there's something I'm missing here. 
![image](https://user-images.githubusercontent.com/26043074/178359755-02c35f3e-0dbd-4d82-a268-9b7f4e63bcb3.png)
