### ISSUE TITLE
Become Masters of the Mediterranean

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#438]
The decisions is available to Bellakar and should be disabled

**Comment by Remerod** [comment]
to be a little clearer, there have been bug reports for the compatch 2.4 that bellakar can Become Masters of the Mediterranean, which i believe are these modifiers?

![image](https://user-images.githubusercontent.com/79544635/178152927-8c9dec71-abf4-49bf-8846-0264360fb220.png)

![image](https://user-images.githubusercontent.com/79544635/178152929-af02f419-5f3c-474c-b3bb-723629d48818.png)

**Comment by JukeJukestar** [comment]
Didnt see a decision for it when I played bellakar for about a year. I got all DLC exept Iberia

**Comment by JukeJukestar** [comment]
This decision would be quite easy to modify to fit realms, question would be where? Maybe for the Tulôrians (Sôriyans) In Tulwang to get their own pirate kingdom?

**Comment by jj248** [comment]
Looks to be fixed - closing.
