### ISSUE TITLE
Abrakhan decision to Request Lands from Mordor

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#439]
So there been request/complaints that Abrakhan can't finish their Event quest to unite Harad because his ring master Sauron takes land that the Golden King need.

So talking in a dev-chat with jamie and some others a solution to this could be that Abrakhan gets a decision to request land from his Master(if he hold some of those lands) that's part of the unite-Harad event chain and get those for a cost of troops/gold/whatever

**Comment by JukeJukestar** [comment]
Good idea. This should also make him Saurons Tributary (that joins wars) since he is now absolutely close enough to contribute directly.

**Comment by Remerod** [comment]
yeah, since this "decision" might be needed to take several times, since sauron could have potentially/unlikely gone threw a conquest spree, having different choices from becoming tributary is necessarily i believe

**Comment by JukeJukestar** [comment]
After the first time (would require bordering sauron) it could be made a repeatable decision where you just pay him some extra tribute in gold. in case he conquers any more counties in harad.

The way I see it this decision would have to account for two scenarios:
a) sauron somehow got a random county in the dune sea or somewhere else in far harad
b) Abrakhan has conquered most of harad and now holds most of Haruzan, but Sauron owns 2 duchies in it

**Comment by jj248** [comment]
This *should* be in now.  So one to test.

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/197232137-48fa52b8-fdcd-438b-9763-f1910003725c.png)

Apparently since the decision gives over vassals, if a large vassal (such as Nurn or Morgul) holds lands in Harad, Sauron will give them over to Abrakhan!

**Comment by JukeJukestar** [comment]
It only gives a few duchies at a time now, not everything you'd actually get. This way youll have to wait for the cooldown and keep pressing the decision whenever avaiable. Dont think this is intended?

**Comment by jj248** [comment]
It was actually, generally to prevent a huge swing of territory when they first border each other.  It's largely a moot point now I guess if we expect him to be recalled.

**Comment by jj248** [comment]
Is there anything left on this @JukeJukestar ?

**Comment by savagesach** [comment]
This decision works as intended
![image](https://user-images.githubusercontent.com/86676697/221262276-dcca03ee-16a1-4fab-90d0-20a9ef3bf5ac.png)
![image](https://user-images.githubusercontent.com/86676697/221262467-d4eafb5a-a63c-4334-8dd0-808d016e333c.png)

**Comment by savagesach** [comment]
I think the issue can be closed
