### ISSUE TITLE
Bug: Immortal Characters killed through "Getting A head" RC event

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#441]
This ones a recurring one but I couldn't find a direct issue on it.
Most events that can kill someone randomly have been patched to not kill immortal characters, but sometimes new ones slip through.
(related to #84 )

![image](https://user-images.githubusercontent.com/76008882/178211929-69718e08-25bf-4c48-ae58-2cb8a6ab5d32.png)

In this case, the "getting a head" court event from Royal Court (in which a fanatic cult wants to look for the head of their leader in your castle, if you throw them out there is a chance they return to kill you) allows for someone to be killed. We know its this event chain because it was reported with the "almost decapitated" death reason which is a special one only for this event chain.

It should be noted that the community believes this is one of the worst events added by RC and removing it entirely would be a valid option

**Comment by jj248** [comment]
Put a blocker in for immortal-esque characters:

NOR = {  #LotR
			is_valar = yes
			is_maiar = yes
			is_undead = yes
			is_elf = yes
		}

**Comment by JukeJukestar** [comment]
Ill be closing this then @jj248
