### ISSUE TITLE
Bug: Tedjin Civil War faction does not appear (2.4 compatch)

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#444]
The special civil war faction that is supposed to appear once Bôr chooses to become a Tedjin reformer during the crossroads of destiny never appears.
The crossroads event fires as normal but does not lead to Azumen forming his special faction.
May be related to the new dissolution faction added by Fate of Iberia.

There is also the issue of Bôr sometimes accepting a demand conversion request from his father while he is still alive, leading to him choosing "Tedjin reformer" despite being of the old tedjin faith. This could be solved by having the event that triggers on the death of his father always convert him to the reformer religion just in case.

**Comment by jj248** [comment]
I haven't been able to reproduce this - I'm getting the faction as normal and it also worked in the recent MP.  There *is* a chance that it doesn't trigger, maybe you just got unlucky?

Have fixed the second point.
