### ISSUE TITLE
Bug: The Butt and Bust washboard dilema 

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#445]
There have been an issue for a while that most female characters Butt and Bust have become flat as a washboard!

![image](https://user-images.githubusercontent.com/79544635/178370910-20e0d831-5bbc-4907-9bde-3218d196ff44.png)

While this is fine for certain characters it should definitely not be a general rule and we should invest heavily in resources and personal to solve this great crisis that is plaguing our great mod!

**Comment by Remerod** [comment]
After Intensive buttocks "researching" for several hours in the base game by our heroic tester @Jermanlordy it have come to the conclusion, that @jj248  was right.... There is only one size of buttocks. Even if this is a very sad revelation for us all, the Bust dilemma is still plaguing us. We must put this sad butt crisis behind us and focus our energy and effort into solve the remaining dilemma and making sure our mod have all different variation representing all people, from washboards to melons! 

![image](https://user-images.githubusercontent.com/79544635/178824996-76f43e4e-aac0-4778-91b5-417bd466a383.png)

_the Saddening Proof_
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/178825111-f84b1c4f-db9a-48e0-8918-6965ded74602.png)

![image](https://user-images.githubusercontent.com/79544635/178824409-697da315-d331-4c39-9d8b-20e8dbb07442.png)

![image](https://user-images.githubusercontent.com/79544635/178824445-d98de856-6bb6-4c9c-81d3-47e7a2f2d6cd.png)

![image](https://user-images.githubusercontent.com/79544635/178824491-d78faa0b-8741-42a5-b4a1-edcd05785310.png)

</details>

**Comment by BriceLeduc** [comment]
I can confirm the problem comes from FS Barbershop : I had the "Clothes Thief" event and the woman looked normal. But the "no clothes" option in barbershop gave her skinny legs and flat breasts. Solution : use the "undress" mod for further checks

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/179537268-6913d89c-15f9-49e5-b127-0a56e8f1198d.png)

What a tragic irony of fate. We are forced to support our rival mod, who is one of the reasons we are no longer on the front page in most subscribed mods (we are no. 9 and it displays up to 8)

**Comment by jj248** [comment]
I've removed the no clothes options.  This should now be fixed.  Testing to confirm.
