### ISSUE TITLE
Potential bug making Isengard an intrigue powerhouse

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#45]
Technique mentioned a few times.  Might be worth some sort of nerf.

**From Discord:**

id say if you want a mighty kingdom, isengard would be the way
just declare war, kidnap, influence everyone in there kingdom for a hook and then successfully kidnap them, win war with 100% war score.... rinse repeat
i havent had to fight a single on-field battle because of how strong that is

**Comment by jj248** [comment]
Putting this in the beta testing area for Red to investigate and give feedback to developers.

**Comment by JukeJukestar** [comment]
Influence is being removed / replaced with the rohan overhaul #536
