### ISSUE TITLE
Genetic Orc Skin Tone

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#450]
So I put together a list of examples of orc skins as references for the Orc Skin rework. The references are from mostly the movies and games + some concept arts. I do think these are the most common colourings on the orch skin.

**Beige**
<details>
<summary>Click to expand</summary>

LOTR Hobbit & movies 
![BEIGE-HOBBIT-Goblins_High_Pass](https://user-images.githubusercontent.com/79544635/180621726-6fb8fc77-6cd3-4183-ad2b-6f369df70888.jpg)

![BEIGE-LOTR-lord-of-the-rings-10-things-you-didnt-know-about-orcs-main](https://user-images.githubusercontent.com/79544635/180621731-859aba3f-63d2-4fa9-8f26-d2f5e00ed4d5.jpg)

![BEIGE-LOTR-ORC1](https://user-images.githubusercontent.com/79544635/180621747-620945a3-a2d0-4fe2-b1a0-0c3e0b643b4f.jpg)

LOTRO
![BEIGE-LOTRO-494px-Bloodless_Archer](https://user-images.githubusercontent.com/79544635/180621736-18874d6d-1bf9-4208-b205-4d3644c843a2.jpg)

![BEIGE LOTRO orc1](https://user-images.githubusercontent.com/79544635/180621710-b74bfd12-4c68-4c25-ad59-63d691507fdc.jpg)

![BEIGE-LOTRO-800px-Forgeworker_(Orc)](https://user-images.githubusercontent.com/79544635/180621744-472b2d81-24eb-44c7-8044-9251e9f29dad.jpg)

LOTR Rise to War
![BEIGE-RTW-GORBAG](https://user-images.githubusercontent.com/79544635/180621751-c6cb2f6f-dc77-470c-89f8-248a6dcb2d4c.jpg)

![BEIGE-RTW-SHARKU](https://user-images.githubusercontent.com/79544635/180621754-e1708545-4182-4d0a-806b-bf81fd8ae42a.jpg)

</details>

**Blue**
<details>
<summary>Click to expand</summary>

LOTR Rise to War
![BLUE-RTW-SHAGRAT](https://user-images.githubusercontent.com/79544635/180621827-69400b4b-5cbc-4b02-9b27-a5bac547b33a.jpg)

LOTR Shadow of war/mordor
![BLUE-SOW-Bald](https://user-images.githubusercontent.com/79544635/180621829-e82faafd-7a19-470b-a05b-64c1b444256f.jpg)

Teal Orc from LOTR Shadow of war/mordor
![TEAL-SOW-ORC1](https://user-images.githubusercontent.com/79544635/180622302-b50e9a07-7a17-4e62-9047-f4abf511c003.jpg)

</details>

**Brown**
<details>
<summary>Click to expand</summary>

LOTRO
![BROWN LOTRO 200px-Hobgoblin_Brute](https://user-images.githubusercontent.com/79544635/180621851-a331ce8c-e193-405b-aec2-31cffa8dc912.jpg)

![BROWN LOTRO 469px-Hobgoblin_Captain](https://user-images.githubusercontent.com/79544635/180621853-266210be-77ed-465a-86f2-c9d4650a030c.jpg)

![BROWN LOTRO Hobgoblin_Necromancer](https://user-images.githubusercontent.com/79544635/180621854-12b21813-f302-4095-982a-bb153a87cb87.jpg)

![BROWN LOTRO Loknashra_(Mount_Gundabad)](https://user-images.githubusercontent.com/79544635/180621858-1c333596-48c5-4c1d-add5-4c4de862a754.jpg)

Age of the Ring Mod
![BROWN-AOTR-uruk_berserkers 1](https://user-images.githubusercontent.com/79544635/180621860-db37f527-cc08-45a4-a9ee-57d9793aef44.jpg)

LOTR Rise to War
![BROWN-RTW-Grishnákh](https://user-images.githubusercontent.com/79544635/180621862-4d00b7ac-d5d6-4a42-ab42-540ee8d960ac.jpg)

LOTR Shadow of war/mordor
![BROWN-SOW-orcs_header](https://user-images.githubusercontent.com/79544635/180621867-1c5a4ace-a696-4e99-9edb-105189be975f.jpeg)

![BROWN-SOW-shadowloot](https://user-images.githubusercontent.com/79544635/180621869-09748369-e53d-48c1-b759-ded72698d2af.jpg)

![BROWN-SOW-shadowofwar13](https://user-images.githubusercontent.com/79544635/180621873-eefc3080-1a4b-4f80-a265-8b99dec9ca78.jpg)

</details>

**Dark**
<details>
<summary>Click to expand</summary>

LOTRO
![DARK-LOTRO-Mordor_Guard_(Talath_Úrui)](https://user-images.githubusercontent.com/79544635/180621896-f378e7b4-45ab-4bcd-9868-b6f252810710.jpg)

LOTR Rise to War
![DARK-RTW-ORC ARCHER](https://user-images.githubusercontent.com/79544635/180621901-af5bc73a-593a-4bab-939b-7eaf96a87f70.jpg)

![DARK-RTW-STALKER](https://user-images.githubusercontent.com/79544635/180621903-ac2055cb-68d1-4b81-bc9b-99a42af51822.jpg)

LOTR Movies & WETA DESIGN
![DARK-LOTR-URUK-Hai1](https://user-images.githubusercontent.com/79544635/180622662-faed915d-f825-4ef1-93f2-1b2905cee35a.jpg)

![DARK-LOTR-Uruk-Hai2](https://user-images.githubusercontent.com/79544635/180622665-d5af50d9-aa8e-408b-982a-5ded0561f0ac.jpeg)

![DARK-LOTR-Shagrat](https://user-images.githubusercontent.com/79544635/180622668-f2ce476c-cc13-4e88-bf68-0a7bc4d5ac7d.jpg)

![image](https://user-images.githubusercontent.com/79544635/180622750-22eefdee-2a17-4ff0-bbae-802075905b1f.png)

</details>

**Green**
<details>
<summary>Click to expand</summary>

Age of the Ring Mod
![Green-AOTR-Mûzgash](https://user-images.githubusercontent.com/79544635/180621920-11e31acd-ee03-48ad-8b51-bc7afb4ae8a3.png)

LOTR Games Workshop
![GREEN-GW-goblins1](https://user-images.githubusercontent.com/79544635/180621926-2fcae564-29fb-4d70-81fa-ca25f19523e9.jpg)

LOTRO
![GREEN-LOTRO-383px-Shakfut_Orc](https://user-images.githubusercontent.com/79544635/180621929-02fdd3e2-4e6b-493d-978f-4e6feaec6c45.jpg)

![GREEN-LOTRO-Hollowing_Orc](https://user-images.githubusercontent.com/79544635/180621938-e8939072-41d2-4934-acf6-2cc26e8e1b31.jpg)

LOTR Movies
![GREEN-LOTR-orc1](https://user-images.githubusercontent.com/79544635/180621941-a8e39484-0ed9-43d7-a6d4-04926a5e2b77.jpg)

LOTR Shadow of war/mordor
![GREEN-SOW-orc1](https://user-images.githubusercontent.com/79544635/180621943-21a8c4df-83c8-4bd3-acbd-243e4f7750a3.jpg)

![GREEN-SOW-Orc2](https://user-images.githubusercontent.com/79544635/180621945-817a8f16-fee2-4bfd-89b6-087c2ffaa776.jpg)

![GREEN-SOW-ORC3](https://user-images.githubusercontent.com/79544635/180621946-56d9f9f3-3035-470b-ad04-6b591676b479.jpg)

![GREEN-SOW-Orc-with-scars-generated-by-the-Nemesis-System-in-Middle-Earth-Shadow-of-Mordor_Q640](https://user-images.githubusercontent.com/79544635/180621950-c66ceb72-6007-4e68-a5a2-162cea4818eb.jpg)

The One Ring rpg
![VARIATION-TORRPG-orc1](https://user-images.githubusercontent.com/79544635/180622453-c5ad670e-6612-4ca0-95bd-9693e91871d8.jpg)

</details>

**Pale & Grayish**
<details>
<summary>Click to expand</summary>

LOTR AMAZON
![PALE-AMAZON-lord-of-the-rings-rings-of-power-orcs-first-look-battle-helmet](https://user-images.githubusercontent.com/79544635/180621987-4a1311af-6480-45f7-ad6b-ba5ca49daa7b.jpg)

LOTR MOVIES & WETA DESIGNS
![PALE-LOTR-ORC1](https://user-images.githubusercontent.com/79544635/180622027-45136d8b-eff6-4ff3-91d5-c38cc0f3a4f5.jpg)

![Gundabad Hoplites](https://user-images.githubusercontent.com/79544635/180622098-6a731fe8-601f-4e32-937b-68137e9860c3.jpg)

![Trait Gundabad Orc Berserker](https://user-images.githubusercontent.com/79544635/180622101-f5b7fe0e-7621-41ee-b746-828a6994812a.jpg)

![Weta Workshop Gundabad Orcs 1](https://user-images.githubusercontent.com/79544635/180622106-89e237c6-278d-4978-b658-c3c524386730.jpg)

![Weta Workshop Gundabad Orcs 3](https://user-images.githubusercontent.com/79544635/180622110-55c71eb3-ad6f-44a8-8051-56b9a8e2165f.jpg)

![Weta Workshop Gundabad Orcs 2](https://user-images.githubusercontent.com/79544635/180622118-abd48078-cc67-4fb4-91c5-df52e7f668c0.jpg)

![image](https://user-images.githubusercontent.com/79544635/180622771-6214c5f2-2603-4cfb-b25b-89f05e394447.png)

![image](https://user-images.githubusercontent.com/79544635/180623073-71466dfa-73df-49d2-aa22-a6b6e0f85ea4.png)

![image](https://user-images.githubusercontent.com/79544635/180623088-40063527-059e-4dda-9c74-f922c0bcbeb8.png)

![image](https://user-images.githubusercontent.com/79544635/180622855-0d099a84-ff57-4709-849b-b980f52c11a1.png)

![image](https://user-images.githubusercontent.com/79544635/180622859-0921c0e7-a6f4-4a22-abfb-2b0a7fca5333.png)

![Pale Orc](https://user-images.githubusercontent.com/79544635/180622122-c9425b07-19ed-4648-b6aa-374f1c74ffb3.jpg)

Age of the Ring mod
![Pale-AOTR-BoloftheNorth](https://user-images.githubusercontent.com/79544635/180621994-a154618b-5f42-4e1c-bf6e-10c130c62b4b.jpg)

![Pale-AOTR-LugMauledRender](https://user-images.githubusercontent.com/79544635/180621997-ca3fed8c-7119-4915-b3ab-532b57ee4fd5.jpg)

![Pale-AOTR-mountain_orcs](https://user-images.githubusercontent.com/79544635/180622001-22a4f63e-d81c-46ee-bfb5-a7f95de19aeb.jpg)

![Pale-AOTR-tombguardrender](https://user-images.githubusercontent.com/79544635/180622005-3621065a-aff2-48a5-82fa-13ed757e23ed.jpg)

![AotR mountain_orcs](https://user-images.githubusercontent.com/79544635/180622133-699a9bd7-4df0-4ba0-8d23-041cf7513966.jpg)

LOTRO
![PALE-LOTRO-534px-Gothmog_Defiler](https://user-images.githubusercontent.com/79544635/180622017-73bd14a6-dd1a-4826-bd7f-093dd749f454.jpg)

LOTR Rise to War
![PALE-RTW-GLASHA](https://user-images.githubusercontent.com/79544635/180622033-c6e90f3a-2976-428f-bf3a-680c3a467d95.jpg)

![PALE-RTW-Uglúk](https://user-images.githubusercontent.com/79544635/180622037-e6789c9a-4d39-4d0e-bed7-4caaecdfe0c1.jpg)

![LOTR RTW Gundabad unit Warlord](https://user-images.githubusercontent.com/79544635/180622157-32e65677-044f-4f27-b16c-69fb9b63f660.jpg)

LOTR Shadow of war/mordor
![PALE-SOW-Kristian-bourdage-nemesis001](https://user-images.githubusercontent.com/79544635/180622054-c61df68b-5fb3-43a7-a180-0e8e48083143.jpg)

![PALE-SOW-orc2](https://user-images.githubusercontent.com/79544635/180622057-a6faee85-5169-4b0a-b579-8434ffe004df.jpg)

War in The North
![PALE-WITN-orc1](https://user-images.githubusercontent.com/79544635/180622060-c0a2cd09-1507-42d3-9018-a2941428fce4.jpg)

![PALE-WITN-orc2](https://user-images.githubusercontent.com/79544635/180622063-14bb390d-8497-41ab-9bc3-91eed582282c.jpg)

![Tharzog 1](https://user-images.githubusercontent.com/79544635/180622178-ff2a8b6a-45d0-48e4-8aa2-dbdcfbd181fd.jpg)

</details>

**Purple**
<details>
<summary>Click to expand</summary>

LOTRO
![PURPLE LOTRO 200px-Uruk-hai](https://user-images.githubusercontent.com/79544635/180622207-c9ccd3fc-ffb2-491b-9135-c2e83150b8a5.jpg)

![PURPLE LOTRO ART](https://user-images.githubusercontent.com/79544635/180622215-29c31ff8-be1a-42e3-b07d-b8b7d59f925e.jpg)

![PURPLE LOTRO blue-crag-invader-goblin-enemies-of-yondershire-deed-lotro-400x400](https://user-images.githubusercontent.com/79544635/180622221-5667ab8f-122f-4688-89a5-0aeb29205439.jpg)

![PURPLE LOTRO bounty-akvosh-orc-west-delf-lotro-wildwood](https://user-images.githubusercontent.com/79544635/180622226-0e9959ce-59c3-4520-a775-d3fe59feb61e.jpg)

![PURPLE LOTRO orc1](https://user-images.githubusercontent.com/79544635/180622231-75e07a3e-a65e-4a4e-83d1-220c304addab.jpg)

Amazon & Peter Movie
![PURPLE-AMAZON-Orc1](https://user-images.githubusercontent.com/79544635/180622236-25f63be6-be59-4f9d-9e9e-6eececf0dec6.jpg)

![PURPLE-LOTR-orcs1](https://user-images.githubusercontent.com/79544635/180622263-bb8680f3-9d96-4abe-a3d2-0b0dbff712ed.jpg)

</details>

**Red**
<details>
<summary>Click to expand</summary>

LOTRO
![RED LOTRO top_5_lotro_best_pvp_class_11](https://user-images.githubusercontent.com/79544635/180622274-ed65c834-099c-418a-80fc-f87ee550a76c.jpg)

![RED-LOTRO-200px-Uruk-hai_Warrior_(Stonedeans)](https://user-images.githubusercontent.com/79544635/180622278-54c579ef-d220-430b-8f09-5daad3a5276b.jpg)

LOTR Rise to War
![RED-RTW Lurtz](https://user-images.githubusercontent.com/79544635/180622279-04ad5ff5-d451-4bc2-b877-bde480962c4d.jpg)

![RED-RTW-Berserker](https://user-images.githubusercontent.com/79544635/180622280-e851e210-a1dc-44e2-a142-9336adfec1ee.jpg)

![RED-RTW-Bruiser](https://user-images.githubusercontent.com/79544635/180622281-15d43cef-70ae-4860-a45f-47e844f9d44a.jpg)

![RED-RTW-Isengard's Ugthak](https://user-images.githubusercontent.com/79544635/180622287-4d181b3d-cbbb-4878-b344-cea87c04c223.jpg)

</details>

**Yellow**
<details>
<summary>Click to expand</summary>

LOTRO
![YELLOW LOTRO orc1](https://user-images.githubusercontent.com/79544635/180622330-ab16abd4-3369-4096-b848-03b2d624620e.jpg)

LOTR Shadow of war/mordor
![YELLOW-SOW-mordor3](https://user-images.githubusercontent.com/79544635/180622336-70204e5f-8938-41d3-b0e4-b4f926623348.jpg)

![Yellow-SoW-orc](https://user-images.githubusercontent.com/79544635/180622340-36d418a8-0552-4c11-9fb2-6933ff991ec8.jpg)

</details>

**Variations**<details>
<summary>Click to expand</summary>

LOTRO
![VARIATION LOTRO orc1](https://user-images.githubusercontent.com/79544635/180622369-d03170e8-732f-4ce4-993c-62981812a396.jpg)

![VARIARTION-LOTRO-Goblins](https://user-images.githubusercontent.com/79544635/180622372-a7d6cc39-2828-46d6-bc6d-549912d5a363.jpg)

![VARIATION LOTRO orc3](https://user-images.githubusercontent.com/79544635/180622391-e1fe3c31-ea1c-45df-8bda-df4801ef2e57.jpg)

![VARIATION-LOTRO-orc2](https://user-images.githubusercontent.com/79544635/180622428-20579dea-35f2-45f0-9a44-d11121b78288.jpg) 

LOTR Games Workshop
![VARIATION-gw-99061462020-0](https://user-images.githubusercontent.com/79544635/180622397-fa848ad4-ac41-498e-b7a3-770dfd6a7b97.jpg)

![VARIATION-GW-99121462015_MordorOrcs01](https://user-images.githubusercontent.com/79544635/180622408-2225885d-01aa-4476-ba64-f98d9d5a81cd.jpg)

![VARIATION-GW-Games_Workshop-LotR_v2-Mordor_Orcs-1](https://user-images.githubusercontent.com/79544635/180622412-b6838209-ef68-4642-83e5-e9966d998814.jpg)

![VARIATION-LOTR-lotr_orc_s__wallpaper_by_meanderingdreams_d5rycli-fullview](https://user-images.githubusercontent.com/79544635/180622421-c54ff148-9cf7-4196-81d9-d46d3124ad9f.jpg)

LOTR Shadow of war/mordor
![VARIATION-SOW-shadowofwar_nemesisforge](https://user-images.githubusercontent.com/79544635/180622448-8f154cd6-70a4-4ac9-8b41-7538a0cbd844.jpg)

WETA DESIGN
![image](https://user-images.githubusercontent.com/79544635/180622893-bf39eb88-d4e2-4578-a2a3-13fe725f1149.png)

</details>

Overall i maybe could have used a little more movie references But i belive these pretty much cover most of all orc colours

**Comment by Remerod** [comment]
If anyone else which to put in some more research/references feel free to do so! ;)

**Comment by Remerod** [comment]
# Introduction
I put together a list of what i think are the basic skin colours variations for the different orcish cultures/tribes.  

# Utumno Orcs/Proto-Orcs
**Utumno Orcs**
I think having them mostly as Pale, Greyish, Beige and light brownish works best for that “proto”-orcs vibe.

# Mountain Orcs
**Worauthai Madûr**
-The Northerners or Free Tribes of the North, these orcs are basically the base culture the orcs of the north splits from so they should mostly be Pale orcs should very from pale-ish white to pale-ish grey but if there are some other northern orc group with another tint to them then maybe the Worauthai Madûr should also have that to symbolize that they came from the Worauthai Madûr

**Forodwaith Orcs**
not in game/concept yet.

**Angmar Orcs**
-Worauthai Madûr who came under Service of the Witch King. They should basically look the same as the Worauthai Madûr. If we wanna make them more different from the other northern tribe maybe making them slightly more dark grey could be neat. 

**Gundabad Orcs**
Pale orcs should very from pale-ish white to pale-ish grey. Take inspiration from WETA designs

**Grey Mountain Orcs**
Either the same as gundabad or maybe a hint of brownish to make em similar to the LOTRO versions of them, where they are mostly Hobgoblins. 

**White Mountain Orcs**
Same as Isenguard?

**Isengard Orcs/ Uruk-hai of Isengard**
The Main colour of the Iseguard Orcs/Uruk-hai should be their brownish-red as they seem to be most represented with in games and art, but also with tints of dark & normal grey variations. LOTRO also have them with some purple variations and I quite like that, it goes into the red theme and having some look more red would also fit I think

# Uruks
**Murdur-Hai Orcs of Mordor** 
-The orcs Sauron unified in Mordor during the secound age 
I think these orcs is fine being inspired by the looks of the **Amazon**-show orcs, so basically a lot of Beige and greyish variations, with maybe some rare tints of dark grey and purpleish. 

**Kazgûmhoth Guldur-Orcs** 
-the orcs Sauron or the Necromancer as he is now known as united under Dol Guldur. They came from various places.
I think a mixture of the Mountain orcs white-grey paleish skin colours but more sickly grayish to give that necromancer vibe, a greenish colour (as inspiration of Moria orcs and maybe forest orcs) and some beige orcs, that would be could be seen as taken from mordor and more of the second age orc look

**Morlûg-hai Black Tower Tribe**
-Black Uruks of Barad-dûr. Their skins should most liely be Black, dark grey and maybe a small number with very dark purpleish tints

**Ungur-hai Terror Tribe**
-Note: use this culture to fill Mordor. They hold Minas Morgul. Their main colours should most likely be Dark grey/blackish, blue/tealish and other variations of grey with some being pale & greenish maybe

**Gûshmurash-hai Warmonger Tribe** (alt: Kutum-hai, Gûshmurash, Gusmuras)
-The Morannon Uruks (alongside the Black/Morannon Orcs) who lay seige to Minas Tirith. They hold Mount Doom and the Morannon. The SoW: have them look brownish-red/purple, Beige and mixing these colours togather with gray. But as they are also “black” orcs I think they could have a good variation of dark/blackish skins but less so in quantity then the Morlûg-hai culture.

**Ghâsh-hai** (alt: Goid-hai) Machine Tribe
-Note: use this culture to fill Mordor. The SoW: They appear to be brown-beige and grayish colours

**Burgûl-hai Dark Tribe**
-Note: use this culture to fill Mordor. The SoW: They appear in a wide range but often in light colours, light beige, light gray/pale and light greenish. 

**Rû-hai Mystic Tribe**
-The Rû-hai reside in a single county in the mountains of inner Mordor.  The SoW: They appear to be mostly very greyish pale, so maybe have them being mostly that with a small chance of other skins as they are supposed to be formed by several gatherings of orc “mystics”

**Gurgur-hai Slaughter Tribe**
-Special Uruk culture used for events. Use for characters.  The SoW: appear to most be beige-like with tints of red, purple and greyish along the beige

**Maraud-hai (alt: Nau-hai) Marauder Tribe**
-Special Uruk culture used for events. Use for characters. Matt note: actually the Nau-hai, but they prefer the Westron word Marauder. Their Mercenary Company the Maraud-hai is a corruption of their name.
The SoW: appear to most be beige-like, Brown and Yellowish-Green.

**Kû-hai (alt: Arataus-hai) Outlaw Tribe**
-Wild Mordor Uruk culture used for events. Early proto-Uruks. The SoW: appears to be light yellowish-green wbut also greyish with hints of beige, or maybe olive greyish is a better term?
 
**Garzog-hai Feral Tribe**
-Wild Mordor Uruk culture used for events. They are wild Uruks, decendants from uncontrolled breeding. The SoW: appear to most be light grayish but also beige-browns 

# Troglobite Orcs (Underground)
These are not in the mod yet
**Moria Orcs**
I guess these will be greenish and green grayish, they are more of the later in the main lotr movies but appear greenish in almost every art & game depiction of them 
**High Pass Goblins**
I hope we go with the Hobbit’s more realistic beige of them.

**Comment by JukeJukestar** [comment]
Seems cool to me!

**Comment by JukeJukestar** [comment]
Its very subtle now, but working I believe - closing for now, reopen if you want to revisit this!
