### ISSUE TITLE
Changes to medlouskan culture

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#463]
The Culture of Asdriag of the Medlouskan has By the sword this should probs be removed since its unlimited Kingdom Holywars wich is quite OP

![image](https://user-images.githubusercontent.com/96250463/182473139-ec623bfc-9056-4b52-a98d-e24509945c95.png)

**Comment by JukeJukestar** [comment]
I agree that its quite OP, but thats a vanilla issue.
Needing 1 level of devotion less is gonna push the AI to be more agressive, which is good for the dragon army

**Comment by jj248** [comment]
Closing this for now.  We can see how it pans out when testing begins in earnest.
