### ISSUE TITLE
Nurniag Suggestion

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#464]
Due to the Nurniag Lords under Khorahil not having the Religious Protection in The Feudal Contract they always get demanded to convert to Lidless Eye by Khorahil and if they refuse theyre land will get revoked meaning that over time Nurniag Religion entirely dissapears and Nurniag Culture also takes a big hit

**Comment by JukeJukestar** [comment]
This is already an issue, #125 

please close since its a duplicate.
