### ISSUE TITLE
Bug: Equal view on gender allows neither gender to become knights

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#465]
There have been several reports on equal gender knightship (through gamerule or creating an equal faith) disallowing anyone from becoming a knight.

This is tested on the 2.3 compatch version on steam but may very well also be an issue on master.
**This does not happen if Royal Court is enabled, only if it is disabled or not owned!**

![image](https://user-images.githubusercontent.com/76008882/182844390-dea6c2a9-01be-4d28-b309-1d61f07b5c77.png)

The same result happens if you make an equal gender faith, or if you set the gamerule to equal.

![image](https://user-images.githubusercontent.com/76008882/182845285-b64e1847-798a-433a-b125-f8a7759d1bc5.png)
 
discord user Edamir explained a possible reason for the problem here.

**Comment by VectorMaximus** [comment]
Fixed. My thanks for the diligent work in uncovering this in particular, made it a very simple fix
