### ISSUE TITLE
More forms of Executions

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#466]
Some people in discussion mentioned recently and i've heard it before that a lot of our executions tends to be by burning at the stakes for most faiths. This is something we likely we can change and do more flavorful. I'll keep this as a suggestion if someone is interested.  

I guess this is most likely a localization heavy issue, but research into lore and so on is still needed.

**Comment by JukeJukestar** [comment]
I made up a bunch. I tried to make them fit the religion if possible. Add those you like and leave out those you dislike
(some of these might be in already)

# Faithful (Gondor and Bellakar) / Elves
(they like to keep it simple and as humane as possible)
- Justly executed
- Hung
- Beheaded

# Northmen
(Simple execution methods; horses)
- Hung
- Beheaded
- Trampled by Horses
- Quartered

# Daen/ Dunlending
(Simple execution methods; Reference to burial cult)
- Impaled
- Hung
- Crushed
- Stoned to death
- Fed to the Dogs
- Buried alive

# Forces of Evil:
(Generally very cruel, reference to dark magic)
- Flayed
- Crushed
- Fed to Beasts
- Eaten alive by maggots
- Sacrificed in a dark ritual
- Impaled and Mounted on the Walls of [Capital]
- Cut into pieces
- Worked to death in the slave mines

# Nurniag/ Tedjin/ Rhunen (forgot religion Name)
- Hung
- Crushed
- Wheeled
- Trampled by Horses
- Quartered
- Hunted for Sport (?)

# Adunaic
(Generic "cruel" execution methods; reference to burial cult; executions at sea)
- Hung Drawn and Quartered
- Wheeled
- Crushed
- Buried alive
- Drowned
- Keelhauled
- Thrown into the Sea

# Near Haradrim
(Execution by animals, Reference to snake worship)
- Trampled by a Mumak
- Trampled by Horses
- Thrown in a pit of snakes
- Thrown in a pit of scorpions
- Offered to the Serpent

# Far Haradrim
(Execution by animals; utilize dune sea enviroment)
- Trampled by a Mumak
- Trampled by Horses
- Fed to a Giant Scorpion
- Buried in the sands
- Left to die in the Dune Sea (i.e. dropped off in the middle of nowhere to die of dehydration)

**Comment by RedArkady** [comment]
*_hanged_ rather than _hung_, when in the context of an execution. Not sure the Dúnedain would be hanging people?

**Comment by JukeJukestar** [comment]
fixed.
It is still a medieval society, and its better than burning at the stake so im pretty sure gondor would do it.
In general hanging would be pretty humane compared to most forms of execution at the time
While the Dunedain are the "good guys", they still dont share our modern values for the most part

**Comment by Remerod** [comment]
I feel that most people are en agreement of this, so i'll be moving this to non-release critical
