### ISSUE TITLE
Suggestion: Make Vengeful, Callous and Sadistic more common in Orc culture

### ISSUE THREAD

**Issue by Kyrenic** [MattTheLegoman/RealmsInExile#470]
I think that we could make the afforementioned three personality traits more common in Orc culture, since I think we see enough Orcs act in those manners that we can reasonably expect it to be a cultural thing. There are a few ways to do this:

### Add them to the Orc Society tradition
The benefit of this would be that we don't have to edit all the Orc cultures, and it's just a single edit. The downside of this is that it virtually locks out the ability for Orcs to be good, this could also be a good thing depending on your view on the Orcs.

### Add them to a new tradition
This would obviously require all the Orc cultures to have this tradition manually added, but it also gives the player the option to play as good Orcs. This is more effort, but I personally think this is the way to go.

### Concerns
My concern is that in order to make certain traits more or less common, we would need to edit some vanilla child personality trait events. This is not an issue to me, but I was told that we shouldn't mess with vanilla whenever possible. Ultimately it's up to the higher ups to decide of this is worth it.

**Comment by Kyrenic** [comment]
I agree that adding it to Orc society makes most sense, I just don't want to force the player to play as bad Orcs, if they want to play as good Orcs that should also be possible in my oppinion.

I agree that wrathful and sadistic would be better options.

**Comment by Remerod** [comment]
> I agree that adding it to Orc society makes most sense, I just don't want to force the player to play as bad Orcs, if they want to play as good Orcs that should also be possible in my oppinion.

I disagree. while this is a sandbox yes allowing player to do whatever they want at the cost of flavour is a bad idea. Orcs should be generically evil/bad. If a player want to change their character there is nothing to stopping trying to remove their traits but we should focus on making orcs as flavourable as possible to make them different from normal humans.

Here is the other issue i talked about: https://github.com/MattTheLegoman/RealmsInExile/issues/340

**Comment by JukeJukestar** [comment]
I would like to note that while making these traits more common would encourage orcs to be evil, it doesnt force them too. There will still be orcs with redeemable traits so playing a "good orc" is not impossible

**Comment by Remerod** [comment]
Since this is linked to https://github.com/MattTheLegoman/RealmsInExile/issues/340 the link to this issue will remain on that issue. And since i intend to continue working on the orcs i'll take into consideration the convo of this issue, but i think we could close this?

**Comment by Remerod** [comment]
talked with Kyrenic, will close this as it will be linked in 340
