### ISSUE TITLE
Suggestion: Give Suladan's ancestors the empire of Harwan

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#471]
Suladan's invasion of the surrounding realms is portrayed as a reconquest and reformation of the declined Haruzan.

Give his ancestors in the title history (up to around the Chelkar revolt possibly?) the empire of Harwan so it truly feels like you are reclaiming a realm your predecessors lost.

**Comment by Remerod** [comment]
Agreeing with this, some more Haruze history would be nice, and potential good to have in store for the rise of the witch king bookmark

**Comment by VectorMaximus** [comment]
Went in and added some history for this in.
