### ISSUE TITLE
Suggestion: Make all name localization keys lower case

### ISSUE THREAD

**Issue by Kyrenic** [MattTheLegoman/RealmsInExile#473]
If this was done from the beginning it would have been much easier to spot which names are and aren't localized.
I mean just look at this, it's impossible to see whether a name without special characters is localized or not:
![image](https://user-images.githubusercontent.com/43797452/184467247-abc564bf-b575-4599-89c2-dffbda0d3ffa.png)

**Comment by VectorMaximus** [comment]
Anything in these localization files is localized, though?

**Comment by jj248** [comment]
While I can see the argument, the work involved is disproportionate to the benefit and these issues are always raised in the error log anyway.

Suggest we don't fix and closing.
