### ISSUE TITLE
Should extended lifetime characters have lower lifestyle experience growth speed?

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#48]
**From the Discord:**

I’m not sure if there’s a good place for suggestions, but maybe there should be something within the Numenorean blood perks that slightly decreases lifestyle growth speed, otherwise it is pretty feasible to completely fill out several trees over a character’s lifespan, especially if they have one of the intelligent perks. In my Adunaim campaign, by the time my starting leader died I had already unlocked almost all of the stewardship and martial branches, and he didn’t even have the best perk (that Aragorn has) or any of the intelligence perks.

**Comment by Gseg** [comment]
I think we should reduce it a little. They should complete some trees, but maybe not everything

**Comment by jj248** [comment]
Putting this in the beta testing area for Red to investigate and give feedback to developers.

**Comment by RedArkady** [comment]
My instinct is to leave it as it is. The lifespan perks are one of the key fun features of the mod, and these people *should* end up much better skilled and experienced than others. I'd worry that you'd end up hampering part of the gameplay fun if you nerfed them in this way. I don't feel strongly about it though, and I can see an argument that long-lived people might become stuck-in-their-ways and stop learning after a while. Again, my instinct is to leave it be though.
