### ISSUE TITLE
Readjusting the wilderness colour when hovering over it

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#481]
So when you hover over the wilderness counties that normally are transparent they turn black (see picture bellow) 
![image](https://user-images.githubusercontent.com/79544635/185748825-4562d457-16e1-4a13-93eb-e16bf0bdeb5c.png)

This we want to change to be more transparent if possible.

> It'd be nice to look at. Ideally we'd have zero highlight

-Jamie

**Comment by Remerod** [comment]
Guess this is slightly related to https://github.com/MattTheLegoman/RealmsInExile/issues/396

**Comment by jj248** [comment]
I've raised this with Terrapass who is going to try and look at it next week. <3

**Comment by jj248** [comment]
Fixed - closing.
