### ISSUE TITLE
SUGGESTION: Northern Wastelands should have trolls

### ISSUE THREAD

**Issue by RoughlyTheSizeOfAMOROOON** [MattTheLegoman/RealmsInExile#482]
Especially in the frigid northern areas close to the mountains, I feel that there should be a Troll wasteland building in those Wastelands. Significant lack of trolling.

**Comment by JukeJukestar** [comment]
Could you be a little more specific? Maybe write out how you think the system should work?
I dont believe we have any super cold frigid areas yet. (North of Mirkwood maybe?)

There were talks about adding colonization events where local wildlife (Wolf packs, trolls, etc) hinder the process and make it a bit more difficult, or even adding those as the owners of the wilderness province if we ever get 3d models for them,
but i think the current solution works well and is quite elegant.

**Comment by RoughlyTheSizeOfAMOROOON** [comment]
Eh, just figured some extra stuff to flesh out the wastelands would be nice, since at the moment the North seems to exclusively belong to Dragons. I just figured adding stuff like Trolls or even other normal stuff like Bears or Wolves would help flesh those areas out.

If we were to do events or stuff, I figure Trolls should be pretty dangerous but not  stupidly so like Dragons would be. Maybe have Troll raids on colonization camps or whatnot, issues to do with Trolls making off with horses in the night or even people.

**Comment by JukeJukestar** [comment]
Interestingly, in our design document on wilderness, someone had the same idea independently, which i think is quite funny.

This might be better as a comment on #396 tho

**Comment by Remerod** [comment]
> This might be better as a comment on https://github.com/MattTheLegoman/RealmsInExile/issues/396 tho

indeed it would have :P but it's fine i guess
