### ISSUE TITLE
Scripted marriages when the King doesn't return

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#488]
If the Return of the King doesn't happen, the scripted characters can never marry.
We should add an event that removes the cannot_marry traits if Aragorn never returns.
Or maybe add an else_if in the return event

**Comment by Remerod** [comment]
@BriceLeduc label your stuff plz

**Comment by Vierwood** [comment]
Just add a hidden effect that removes the trait if he isn't able to return.

**Comment by jj248** [comment]
Should not have a timed event for Faramir, Eomer, Eowyn, Aragorn and Lothiriel to remove trait after 21 years if not already removed.  Trait is already removed on Shattered World start.

Ready to test.

**Comment by blackbird5598** [comment]
All characters had their cannot marry trait removed by 01/01/3021 without Aragorn ascending the throne. I believe this can now be closed.
