### ISSUE TITLE
Bug: Azumen often converts to Soryian

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#490]
When Azumen wins the reactionary Tedjin civil war, he often moves his capital to the former capital under Bor.
He then converts to Soryian because the ai likes to do that.

Worse, after he creates K_Tedja and makes it his primary title, he moves his dejure capital back to the Tedjin lands but cant reconvert/ doesnt want to.

**Comment by jj248** [comment]
I've attempted to combat this by turning the capital and a few surrounding counties in the North to Tedjin culture and faith.  Let me know if this helps with the issue.  Back to testing.
![image](https://user-images.githubusercontent.com/26043074/193816341-e8e4bf7a-abdf-4c7a-8491-c75a48b8be7e.png)

**Comment by JukeJukestar** [comment]
I tested it a bit, this fix works out fine. He no longer converts.
