### ISSUE TITLE
Make a decision to switch from any governments to elven ones

### ISSUE THREAD

**Issue by MathieuGFB** [MattTheLegoman/RealmsInExile#495]
I played in a shattered world and create a new elven character (Ghaladrim and Lomequendi) in a county in  western Andrast, on a county normally occupied by a tribal human character. Therefore, it was not possible to switch from the tribal type of government to the elven one. I guess the issue will appear for any other kind of government.

I suggest to create a special decision, tied to elven cutlures maybe, to allow elven characters to switch from any type of governments to the elven one.

**Comment by JukeJukestar** [comment]
Elven government description should also explicity state what features the government has and how it differs from regular feudal.
This is also a vanilla issue tho, because unlike ck2 the ck3 government descriptions are pretty vague

**Comment by jj248** [comment]
I've now added in mechanical support for elves in Ruler Designer.  After game start, any directly held provinces should now convert to your culture and faith and will have their holdings replaced with Elven Refuges.  You'll also get the Elven Government type.  Also, you should get an event asking you what your real age is (given you're limited to 120 in the ruler designer).

**Comment by Jauffr** [comment]
Issue can be closed. Working as intended. allowing the player to choose their age. Converting primary county to elven holdings of your culture and faith, while handing out all other counties the overwritten character held to new characters of the local culture and faith. Also changes the player to elven government type
![Screenshot 2023-02-27 183036](https://user-images.githubusercontent.com/108106660/221729716-40b4728a-7311-41d5-a01f-fabea5c47b42.png)
![Screenshot 2023-02-27 183058](https://user-images.githubusercontent.com/108106660/221729723-d27fbf1a-3263-4a60-9888-01b4f8e751e0.png)
![Screenshot 2023-02-27 183110](https://user-images.githubusercontent.com/108106660/221729729-5168e6f7-2170-48e0-9c83-4eaa4466c672.png)
![Screenshot 2023-02-27 183142](https://user-images.githubusercontent.com/108106660/221729734-2739124f-4f5e-4dc0-9b5e-8f9d2060e2ef.png)
![Screenshot 2023-02-27 183154](https://user-images.githubusercontent.com/108106660/221729739-ffbc7f36-a584-4c74-aa36-f5f47cc15eb5.png)
![Screenshot 2023-02-27 183248](https://user-images.githubusercontent.com/108106660/221729742-ef93c672-bdc2-4fc8-8077-56a68942cc5d.png)
