### ISSUE TITLE
Early on Game Crashes 2.3(2.5) compatch

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#497]
game crashes very early on sometimes even before 10 years have passed and seems to be a serious issue and needs further looking into

**Comment by Chief305** [comment]
ive experienced one ctd maybe 11 years in but i relaunched the game and didnt get anymore crashes ill keep testing

**Comment by Jermanlordy** [comment]
i did 2 testing games the other day both had crashed 1 was before the 10 year mark one before the 4 year mark

**Comment by Chief305** [comment]
i just did a test play through with gondor and i got a cdt at 3006 im gonna see if it happens again

**Comment by Chief305** [comment]
[error.log](https://github.com/MattTheLegoman/RealmsInExile/files/9561870/error.log)

**Comment by Chief305** [comment]
i got another crash in 3020. both times i had my game speed on 3 i never went any higher but its never the same dates i just get a crash a few years after 3000 then another crash after aragorn comes in the picture. ive also did two more test play throughs and its the same the crashes occure every game i run.
