### ISSUE TITLE
[KHAND] Introduce the heir

### ISSUE THREAD

**Issue by josejuanmartinez** [MattTheLegoman/RealmsInExile#498]
Jamie was working on a decision and events to 'introduce' your heir to your vassals, with possible positive and negative outcomes (based on traits and stats), so that you can potentially help secure the loyalty of at least some of your lords into the next generation

**Comment by jj248** [comment]
The basic decision should already be in place ( in lotr_khand_decisions.txt ).  This should trigger an event chain.  I'd planned for that chain to flow as follows:

Introduction -> 3 selections of events from a random chain testing the heir -> Conclusion event

- Introduction just sets up the story of what's happening.

- The random events I'd planned to start with a set of 6, with duel effects testing the heir on each trait.  Each event would have two options: take the test with the potential of success or failure, or decline the test.

- Conclusion would end the event and have a dynamic description to sum up how the heir did.

The main outcome of this chain would be to give the heir a modifier giving them a relationship bonus with the vassals to give them greater (or lower) chances of keeping the realm together on succession.  We can have different tiers of this modifier with different levels of bonus and / or malus.  e.g.:

1.    Widely Popular Heir
2.    Popular Heir
3.    Likeable Heir
4.    Uninspiring Heir
5.    Unlikeable Heir
6.    Unpopular Heir
7.    Widely Unpopular Heir

Success in each task would move them up on the ladder, failure would move down.  Turning down the challenge would move down by a lesser extent or have a chance to move down.

We can add a character flag to the heir on completion to block the decision from being taken again for that heir.

**Comment by jj248** [comment]
This is on my list to review.  Nem has some comments from a review game too.

**Comment by jj248** [comment]
This commit should bring the Introduce Heir decision for Variags to a testable state. We currently have the bare minimum number of trials in there, but as it's a pool, more can easily be added, much like the sailing events. And the framework should be clear enough to make it obvious how to structure these.

Ready to test!  The three main things that I need particular feedback on are:

1. Difficulty of tests.
2. Size of modifiers and impact on succession.
3. Overall look and feel.

**Comment by ryyde** [comment]
Only thing i can get from that decision is to do nothing or reset the cooldown (as often as i want)

**Comment by ryyde** [comment]
My opinion too lang dialogue chain when failing many times and retry

**Comment by savagesach** [comment]
the decision works as intended, I have no complaints
![image](https://user-images.githubusercontent.com/86676697/220416804-c87ab306-1313-4e59-a6df-94735c5df1bf.png)
![image](https://user-images.githubusercontent.com/86676697/220416993-63df05d1-d22b-463a-a0b9-1c0743b2e72d.png)
![image](https://user-images.githubusercontent.com/86676697/220417100-cb8b3bfa-8081-4d1d-9c75-6dacb9e53a0c.png)
![image](https://user-images.githubusercontent.com/86676697/220417201-a0e5109d-a144-4743-a310-afc092b3e5a1.png)

**Comment by savagesach** [comment]
it can be closed now
