### ISSUE TITLE
Propaganda testing

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#500]
Hello testers, could you test the propaganda events ?
Things to check :
- it should show for rulers whose faith has the Adunai Birthright tenet
- all 4 event chains should launch correctly all the way to the final night corridor event.
- bonuses/maluses should be shown and occasionally applied
- events should work in both 2.5 and 3.0 branch (prioritise 2.5 atm)

**Comment by Pepper-san** [comment]
The Thani-Hazad propaganda piece has a buff called "Historical lessons in seduction". This, like all other character modifiers, should be fully capitalized as "Historical Lessons in Seduction".

**Comment by Pepper-san** [comment]
I recall noticing a similar issue in some of the sailing modifiers as well

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/218124082-968e0996-7c90-4879-929a-0ea41199bdcb.png)

reopening this real quick because there seem to be missing events according to the error log. close if irrelevant

**Comment by BriceLeduc** [comment]
Those events are present and firing fine. It's the first of each chain, you'd notice if they didn't work
