### ISSUE TITLE
New Government(s) Issue

### ISSUE THREAD

**Issue by Vierwood** [MattTheLegoman/RealmsInExile#501]
The despotic and orcish governments, although coded correctly, aren't being given out to everyone assigned to them. For instance, only Gundabad receives the orcish government and Abrakahn doesn't receive the despotic government.

**Comment by JukeJukestar** [comment]
The governments description should also explicity state what features the government has and how it differs from regular feudal.
This is also a vanilla issue tho, because unlike ck2 the ck3 government descriptions are pretty vague

**Comment by JukeJukestar** [comment]
In Numenorean, Despotic and Elven governments, feudal contracts are bugged and dont function correctly.
"Offer Vassalization" contract options are also bugged, religious exemption is shown twice,

**Comment by JukeJukestar** [comment]
Gonna close this for now since we removed them and theres a distinct one for the new elven government.
