### ISSUE TITLE
Reintegrate Dor Rhúnen decision

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#502]
-would benefit from a new decision art background.
-consider granting 'Romendacil' nickname?

-decision should appear once Gondor controls Duchy of Dagorlad
-requires control of all of the Kingdom of Southern Rhovanion

Ready to test.

**Comment by Pepper-san** [comment]
Doesn't work for Castamiri Gondor.

**Comment by Jermanlordy** [comment]
issue can be closed descision works for all gondors and Numenor in Exile to

**Comment by jj248** [comment]
Thanks. Closing.

**Comment by RedArkady** [comment]
This was tweaked so that you only needed the _title_ of Dagorlad rather than control of the whole duchy, to avoid the Dead Marshes problem. But it's been changed to literally _holding_ the title yourself, and doesn't count if the title holder is your vassal. Can that be changed?

**Comment by RedArkady** [comment]
Fixed it. Closing again.
