### ISSUE TITLE
Elven conversion counselor task

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#504]
Counsellor task to replace faith and culture conversion tasks for elves.

Task will change faith, culture and convert holding to an elven holding when completed.

**Comment by savagesach** [comment]
I can confirm that the conversion task does work as intended
![image](https://user-images.githubusercontent.com/86676697/220264910-dd314aff-5c1d-447f-847a-f3c6a1cc3a0f.png)
before conversion
![image](https://user-images.githubusercontent.com/86676697/220264998-2a658303-5789-4ae3-bb0f-a0c29c2d799b.png)
during conversion
![image](https://user-images.githubusercontent.com/86676697/220265281-ad43a9d5-d6d5-47c9-b85a-f7d4d1505d39.png)
after conversion

**Comment by Remerod** [comment]
seems good
