### ISSUE TITLE
Sauron can lead armies

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#51]
On the subject of the Sauron leading armies question asked #discussion. I remember us mentioning it before, but do we want Sauron leading armies before he regains the One?

If we do, we could make a custom trait like "A Shadow of Malice" that disables army leading like Infirm does. Then when Sauron reclaims the one ring, the trait could be replaced by a new one that allows him to lead armies and gives him appropriate buffs.

**Comment by Gseg** [comment]
Agree. The main oddity of this does not seem to me so much that Sauron can lead armies as that Sauron participates in battles as a knight.

**Comment by jj248** [comment]
Now have Loss of the One Ring trait added which disables combat leadership.  Closing.
