### ISSUE TITLE
Ensure elves are resistant to hostile schemes

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#512]
Ensure elves are resistant to hostile schemes such as murder or kidnap plots.

**Comment by jj248** [comment]
Remove scheme blocks on elves but increase the difficulty and decrease likelihood for elves to join schemes.

**Comment by jj248** [comment]
This has now been done for all schemes, hostile and non-hostile:

- Elves have a base resistance modifier to murder and elves are less likely to join murder plots.
- Elves have a base resistance modifier to abduction and elves are less likely to join abduction plots.
- Elves have a base resistance modifier to fabrication of hooks.
- Elves have a base resistance modifier to throne claims and elves are less likely to join these plots.
- Elves are unable to be targeted by seduction and elope schemes.
- Elves are highly resistant to romance plots by non-elves.
- Elves are slightly resistant to sway and befriend schemes by mortals and highly resistant to these by evil characters.
- Elves may not be converted to witchcraft.

Ready to test.

**Comment by JukeJukestar** [comment]
Seens to be in a decent state. Reopen if its too easy to kill elves.
