### ISSUE TITLE
Feature: Eras

### ISSUE THREAD

**Issue by MattTheLegoman** [MattTheLegoman/RealmsInExile#52]
Eras and Cultural fascination gain require looking into.

Keep current eras, it’s great flavor and appropriate to our time span
Look into making Gondorian cultures innovation gain reduced, to simulate an advanced, but relatively stagnant, society.
Potential Numenorean Architecture 3 for Gondorian and Umbarean cultures, to give them something to aim for.
Minor rebalancing of what innovations the various culture groups have at 3000 T.A.

**Comment by MattTheLegoman** [comment]
#36

**Comment by MattTheLegoman** [comment]
From @VectorMaximus,
* Keep current eras, it’s great flavor and appropriate to our time span
* Look into making Gondorian cultures innovation gain reduced
* Potential Numenorean Architecture 3
* Minor rebalancing of what innovations the various culture groups have at 3000 T.A.

**Comment by jj248** [comment]
I've closed #36 as it's pretty much covered by this item if we also consider the domain limit size provided by the innovations.
