### ISSUE TITLE
Remove two test wilderness provinces in the west

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#521]
One in Old Pukel Land, one by Tharbad

**Comment by JukeJukestar** [comment]
Should also look into turning some of the ones next to the Black Gate and Northern Ithilien back into regular counties controlled by Sauron, so he can march his armies through more effectively without attrition.
Lore reason would be that by the time of the War of the Ring he has regular patrols in the are, shouldnt be much of a stretch to have some garrisons there

**Comment by jj248** [comment]
Done the first part here.  Leaving unclosed for now to give opportunity to discuss Juke's point.

**Comment by jj248** [comment]
![image](https://user-images.githubusercontent.com/26043074/207726185-8c0585c1-84ef-42e4-adeb-cc3c847c1408.png)
Out of supply doesn't seem too penal.  Regardless, there's nothing for Sauron to siege down in the area so they'd only be passing through.  Saying we don't need to change those regions, but let's monitor in play testing,  Closing.
