### ISSUE TITLE
AI likes to spam Pelargir Mariner MaA

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#53]
**From Discord:**

Is the Dev Team aware of the Pelagir Marine Spam that Gondor is doing? Entirety of Gondor in my game. Talking about 10k Stacks of Pelagir Mariners after 100 years. Possibly due to very appealing stats with 50/30 Baseline and 100 Unit size (+ Skirmisher Cost and Upkeep which is by far better than ANY Heavy infantery) they outclass every MAA except for the Fountain Guard.

Evil Forces MAA have no counter to said Pelargir Spam of Gondor btw too. Their special MAA (except for the War Mûmakil and Uruk-Hai Crossbows) do not counter skirmishers. Which leaves them with the option of building baseline archers but unless they build at least as many archer MAA stacks as Gondor does They will never win a fight, because Pelargir Marines are double as good as archers.

Current suggestion is to move them to event-only.

**Comment by VectorMaximus** [comment]
Pelargir Marines can no longer be recruited normally, and are now only available to the Sealord of Lebennin. Issue closed.
