### ISSUE TITLE
New faith icons

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#533]
@VectorMaximus to provide details of exactly what is needed, and what would be nice to have.

We should consider minor colour changes to create heresy symbols too.

**Comment by JukeJukestar** [comment]
Would be very nice to get some more, currently most of the ones we have are very Gwaithuirim.
It would be great to get at least one or two recolored Gondorian ones, since all of the ones we already have are in use by heresies.

**Comment by JukeJukestar** [comment]
Note that with the release of a recent update to vanilla ck3, we have a lot more faith icons now, a lot of which are now used for faiths

**Comment by jj248** [comment]
Agreed - suggest we deal with requests for additional icons on a request basis, rather than have a standing issue for it.  Especially as we now have AI that can help with it.  Closing.
