### ISSUE TITLE
Dol Guldur - Invasion decisions

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#538]
Dol Guldur should have decisions prompting them to launch invasions of neighboring lands.  

NOTE:  Not as OP as Abrakhan please!

**Comment by JukeJukestar** [comment]
Personally I am a bigger fan of steering the AI to agressively expand through regular CBs, as that is less prone to breaking

**Comment by jj248** [comment]
These are contained within design of #539 now.  Closing.
