### ISSUE TITLE
Heresy event can allow Erutaitale lords to Eldar

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#54]
Likely to be further reaching than just his particular permutation.

![](https://cdn.discordapp.com/attachments/778645689089392730/828563466474356786/20210404151359_1.jpg)

**Comment by jj248** [comment]
This is because both are part of the Free People's faith group.  We might be able to fix this by creating some heresies and using the strict regional heresies game rule by default.

Alternatively, we can split the Free People's group into more appropriate regional variants.

**Comment by VectorMaximus** [comment]
For now, I have disabled heresy events for all religious groups in the mod, because heresies aren't really a thing in LOTR. Might re-enable them for Men of Darkness in the future, but for now nobody should be getting them.

**Comment by VectorMaximus** [comment]
Issue closed
