### ISSUE TITLE
Dorwinion - Duchy ascension mechanic

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#546]
Add mechanic to allow complete duchies de facto under Dorwinion Kingdom but not de jure to request Realm-master to become de jure at a cost.

Rationale for this is that votes are only given for holdings in de jure Dorwinion so this translates directly to power on succession.

**Comment by JukeJukestar** [comment]
Few notes on this
- should require the duchy counties to have at least one county with dorwinrim or dorwinrim descended culture
- should require the ruler to be of a northmen faith (for example, forces of evil chars wouldnt do this. on the other hand it should be religion restricted, not faith restricted, so it still works if the dorwinion player creates a new northmen faith)
- should only be possible up to 3 times during the course of a game (so we dont have a dorwinion kingdom filling the entire map
- should require the duchy to neighbour the kingdoms dejure (so you dont have a random exclave as part of the dejure)

I'd like to link to #462 as well, I still believe that Dorwinions mechanics are unique enough to warrant its own government

**Comment by jj248** [comment]
Yes, I was going to require that the faith and culture of *all* provinces in the Duchy be the same as the k_dorwinion title holder, and that the Duchy neighbour an existing de jure Duchy.

The only thing I hadn't considered was a limit. It makes sense in principle. Though maybe I might just limit it to only be valid in a few neighbouring kingdoms, or maybe just to the duckies neighbouring Dorwinion on game start. Not sure - will experiment when implementing!

**Comment by jj248** [comment]
On reflection, I'm canning this idea.  Player can achieve similar effect by De Jure drift and Integrate Title alone and it doesn't have a solid basis in lore.  Plus, decision triggering would be complex.  Thanks for the thoughts though @JukeJukestar . <3
