### ISSUE TITLE
Easterling succession mechanics

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#548]
Lock down Easterling succession mechanics.

**Comment by Jauffr** [comment]
Medloshukain can not loose its Aristocratic elective law through succession, or through actively trying to remove it with prestige. It will not be added to new empire, or King titles you create or ones that gain independence. 
![Screenshot 2023-02-23 172714](https://user-images.githubusercontent.com/108106660/221062803-af73a956-3b04-46a0-9d77-16c4d5a63a4d.png)
![Screenshot 2023-02-23 172727](https://user-images.githubusercontent.com/108106660/221062808-9f898b78-fc47-4166-a16a-12365c72671b.png)
![Screenshot 2023-02-23 172845](https://user-images.githubusercontent.com/108106660/221062813-637381f8-6109-4a03-8022-6bba70b78e60.png)
![Screenshot 2023-02-23 173312](https://user-images.githubusercontent.com/108106660/221062820-940c07a3-80a5-4614-ac22-963a10679455.png)

**Comment by jj248** [comment]
I believe this is working as intended as it should just be for that title.  I guess I could make it possible to pick for Easterling culture characters to add to titles.

**Comment by jj248** [comment]
Broadened it to king and above and made it unique to Easterlings. Can now be removed but only at great prestige cost, rather than the silly high blockers we had before. Also gave it a name... Akhil-Shura.  Pushing back to testing.

**Comment by savagesach** [comment]
I tested it and you can remove the elective law by paying prestige, but no one is ever going to get 20,000 prestige, I highly suggest lowering that amount down to 15,000 or maybe 10,000. At the very least, I think a player should be able to remove the law, and prestige is not inherited.
![image](https://user-images.githubusercontent.com/86676697/221400554-754b6b51-abe6-4f70-be71-2e2553a86405.png)
![image](https://user-images.githubusercontent.com/86676697/221400660-024d37d7-6407-44bd-9771-67f94e4218d0.png)

Also you can still make new empires/kingdoms and not have elective succession, but I'm not sure how you want to handle that. I can confirm though that adding the akhil-shura succession law does work.
![image](https://user-images.githubusercontent.com/86676697/221401174-8f63befd-5d60-49ee-a390-1d13d5ef1f30.png)
![image](https://user-images.githubusercontent.com/86676697/221401217-41084146-916d-4074-9b62-8205197868ac.png)

**Comment by JukeJukestar** [comment]
Its completely fine that new empires and kingdoms dont have this succession law, they arent supposed to. You should be locked from forming Rhun if I remember correctly and if you conquer all of rhovanion thats gonna take a while

If you made it so new empires and kingdoms vote too, the realm would devolve into border gore as every title gets different electors.

I think 20k prestige isnt too bad, but maybe 15k is more appropriate

**Comment by savagesach** [comment]
juke, 20,000 prestige is insanely hard to get. 15,000 prestige is still a lot but it's much more reasonable. I think besides that though, easterling title mechanics are all working as intended.

**Comment by jj248** [comment]
I've tweaked this down to 15k.  Closing.
