### ISSUE TITLE
Khand - Remove succession shattering tradition decision

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#550]
Decision to remove / replace cultural tradition of realm shattering given a period of stably holding realm together.

**Comment by jj248** [comment]
Sorry for the pings @VectorMaximus, but ditto this.  What conditions were we thinking for this?  I seem to recall discussing the idea of requiring holding the empire for a certain number of generations without it being destroyed?

**Comment by VectorMaximus** [comment]
My thought had been holding the imperial title of Khand for 3 generations and a minimum of 100 years.

**Comment by jj248** [comment]
Two main things remain:
- Localisation, one for you [@VectorMaximus](https://github.com/VectorMaximus) ?
- I *believe* there's no blocker to just reform away the tradition. Two possible solutions here are to block it being removed (not sure how) or to bundle benefits in with the penalties and make an event-only tradition that removes the downsides, so it can be removed but you also remove the benefits.

**Comment by jj248** [comment]
Just pinging @VectorMaximus not as a nag, but more just so it doesn't fall off our radar to consider as this would be fairly quick to finish off.

**Comment by jj248** [comment]
Can move to testing once Vector has done his loc / considered adding an event on completion to celebrate.

**Comment by JukeJukestar** [comment]
Currently it is visible to all easterling rulers, even if they are far away from Khand. Perhaps only make it visible if at least one county in khand is held. Alternatively make it visible only for holders of upper or lower khand, or the empire.

**Comment by jj248** [comment]
Pushed a fix - the availability trigger was commented out for some reason... good spot.

**Comment by JukeJukestar** [comment]
Some notes:
- The tradition should give powerful control growth so they can recover from conquests quicker (Maybe something like +0.5 control/month in same culture counties)
- Jamie make variag rulers more angressive upon shattering

**Comment by savagesach** [comment]
I've tested the decision and I can confirm it works as intended.
![image](https://user-images.githubusercontent.com/86676697/221105165-f4ce1ce9-70c9-4fe5-9038-a94f07ee00f7.png)
![image](https://user-images.githubusercontent.com/86676697/221105227-f98234ba-9c79-4de9-8801-c21ea43107a6.png)

**Comment by savagesach** [comment]
also I can confirm that I am unable to get rid of the tradition by diverging or hybridizing
![image](https://user-images.githubusercontent.com/86676697/221106362-ef2be61e-8be7-44c3-96a3-0786dc1bed42.png)
![image](https://user-images.githubusercontent.com/86676697/221106637-942ce167-80f8-4ad8-881e-e4e31b473c83.png)

**Comment by savagesach** [comment]
I think this issue can be closed
