### ISSUE TITLE
Khand succession shatters when not independent ruler

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#551]

**Comment by jj248** [comment]
Fix pushed - ready to test.

**Comment by Jauffr** [comment]
Issue resolved. I tested killing off every single duke level Variag after giving out their lands to various characters with different opinion levels and not once did a single county split off

**Comment by Remerod** [comment]
I Trust you enough that this issue then should be resolved, closing this down, good testing @Jauffr !
