### ISSUE TITLE
Abrakhan AI imperial conquest CB is OP when heading north to unified Khand

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#553]

**Comment by JukeJukestar** [comment]
the imperial conquest is always OP haha
I still think as AI he should only get free kingdom CBs

maybe with the newly changed AI behavior we could also modify his personality traits to make him more agressive

**Comment by jj248** [comment]
This should now really be limited by the fact that AI Golden King can be recalled.  I've also put in place lore-friendly AI choices into his initial expansion based on game rules to that, if default lore-friendly rule is enabled, he will seek to subjugate the Nafarati first.

I'll also add that game rule for recalling him now while I remember.

**Comment by jj248** [comment]
I've now done this - ready to go back to testers for feedback.

**Comment by JukeJukestar** [comment]
Actually its not tied to the golden king - the black vizier can use it just as much. even then, in the case the golden king isnt recalled he shouldnt conquer Khand.
Just remove the imperial conquest please

**Comment by jj248** [comment]
Question - should the Vizier retain the CBs at all?

**Comment by VectorMaximus** [comment]
I am of the opinion that the imperial conquest CBs be disabled.

**Comment by jj248** [comment]
Disabled - can we close?

**Comment by Jauffr** [comment]
I have not seen any AI using the imperial conquest in my observer games, and I can not use any empire invasions on my own either. Khand is safe from being gobbled up by Abrakhan... That quickly at least
![Screenshot 2023-02-23 181237](https://user-images.githubusercontent.com/108106660/221067730-5434caa6-fb02-4b2e-8f47-b304f5cb5e3d.png)

**Comment by jj248** [comment]
Great - will close.  Though the mechanics / decision structure will probably be revisited, at the very latest when Khy is added.
