### ISSUE TITLE
Final review of scripted illustrations

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#555]
Ensure character backgrounds are appropriate for each culture.

**Comment by BriceLeduc** [comment]
Two things :
- Elrond has an Iberian court backgriynd for some reason (minor)
- We need a Rohirrim throne room illustration. The current norse temple illustration is very bad imo. Especially since it's from vanilla and everyone knows it's a temple

**Comment by BriceLeduc** [comment]
The scripted illustrations are in a satisfactory state, ready for release
