### ISSUE TITLE
3.0 Dejure duchy density 

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#568]
A few of the duchies are still massive, such as Undeeps (8 counties); Talath Harroch (9 counties) and should be split up.
(Drownholt, the duchy neighbouring undeeps, only has 2 counties for comparison)

Compared to the rest of the map, there is generally also a very large ammount of large new duchies (with 6 or 7 counties). These are usually fine as we also see them in vanilla, but if you compare the average county density of rhovanion and khand to the ones in gondor or harad, the difference is very apparent.
On the other hand, there is also a large ammount of duchies with very few counties (only 2 or 3)

Naturally i had to calculate average county per duchy density for all areas because i am something of a math nerd

# DUCHY DENSITY

## Anadune + Dune Sea + Haradwaith + Nafarat

44+77+68+75=264 counties
13+20+19+17=69 duchies
**Average 3.83 counties per duchy**

## Bellakar + Bozisha-Miraz + Thani-Hazad

92+107+31=230 counties
21+23+7=51 duchies
**Average 4.51 counties per duchy**

## Gondor + Mordor + Enedwaith + Calenardhon

101+50+53+25=229 counties
28+13+16+5=62
**Average 3.69 counties per duchy

## All pre-3.0 Empires combined

729 counties
182 duchies
**Average 4.00 counties per duchy**

## Laurelindorenan + Nan Anduin + Greenwood + Rhovanion + Rhun + Khand

11+30+58+132+47+65=343
3+8+12+26+10+13=72
**Average 4.76 counties per duchy**

# Conclusion

A difference of 0.76 may not appear to be very large, but it is a noticeable difference between the new areas and the Pre-3.0 areas.
Overall, most of the duchies in 3.0 are either small or very large, with too few medium sized ones

**Comment by JukeJukestar** [comment]
just for comparison, Undeeps is the same size as andrast

**Comment by VectorMaximus** [comment]
We have now split up the Undeeps and Talath Harroch.

**Comment by jj248** [comment]
I've made some additional tweaks here and there to reduce the number of baronies in a number of counties that were just too large.  Naturally, this will skew our ratios upwards and increase the average number of counties per duchy.

Now we can certainly go in and split up duchies a little more, that's no great problem.  But we should first establish whether this a problem to begin with and, if so, what is a more desirable ratio and which areas do we want to split down.

Details below:

**All v3 Additions**
70 Duchies
344 Counties
**4.9 Counties per Duchy**

**South Rhovanion**
7 Duchies
31 Counties
**4.4 Counties per Duchy**

**Usrievar (aka Easterling Kingdom)**
5 Duchies
29 Counties
**5.8 Counties per Duchy**

**Ewathavuld**
5 Duchies
26 Counties
**5.2 Counties per Duchy**

**Dorwinion**
7 Duchies
32 Counties
**4.6 Counties per Duchy**

**Nelornieth**
5 Duchies
18 Counties
**3.6 Counties per Duchy**

**Logathavuld**
3 Duchies
19 Counties
**6.3 Counties per Duchy**

**Dale**
6 Duchies
26 Counties
**4.3 Counties per Duchy**

**Lasgalen**
6 Duchies
30 Counties
**5.0 Counties per Duchy**

**Angaladh**
3 Duchies
16 Counties
**5.3 Counties per Duchy**

**Dol Guldur**
3 Duchies
26 Counties
**4.3 Counties per Duchy**

**Anduin Vale**
4 Duchies
19 Counties
**4.8 Counties per Duchy**

**Lothlorien**
3 Duchies
11 Counties
**3.7 Counties per Duchy**

**Anneithel**
3 Duchies
11 Counties
**3.7 Counties per Duchy**

**Gundabad**
1 Duchy
3 Counties
**3.0 Counties per Duchy**

**Upper Khand**
5 Duchies
21 Counties
**4.2 Counties per Duchy**

**Lower Khand**
4 Duchies
26 Counties
**6.5 Counties per Duchy**

**Comment by jj248** [comment]
See discussion on Discord here: https://discord.com/channels/751097183448727552/1050052659194900491/1050052659194900491

Also see detailed analysis and comparison vs vanilla here:
https://docs.google.com/spreadsheets/d/1JY0NW6aV-4ObQuhGmXXxAXHoea2XFfkA/edit?usp=sharing&ouid=103572386438571462300&rtpof=true&sd=true

Moving to testing to get feedback in proper playtesting.

**Comment by JukeJukestar** [comment]
Think we can close this, its in a good state rn
