### ISSUE TITLE
Black Horseman claims Upper or Lower Khand

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#569]
The Black Horseman nazgul has a claim on khand, as well as the kingdoms of upper and lower khand. Sauron personally wont press it because Khand is his tributary, but the witch king or the black horseman himself as an adventurer can claim khand and then swear fealty to sauron right after. 

This is unintended behavior and could be remedied by removing his claims

**Comment by jj248** [comment]
Would changing these to unpressed claims remedy this @JukeJukestar?  The reason I put the claims in was as a lore pointer to show that he once ruled Khand.  Not worth sacrificing game balance for, but would be good to retain if we could.

**Comment by JukeJukestar** [comment]
Havent seen it happen anymore, if it does do reopen.
