### ISSUE TITLE
The Ages of Arda

### ISSUE THREAD

**Issue by VectorMaximus** [MattTheLegoman/RealmsInExile#57]
Currently, we are missing most of the years of the Ages of Arda, with most of the Years of the Trees and Lamps missing. We should fix this sooner than later, because the amount of things to adjust will only increase.

**Comment by VectorMaximus** [comment]
The years, separated into ages, look like this 
Taken from the Annals of Aman, the Histories of Middle-Earth

1 - 33,537: The Years of the Lamps
33,538 - 47,909: The Years of the Trees
43,549: Our current year one
43,599: The Awakening of the Elves
47,910 - 48,500: The First Age of the Sun
48,501 - 51,942: The Second Age of the Sun
51,943 - 54,943: Third Age 3000, our start date.

**Comment by jj248** [comment]
Decision made not to implement.
