### ISSUE TITLE
Strange Succession Gender Law Requirements

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#571]
Faithwise, Realms allows for five different gender doctrines instead of the vanilla 3. Some of these do not work as intended and someone needs to take a look at the entire system, because large parts of it need an overhaul.
Cultural gender doctrines (such as matriarchal) added by RC also work strangely, especially in combination with opposing faith doctrines.

# Gender Succession Law Issues
## Male Dominated
Allows for:
- Male Only
- Male Preference

## Male Orientated
Allows for:
- Male Only
- Male Preference
- Female Preference

(Should not allow Female Preference)
(Should allow Equal)

## Equal
Allows for:
- Male Only
- Male Preference
- Equal
- Female Preference

(Should not allow Male Only)

## Female Orientated
Allows for:
- Male Only
- Male Preference
- Female Preference

(Should not allow Male Only and Male Preference)
(Should allow Equal and Female Only)

## Female Dominated
Allows for:
- Equal
- Female Preference
- Female Only

(Should not allow Equal)

# Conclusion
The issues likely arise from RCs changes to the way gender laws work.
They have to be symmetrical and also logically plausible (For example, "Female Orientated" disallows female only and equal but allows Male only and male preference)

Martial Customs (set during culture divergence or reformation, **choices depend on succession gender law, not faith gender doctrine**) appear to be working fine. They are asymmetrical, but I believe this is intended by PDX since female only armies dont make much sense logically and should only be avaiable to players going "full amazon" for RP reasons

**Comment by Pepper-san** [comment]
Fixed. The orientated doctrines do NOT allow Equal succession after discussion with Vector (It would make the Equal Succession cultural tradition entirely redundant, and doesn't match what those doctrines mean to represent). Aside from that, gender laws now are symmetrical and make sense, the only exception being in the event of cultures with the matriarchal tradition, which will override religion gender doctrine and allow the same laws as female dominated. Can probably be closed.

**Comment by Jermanlordy** [comment]
yea i tested aswell and its fixed for me to

**Comment by JukeJukestar** [comment]
Closing it then.
