### ISSUE TITLE
Leofring rulers have the wrong faith, are partially feudal

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#572]
# Wrong Faith Rulers
![image](https://user-images.githubusercontent.com/76008882/196785568-08e33736-998a-4d76-96fb-b10cd2122686.png)

All of the Eastern Leofring rulers are of the Fey Court, but rule over Withered Court counties. They should be changed back to the correct faith. (With the High Chief of Drownholt being Withered Court, but also ruling a Fey Court county.

# Strange County Behavior
![leofr](https://user-images.githubusercontent.com/76008882/196786812-fc457d0f-cbee-43e4-8f13-4ff5d239769d.png)

Some of their counties (shown here) are supposed to be held by tribal rulers, but have castles in the primary holding slot, which makes their rulers flip to feudal on day one. There are tribes in the secondary holding slots held by barons.

**Comment by JukeJukestar** [comment]
I noticed that the independent orcs in Mirkwood have the same problem, their holdings are tribal but their lord is feudal.
It doesnt flip to tribal at game start because feudal lords can hold tribal holdings of their culture

**Comment by jj248** [comment]
Pushed a fix for all of the points raised above.  Barony density is still too high in the Undeeps, but that's a separate issue.  Back to you to check @JukeJukestar .

**Comment by JukeJukestar** [comment]
fixed
