### ISSUE TITLE
Post-Ruler Designer event to age elves

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#574]
The current upper limit of ages for Barbershop characters is 120 years, which is far too young for most elves.

We should use an after-barbershop game start on action to fire an event for the player character that will give them the option to choose which age they were born in and apply an appropriate randomly assigned set_age that puts them within that time period.

**Comment by JukeJukestar** [comment]
You mean the Ruler Designer, barbershop is the in game menu that lets you set your clothes and hair

**Comment by jj248** [comment]
Done as part of #495 .  Closing this one.
