### ISSUE TITLE
Bug: Mercenary companies submit to Abrakhans vassalization request

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#575]
Title says it all. When Abrakhan demands an area to become vassalized, local merc company rulers often submit as well.
Only tested in public version, but I am relatively sure that nobody touched Abrakhans events in a while so it should apply to the master as well.

**Comment by jj248** [comment]
This shouldn't happen any more.  I've tidied up all the triggers but they'll need to be tested to make sure that the submission demands are still all being sent correctly.
