### ISSUE TITLE
Bug: Nobody can grant out baronies due to bugged elven refuges

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#576]
![image](https://user-images.githubusercontent.com/76008882/198103939-f7e3837f-af27-41ba-a6ee-cf83d8ad06ae.png)

Nobody can grant out any baronies, this appears to be because of the recently added elven refuges.

**Comment by jj248** [comment]
Should now be fixed.  Ready to test!
