### ISSUE TITLE
Bug: The decision to convert to local culture has disappeared entirely.

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#577]
This is a core gameplay mechanic. Not much more to say, really.
I checked it with several different characters and Pepper was also able to replicate the issue.

**Comment by jj248** [comment]
Ready to test - mostly just need to make sure that conversions between races are not possible, so if we can try all the different permutations, that should cover us!

**Comment by JukeJukestar** [comment]
Works as intended. Spess bless,
