### ISSUE TITLE
Nerf Dales economy

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#578]
# Dale's Economy
Dale currently has a very strong economy, which should be nerfed a bit. As a player its pretty easy to stack tax buffs and building cost reductions (The king is a pretty good steward) and since they have lay clergy you can quickly get to ~12 holdings, which you can then upgrade heavily to snowball fast.
Militarily, their MAA arent extraordinarily powerful, but they are quickly able to afford a lot of them.
For comparison: Currently their economy is comparable to Rây's, exept that they are in a far better political position with no enemies nearby and can thus focus on making that sweet cash

# How?
- A start would be to change the effects of the dwarven trade modifier to no longer give +5 gold/month. It could instead just give a flat increase to development growth and reduce holding construction cost.
- Perhaps the king could be nerfed a bit aswell
- If this makes sense lorewise, lay clergy could also be changed to theocratic so you can no longer hold temples

**Comment by jj248** [comment]
Have commented out the +5 gold / month modifier as agree, it's OP.  Will reconsider as part of #544 .  Closing.
