### ISSUE TITLE
Upper Anduin/ Vale map overhaul

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#583]
For more info see the suggestions forum in the discord. Feel free to assign yourself if you want to do this!

<details>
  <summary>Current map setup</summary>
  
![currentcale](https://user-images.githubusercontent.com/76008882/203769785-d9f4bc49-c597-4813-9e09-0840fb091aba.png)

</details>

<details>
  <summary>RedArkady's proposed version</summary>
  
![image](https://user-images.githubusercontent.com/76008882/203769911-968501bf-e1d4-464b-bd20-5d1a6c5c4cd7.png)

</details>

# Map Setup

<details>
  <summary>My sketch based on RedArkady's</summary>
  
![valesofanduin](https://user-images.githubusercontent.com/76008882/203770011-164c5ef6-9529-4879-8933-bd8a03c327f7.png)

</details>
The Anduin should be a major around the area of the vale, but a minor one north around Dol Guldur and the Framlings.
It is unclear where exactly it should transition into a minor river in the south, decide this while mapping

## Important Notes
- Avoid changing the province/ title setup if possible
- Have a (primary) holding at each side of the fords, so defenders have an advantage
- Add more fords if needed, gameplay goes before lore here
- The Carrock should have a ford on its eastern bank
- Dol Guldur and Lorien have to be able to reach eachother without marching north to the Old Ford
- Should stay a minor river around the Undeeps (as the name implies)
- Maintaining a foothold on both sides of the River shouldnt be too difficult for the Beornings, but having a Realm that is split along the river (Like Anorien/ Ithilien) should also be possible (If, for example, mountain orcs take over the west)

**Comment by jj248** [comment]
One thing I'd note on this is that I'd far prefer there to be a _single_ transition from major to minor river, and for us to add crossings where needed, rather than to chop and change as you go upstream.

**Comment by MattTheLegoman** [comment]
Jamie, I'll make sure you can look at it beforehand. But anyone can feel free to take over in terms of changing the provinces and titles. I'm still working on the terrain so do not edit that.

**Comment by jj248** [comment]
This is ready for tester feedback.  Pinging @JukeJukestar and @RedArkady as folks with a vested interest in this issue.

**Comment by JukeJukestar** [comment]
Looks good, seems to be working. Couldnt find any broken locators or anything like that.
