### ISSUE TITLE
Assign unlanded Nazgul to courts, prevent them from wandering off

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#584]
In a recent Saruman testing game I got one of the Nazgul in my court.
If unlanded characters dont find anything to do they tend to go wandering off. This should be prevented for Nazgul.
They should also be assigned as courtiers at game start, currently they have a chance to be guests instead so you have to spend precious cash hiring them.

This should also account for Nazgul getting unlanded (Ithilien reconquered, Dol Guldur destroyed, Abrakhan fallen etc)

**Comment by jj248** [comment]
I've done this, putting them all in Sauron's court for now and @VectorMaximus can move some if he wants.  I've also deposed Khorahil as discussed and replaced him with a random Nurniag - we may want to do a bit more work on his character though, as he's super basic right now.  Might be one for @JukeJukestar as he's enjoying Character History right now.

Still - effectively the main thrust of this is done, so closing.
