### ISSUE TITLE
Text problem

### ISSUE THREAD

**Issue by vackrich** [MattTheLegoman/RealmsInExile#586]
When I started playing ck3 with this mod, the text or ui disappear. Is there any possible ways to fix this and does anyone have the same problem?

**Comment by BriceLeduc** [comment]
This is not an issue, incorrect installation

**Comment by BriceLeduc** [comment]
Are you a tester ?

**Comment by vackrich** [comment]
> Are you a tester ?

Not really sure what you mean by that

**Comment by BriceLeduc** [comment]
This is not an open github : it's developping platform for the team, including testers and developpers. You should get the public version from Steam

**Comment by vackrich** [comment]
I don't  think it would be possible for me to play with this mod because I didnt buy ck3 from steam
