### ISSUE TITLE
"Convince De Jure Territory" councillor action can be used to get back Ithilien

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#589]
![image](https://user-images.githubusercontent.com/76008882/207944711-a8e171ac-399b-4acc-96b8-dda92bf21f98.png)

![image](https://user-images.githubusercontent.com/76008882/207944774-22fb8fba-d473-478d-9cc4-e2bb506a819b.png)

This can be used to gain back Minas Morgul for example.

Solution? Unsure. Maybe make it unuseable on Evil faiths?

**Comment by jj248** [comment]
I've added an additional check to prevent convincing those with faith hostility levels of hostile or evil.

![image](https://user-images.githubusercontent.com/26043074/213183925-a623eae2-ab02-41fd-9e18-d0acb41c229d.png)

**Comment by JukeJukestar** [comment]
Seems to be working, Reopen if you find a problem with it
