### ISSUE TITLE
No Vanilla Tenets are avaiable during faith reformation

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#592]
As the title says, none of the vanilla tenets are avaiable during faith reformation. They do not show up as a choice and are marked as "not allowed" if they are already in use

**Comment by jj248** [comment]
Not sure I can replicate this... can you check it's still an issue @JukeJukestar please?
![image](https://user-images.githubusercontent.com/26043074/213220788-4db9f4c6-2ab1-4001-8656-f19e5c5adae1.png)

**Comment by JukeJukestar** [comment]
Works again, closing.
