### ISSUE TITLE
Bug: Old Isengard events cause tons of errors

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#594]
![image](https://user-images.githubusercontent.com/76008882/210140939-491ff5ae-0234-4b99-b48f-68cf01145737.png)

This is from my error log. There seem to be a ton of errors related to Sarumans stuff, Jamie told me its probably part of the old events.

**Comment by MattTheLegoman** [comment]
They need to be added back in.

**Comment by jj248** [comment]
Will deal with this as part of #612.  Closing.
