### ISSUE TITLE
Tie settlement inheritance to main title

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#601]
Settlements can be inherited by random heirs at the moment, the game treats them as standard counties.
They should be tied to the main title's succession to avoid rulers ruling over a single settlement, and not having the resources to finish the colonisation.

**Comment by Jauffr** [comment]
Issue can be closed. settlements are always given to the new holder of the primary title. This includes Dorwinion and Easterling elections. No more situations are 
![Screenshot 2023-02-23 173603](https://user-images.githubusercontent.com/108106660/221063321-4abf0646-eb62-4382-a382-eefc44d5837e.png)
![Screenshot 2023-02-23 173648](https://user-images.githubusercontent.com/108106660/221063331-645f8e06-64c2-4297-a69f-82a080e116e2.png)

**Comment by Remerod** [comment]
Before we close this

> They should be tied to the main title's succession to avoid rulers ruling over a single settlement, and not having the resources to finish the colonization.

has this been tested in the case for colonization? I mainly ask because i didn't see a picture or sentence reflecting this (since other pictures where posted)

**Comment by Jauffr** [comment]
Picture one shows the dead marshes still held by Medloshukain after the title was taken from my family. Picture two shows the same with Vardigathod as Dorwinion. The county on the western edge of dorwinion is a new colony

**Comment by jj248** [comment]
Closing. Thank you kindly.
