### ISSUE TITLE
Dorwinion - Men at Arms

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#606]

**Comment by Vierwood** [comment]
**Divide & Conquer Dorwinion Units**

Note: these are only a few of the ones I think would suit Realms best. 

![20230114135107_1](https://user-images.githubusercontent.com/26224955/212493697-bf0e6c5c-05f5-4608-bbed-710575373813.jpg)

"Regent Bowguard" | Crossbowmen

![20230114135057_1](https://user-images.githubusercontent.com/26224955/212493735-6c94d669-f86f-4751-bc63-904c90a6fa04.jpg)

"Vineyard Bowmen" | Archers

![20230114135042_1](https://user-images.githubusercontent.com/26224955/212493763-3f94f47e-9314-493b-bcb9-41110bd0fed6.jpg)

"Thorn Guard" | Pikemen 

![20230114135037_1](https://user-images.githubusercontent.com/26224955/212493773-54066133-0081-45ba-9705-ea968852ceea.jpg)

"High Paladins" | Heavy Infantry

![20230114135029_1](https://user-images.githubusercontent.com/26224955/212493828-0678ddb0-42e4-4e0f-bbfd-20dbd3eba98c.jpg)

"Vintner Court Knights" | Heavy Infantry

![20230114135020_1](https://user-images.githubusercontent.com/26224955/212493848-3d4b5d46-757c-45a7-8461-eb375136ae7f.jpg)

"Vintner Court Paladins" | Heavy Cavalry

**Comment by jj248** [comment]
Unique tradition and 3 MaA added.  Ready to test. Also pinging @Vierwood as a Dorwinion fanboy... 😃 
![image](https://user-images.githubusercontent.com/26043074/212675372-fc605bb8-26a6-4ef8-8866-aea6dca64df1.png)

**Comment by Remerod** [comment]
So to make sure, what is it that needs testing?

* If the MAA works/apear correctly?

* whatever they fit the region correctly, say rp theme vice and with modifiers and so on?

* if the MAA is balaneced? 

or all of the above?

("ready to test" is not the best describing way to ask for a specific testing-thing :P )

thank you in advance for answering my question

**Comment by jj248** [comment]
> So to make sure, what is it that needs testing?

Apologies, I thought this one was pretty self-explanatory:

- [ ] MaA are present and available only to those with the tradition.
- [ ] The tradition is fully localised with no writing issues.
- [ ] Tradition effects are balanced (should be as we addressed its balance in another issue!).
- [ ] MaA feel balanced.
- [ ] MaA art is appropriate / passable.

**Comment by Jauffr** [comment]
1. The MaA are available to be recruited by those intended. Including being given as starting units
2. The tradition is fully localized and conveys exactly what it is designed for
3. The tradition's effects are balanced and are perfect for enhancing the feel of and playstyle for Dorwinion. The only change I would suggest is to have it increase the vassal limit, to assist the feel of having many squabbling vassals. However the Winelords already have a boost to their vassal limit, so it is merely a personal opinion
4. The MaA look and feel balanced, as well as being useful for the relevant region of the map. Their terrain bonuses and stat dispersion perfectly display their roles in Dorwinion society and in the military, as well as what terrain and foes they each would be expected to encounter. The Thorn Guard's bonuses in desert hills and forest is an excelent way to convey their intended role as caravan guards traveling through the woods to the west and the deserts of  Rhun
5. The art is incredible for the Vintner Court Paladins and causes me to recruit them more often just to see the art! The other art is Vanilla, yet it is functional with no bugs. I could always boot up Divide and Conquer for some options for their art

**Comment by jj248** [comment]
Great, thanks!  I added a minor vassal limit buff as suggested in 3.  Otherwise, I think I can close this.
