### ISSUE TITLE
Mumakil Mercenaries

### ISSUE THREAD

**Issue by wFredsch** [MattTheLegoman/RealmsInExile#608]
Adding Haradrim Mercenaries with Mumakil.

**Comment by wFredsch** [comment]
@VectorMaximus what should I add for restrictions?

**Comment by VectorMaximus** [comment]
Well, I'm unsure what restrictions there are. So, as things stand, you can recruit maximum of 50 Mumakil (1 battalion with five levels, ten Mumakil per level), with maxed out everything, as a landed ruler. Mercenaries should also hard cap out there as well. Additionally, say there are 10 Haradrim mercenary companies. Only say one in ten should be fielding Mumakil.

**Comment by jj248** [comment]
Is this even possible?  I'm not sure what we're looking to achieve here.
