### ISSUE TITLE
Elves can die of stress

### ISSUE THREAD

**Issue by Pepper-san** [MattTheLegoman/RealmsInExile#609]
![image](https://user-images.githubusercontent.com/115768993/212773196-f1d2fb29-a9a4-453a-aafc-4b13e10980c0.png)
Currently it is possible for Elves to die of stress. This shouldn't be happening, rather, it should either send them to the undying lands or the event just shouldn't trigger.

**Comment by jj248** [comment]
Should no longer be possible.  @VectorMaximus is also adding more stress reduction modifiers to immortal races to effectively make stress a non-issue for them regardless for now, until we have more elf-friendly stress breaks and traits.

**Comment by JukeJukestar** [comment]
I think you should focus on getting elf friendly stress stuff in instead of nerfing their stress.
Stress is the one character mechanic from vanilla I can see elves experiencing (seduction, disease, murder etc are all kind of out of the picture)

**Comment by jj248** [comment]
Totally.  It's just a pragmatic interim solution.

**Comment by JukeJukestar** [comment]
We should also disable the "heresy" option in stress breaks

**Comment by jj248** [comment]
> We should also disable the "heresy" option in stress breaks

Wait... we haven't already?  Have you seen this happen?

**Comment by JukeJukestar** [comment]
Nope, just something we should consider - can you check if it is disabled?

**Comment by savagesach** [comment]
I've given galadriel level three stress and she never got a stress break from it. I think it's safe to say that elves can no longer die from stress
![image](https://user-images.githubusercontent.com/86676697/221248340-9bc67aa3-fe2b-4301-abc4-746a8724994a.png)

**Comment by savagesach** [comment]
I think this issue can be closed
