### ISSUE TITLE
AI doesn't take final step to convert settlements to full holdings

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#616]

**Comment by jj248** [comment]
Should be fixed in latest commit.  Ready to test.

**Comment by Jauffr** [comment]
AI can and will finish colonizing a county. They will take the final cost to upgrade to a standard holding 
![Screenshot 2023-02-23 174813](https://user-images.githubusercontent.com/108106660/221064821-10796055-a005-44ab-b4e9-330f0bd0a858.png)
![Screenshot 2023-02-23 174858](https://user-images.githubusercontent.com/108106660/221064827-0d7ee7ac-7bdd-4eef-a416-be555dae4124.png)

**Comment by Remerod** [comment]
seems to be working fine, nice testing 👍

**Comment by jj248** [comment]
Bravo - another one bites the dust.
