### ISSUE TITLE
Offer Vassalization is bugged

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#619]
![image](https://user-images.githubusercontent.com/76008882/214825988-394b30f7-faa4-46a4-b0ec-ef7e7aad5346.png)

When offering vassalization to someone, there are two choices for "religious excemption"

![image](https://user-images.githubusercontent.com/76008882/214826058-736275ca-78c0-404f-b11e-2698969baf82.png)

The values also seem to be off.
In this example, Dorwinion offers vassalization to a pantheon of rhun (men of darkness, a people apart, hostile) duke and he easily accepts. Will have to be cross-referenced with vanilla, but the negative faith penalty seems really low while the religious acceptance buff seems really high:

For a faithful liege, heres the acceptance chance reductions:
- 10 with men of darkness, echoes of the ainur (astray)
- 20 with men of darkness, a people apart (hostile)
- 120 with men of darkness, dominion of the dark (evil)

+60 for religious excemption contract, meaning that vassalizing rulers of a foreign faith is actually easier than vassalizing regular rulers! I suspect this is a leftover from the removed governments, since they originally bugged feudal contracts.

**Comment by jj248** [comment]
Should be fixed, ready to test.

**Comment by JukeJukestar** [comment]
Seems to be working as intended. Religious Excemption gives +60 acceptance, which I think is the same as vanilla
