### ISSUE TITLE
Uruk MaA

### ISSUE THREAD

**Issue by isam0** [MattTheLegoman/RealmsInExile#62]
* balancing
* check art
* Matt prefers to make comparisons with base game MaA to make compatching easier. Please consider this.

**Comment by jj248** [comment]
Related issue in #111 with Orc Warriors and Archers not appearing for Orcs.

**Comment by jj248** [comment]
Orcs are still getting access to non-orc units like Armoured Footmen and Armoured Horsemen... presumably there should be orc equivalents here.

Also, the stats of some of these units feel particularly weak.  Like the Smakurr for example.

Also also, general balance seems off.  Why do the Orcs have three units of skirmishers for example with not much difference between them?

![image](https://user-images.githubusercontent.com/26043074/122557643-f7d8f600-d034-11eb-9647-8d2f29389beb.png)

**Comment by JukeJukestar** [comment]
Closing this ancient issue, refer to #201 #607 and similar ones if we find any issues with orc MAA.
