### ISSUE TITLE
Upgrading wilderness destroys normal buildings

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#620]
It is possible to build normal holding buildings (e.g. palisade) in a wilderness settlement. However, these are destroyed when upgrading to a tribe holding. I think there's an argument that you *should* be able to build normal buildings, but these should not be destroyed on upgrading.

**Comment by jj248** [comment]
These aren't normal holding buildings.  These are specific cheap and cheerful temporary settlement buildings to make them less crappy while you wait for them to develop.

**Comment by jj248** [comment]
WAD - closing.
