### ISSUE TITLE
Remove Anduin river crossing south of Argonath

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#629]
![image](https://user-images.githubusercontent.com/76008882/215478885-5ef76e52-a03d-4154-b0d7-bcc3ea039fcb.png)

Mordor will often invade Rohan instead of gondor because they share a border once mordor colonizes Nindalf.
if the river crossing between b_mistham and b_raunas is removed we wont have this issue anymore.
It will also solidify the front in ithilien further, since Sauron will focus on it more.

**Comment by jj248** [comment]
I'm not averse to the idea, it's certainly a simple solution.

@VectorMaximus / @RedArkady - does it pass the lore sniff test?

**Comment by RedArkady** [comment]
I think it probably represents the portage that would have existed on the Anduin river route. But I tend to agree it's a gameplay problem, and arguably doesn't make much sense at our start date. It's not like there's a functioning ferry system.

**Comment by RedArkady** [comment]
The more I think about it the more I think we scrap it - it would be madness to take an army that way given the Nindalf and Dead Marshes.

**Comment by jj248** [comment]
Yup - agreed.  Let's do this.

**Comment by jj248** [comment]
I've now removed the crossing at Rauros.  Closing. 
![image](https://user-images.githubusercontent.com/26043074/215733077-ad805cae-8b95-433d-ac7c-7204d0f99ad3.png)
