### ISSUE TITLE
Cavalry Leader and Outrider Leader Traits are inheritable

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#630]
This is a leftover from 1.0

- Make it so they arent inheritable
- Remove Outrider Leader entirely as its reduntant and shares almost all effects with Cavalry Leader
- Add a random event for Eotheod characters with the option to get it
- Add it to the commander trait pool.
- Add it as an option for Strategist Lifestyle random event

**Comment by jj248** [comment]
Agree and have done the following:

- Removed any genetic element (that was odd)
- Removed Outrider Leader and replaced any existing with Cavalry Leader
- Should now be available as a commander trait and obtainable like other commander traits for those with the Horse Lord culture trigger.

I have not added any event just yet.  Hopefully Eotheod characters should just get this naturally like other commander traits.

**Comment by JukeJukestar** [comment]
Working as intended.
Random commanders can generate with it, its not too OP I dont think.
The reason why an event to get it would be good is because while random characters generate with it, players can only get it if we actually add it as an option. (Same with orc commander traits)
