### ISSUE TITLE
Puppet in Rohan decision bugged

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#635]
Saruman / Isengard's "Install a puppet in isengard" decision is buggy.

- You can just wait until everyone is dead and then use the decision
- it doesnt seem to check if the rohirrim stil control the kingdom, it could be part of gondor or mordor or conquered by a scorpion riding Qarsag adventurer by this point

![image](https://user-images.githubusercontent.com/76008882/215795321-11f03bdb-1115-42c7-bda3-496e5e0243ee.png)

**Comment by jj248** [comment]
Will deal with as part of #536 - closing.
