### ISSUE TITLE
Saruman can easily get rushed by Rohan

### ISSUE THREAD

**Issue by savagesach** [MattTheLegoman/RealmsInExile#651]
Since Saruman no longer has a strong hook on Theoden, it's possible for Theoden to fabricate a claim and kill Isengard within the first few years of the game. There should be some kind of truce like with mordor and gondor to prevent this
![image](https://user-images.githubusercontent.com/86676697/217320786-29e2e991-878e-4184-a424-71c78830c39d.png)

**Comment by JukeJukestar** [comment]
We could even make isengard a protectorate of rohan until they attack them if thats possible.
that way rohan would protect them from any dunlendings who want to rush him (players cough cough)
However, I think a mutual truce is also good for at least the first few years of the game

**Comment by jj248** [comment]
Mutual truce implemented: 
![image](https://user-images.githubusercontent.com/26043074/217649422-7b897500-b308-45aa-b440-0386e424ea91.png)

Protectorate doesn't really make sense from a lore perspective....  Over to testing.

**Comment by savagesach** [comment]
so I noticed an interesting side effect of the 10 year truce, isengard can no longer raid rohan llike they used to
![image](https://user-images.githubusercontent.com/86676697/220975647-be01d197-0d57-44d4-8ba0-2ed3e36a3f50.png)

**Comment by jj248** [comment]
The price we pay for progress... I could always make it a one-way truce I suppose.

**Comment by savagesach** [comment]
besides that, the truce worked as intended in my playthrough. I've also run several observer games and isengard never got attacked early by rohan. I think this issue can be closed
