### ISSUE TITLE
Galadriel turns neighbouring dukes into protectorates

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#659]
This has been a problem for a while. Galadriel will turn nearby rulers into protectorates sometimes, which makes it near impossible to conquer them even as good aligned characters like Grimbeorn. It makes sense for her to protect them against Dol Guldur, but she shouldnt intervene in human conflicts I feel.

Maybe it would be possible to make a new type of protectorate for elves that is only defended against Forces of Evil attackers?
Or maybe just make it so she gets a decision to offer help if good/ neutral humans bordering her are attacked by Dol Guldur

**Comment by jj248** [comment]
For now, I will make it so that AI elves do not offer Protectorates.  We can tweak this logic to be more complex if desired, but adding a whole new protectorate type is beyond the scope of v3.  Let me know your thoughts.

**Comment by JukeJukestar** [comment]
Sounds good.

**Comment by JukeJukestar** [comment]
She dejure-claims Parth-Celebrant sometimes, but I think we reduced her agressiveness a bit. Closing for now.
