### ISSUE TITLE
Destroy Gondor CB

### ISSUE THREAD

**Issue by VectorMaximus** [MattTheLegoman/RealmsInExile#66]
* Destroy Gondor CB

**Comment by RedArkady** [comment]
This works really well. There's arguably a balancing issue, in that Mordor can use gold from tribute to overtake Gondor very quickly and destroy it in two short wars. But that's probably quite true to lore. Perhaps it *should* be easy for a human player to do that.

**Comment by VectorMaximus** [comment]
That's good to hear. Sauron is supposed to be a bit of an 'easy-mode', so I don't think thats outside the bounds of reason. Closing the issue.
