### ISSUE TITLE
Unlocalized trigger for disabled caravanserai building

### ISSUE THREAD

**Issue by ryyde** [MattTheLegoman/RealmsInExile#665]
After the King died and my heir inherited, the caravansevai building got disabled.

NOT_HAS_CULTURAL_PILLAR_THIRD is unlocalized

I reactivated the third cultural pillar and waited many years but the building stayed disabled.

![4](https://user-images.githubusercontent.com/124939126/218179022-e927b876-e5e7-4e3e-ac2c-54cb4ab65273.jpg)

**Comment by JukeJukestar** [comment]
Related to #582

**Comment by jj248** [comment]
Added localisation to this trigger.  Closing.
![image](https://user-images.githubusercontent.com/26043074/219653794-12fc2597-228c-40d4-a4d6-4ffe234c58e7.png)
