### ISSUE TITLE
Raiding is broken

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#666]
![image](https://user-images.githubusercontent.com/76008882/218217809-55f9a1b8-2772-4ab2-857f-a81b871cb8d4.png)

Raiding now lasts negative two million days, likely an overflow error.

**Comment by jj248** [comment]
Can you tell me how I can replicate this @JukeJukestar ?  All my raid times seem fine when I try.

**Comment by Remerod** [comment]
Juke you are forgetting to put issues in projects to much

**Comment by Remerod** [comment]
> Raiding now lasts negative two million days, likely an overflow error.

also you should add more information how you discover bugs and how to recreate them

**Comment by jj248** [comment]
Closing as cannot replicate.  Can reopen if it's spotted again.  May have just been a freak overflow!
