### ISSUE TITLE
"nine fingered peasants" as Elves

### ISSUE THREAD

**Issue by ryyde** [MattTheLegoman/RealmsInExile#668]
![8](https://user-images.githubusercontent.com/124939126/218321002-c86064e2-4c43-4f1e-9e5d-852780e4240f.jpg)

I think thats a (nordic or generally and evil men) men or dwarven thing. **Not elvish.**
Maybe all the countries south of mordor too.

**Comment by BriceLeduc** [comment]
Problem is we have 0 custom court events. If we start disabling court events for them they won't be left with many

**Comment by ryyde** [comment]
was it a elven thing cut of saints fingers? but fingers of workers too?

**Comment by BriceLeduc** [comment]
No it's a vanilla event. We haven't made any Realms court events. Everything court event you'll see is from vanilla
