### ISSUE TITLE
Forces of Evil Activity

### ISSUE THREAD

**Issue by MattTheLegoman** [MattTheLegoman/RealmsInExile#67]
* Decision: start activity to do "evil stuff", an alternative to feasts and hunts. It opens their characters to various modifiers and outlets for wealth.
* Available to Sauron and the Nazgûl.

### Sorcery Activity
Available to all Forces of Evil characters.
Starting the activity would begin a starting ritual/meditation at a chosen location, selected from a list of available terrains or home. The second event offers three or less random choices from the below plus a choice to cancel the activity. Each summon/calling/spell gives a random event with a modifier.

**Call the Horde: Uruks**
* Invigorate the local warlords.
* Disrupt the local warlords.
* Outfit a rising warlord as a banner orc.
* Call in the legions of Morgul.
* Forge sorcerous steel.
* Mark Uruks with the Red Eye.
* Mark Uruks with the White Hand.

**Call the Horde: Haradrim**
* Call in Haradrim Raiders.

**Call the Horde: Wildmen**
* Call in a wildmen horde.

**Call the Horde: Black Númenóreans**
* Call in a (small) army of Black Númenórean Vanguards.

**Summoning Ritual: Wraiths**
* Unseen Terror
* Wood-wights
* Marsh Spectres
* Oathbreakers
* Watchers of Mordor

**Summoning Ritual: Evil Gathering**
* random assortment of available armies

**Cast Spell: The Second Darkness**
* Darkness covers the realm.
* The land festers.
* Salt the earth, burn the woods.
* Shadow of Fear

**Cast Spell: Conflagration**
* You summon the Cracks of Doom.
* You summon the molten rock and fires of Orodruin.
* You summon the infernal flames of Udûn.

**Cast Spell: Houses of Lamentation**
* This is my Hour!
* You will suffer the chill of Angmar.
* Die now, the Morgul Blade drives through your heart.
* Pursue them relentlessly.
* Do not come between a Nazgûl and its prey.

**Cast Spell: Of Piercing, Opening and of Treachery**
* Hatred of the Free Peoples
* Ambassador of Darkness
* Endurance of Death
* Live Deliciously
* Hunter's Smell

### Notes
**Callings** are for non-magic characters. They are tied to the realm's available regions. It summons armies, characters or modifiers.

**Summoning Rituals** are for magic characters. It summons armies, characters or modifiers based on available regions. Summoning and Calling have crossover.

**Cast Spell: The Second Darkness**
A negative county modifier targeted at a county with non-Forces of Evil population, in exchange for a positive modifier.

**Cast Spell: Conflagration**
A negative realm modifier in exchange for a positive army modifier.

**Cast Spell: Houses of Lamentation**
Nazgûl focused events with modifiers.

**Cast Spell: Of Piercing, Opening and of Treachery**
Available to allow the player a unique playstyle. Each of these random events gives a choice to accept or refuse, the AI always refuses.
_Hatred of the Free Peoples_ - negative opinion for Free Peoples.
_Ambassador of Darkness_ - positive opinion for Free Peoples.
_Endurance of Death_ - removes undesirable traits for wraiths. Allows the player to cleanup their wraith.
_Live Deliciously_ - unlocks the base game Feast Activity for your character.
_Hunter's Smell_ - unlocks the base game Hunt Activity for your character.

**Comment by jj248** [comment]
Large number of errors coming through in log from incorrectly formatted code that should be reviewed pre-release.

**Comment by Gseg** [comment]
No more errors left. Closing!
