### ISSUE TITLE
Upper Khand Pilgrimage Background picture

### ISSUE THREAD

**Issue by ryyde** [MattTheLegoman/RealmsInExile#670]
![11](https://user-images.githubusercontent.com/124939126/218330035-539a300c-802f-41ec-9c86-d26e0713b6ad.jpg)

Only Khand´s start of pilgrimage background didnt match the countries terrain

**Comment by jj248** [comment]
One for you @BriceLeduc ?

**Comment by BriceLeduc** [comment]
The thing is I checked the pilgrimage code, and it hasn't been changed from vanilla

**Comment by BriceLeduc** [comment]
Not a bug, this is how the background is defined
