### ISSUE TITLE
All Rasayni rulers convert to Kirab-Sarada

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#677]
A few months after game start, all Rasayni rulers convert to Kirab-Sarada. This happens alsmost every game. It appears to be a random heresy since they start with relatively low fervor at game start.

**Comment by jj248** [comment]
Gave them a bunch of fervour at game start.  Pinging back to testing to see if that fixes.

**Comment by Remerod** [comment]
I've tested this now 4 times for 10 years and it seems to be working now fine now so i'm closing it off :)
