### ISSUE TITLE
Assault on East Gondor Bug

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#678]
![image](https://user-images.githubusercontent.com/76008882/219178444-8e4a9bd1-0cf9-4ac8-b36e-dfa091764f0a.png)

Sauron has a new fourth option during the "Assault on East Gondor" event - this one is the same as the fourth one exept it doesnt cost 1000 prestige and isnt localized.

**Comment by jj248** [comment]
Nice and simple.  Was just some misplaced tooltip localisation.  Closing.

![image](https://user-images.githubusercontent.com/26043074/219645448-ff4278f3-723a-4026-969d-23a6bfa5935e.png)
