### ISSUE TITLE
Gondor Civil War event

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#68]
Full branching event chain following the decision of the ruling Steward to *not* permit the Return of the King.

**Comment by jj248** [comment]
Initial draft committed.  Need to work on AI weights, localisation review, fix Dol Amroth marriage and dynasty creation and generally test.

**Comment by jj248** [comment]
AI weights and last fixes done - just needs testing feedback now.

**Comment by RedArkady** [comment]
This option plays really well, though players *should* expect Mordor to take advantage!

Future consideration might be given to adding White Peace resulting in division of Gondor?

Recommend close.

**Comment by jj248** [comment]
Will consider white peace for later extension.  Bug is noted.  Thanks - closing.
