### ISSUE TITLE
Andrast Rebalance

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#686]
The newly created corsair on the tip of Andrast is OP, he always ends up gobbling his neighbours.

That would be ok for a major character but this is not the case. He also makes playing as anyone else there even more difficult than it was previously.

Proposed solution : giving him mediocre stats

**Comment by JukeJukestar** [comment]
Do you have any data on how strong he usually gets? How many test games did you run?

![image](https://user-images.githubusercontent.com/76008882/219959720-86e826aa-c3db-450b-99e3-9ad24025d3f2.png)

His stats are already pretty mediocre, the reason hes stronger than the surrounding counts is that Úlond is just a really strong county with a lvl 3 fortress - combined with his conquest CBs which can be used a bit earlier than the previous Gondorian ruler's holy wars.

I think hes in a decent spot, in my test games he usually forms a duchy and conquers a few counties, before being killed and either conquered by gondorians or inherited by his relatives in Umbar. Havent seen him form the kingdom so far.

**Comment by BriceLeduc** [comment]
A solution could be to move him to a different county

**Comment by JukeJukestar** [comment]
Hes kind of supposed to be at the tip there because its a gondorian county with no lore beforehand, also so umbar (if they get his stuff) start harassing gondor from there. I tihnk the borders wouldnt look very good if they get one of the tribal counties upnorth instead

**Comment by jj248** [comment]
> Hes kind of supposed to be at the tip there because its a gondorian county with no lore beforehand, also so umbar (if they get his stuff) start harassing gondor from there. I tihnk the borders wouldnt look very good if they get one of the tribal counties upnorth instead. Do you have any data on how strong he gets? I havent seen him do much more than conquer 2 duchies

On the contrary actually.  That's Bar Morthil.  See lore we've gone with for the region [here](https://notionclubarchives.fandom.com/wiki/Bar_Morthil).  It may even have a special building no?

**Comment by RedArkady** [comment]
It does! Maybe move him up to Nannthorod if we're keeping him?

**Comment by BriceLeduc** [comment]
That's right. This is pretty much the only county that has any lore. We even have a sailing event taking place there

**Comment by JukeJukestar** [comment]
Ran some test games myself, here are the results

**Test 1**
Raided a bit, conquered nothing, died 3005

**Test 2**
Raided a bit, conquered nothing, died 3010.
Succeeded by his only daughter, who also raided Andrast, she also conquered nothing.
His daughter patrilinearly married a Gondorian man, their child is Erulaitale-Gondorian.

**Test 3**
Raided a bit, conquered 1 county, died in 3008
Succeeded by Umbarean branch

**Test 4**
Raided a bit, conquered 1 county, formed the duchy, defeated by Tharagrondost Gondorians (who use the money to refound their duchy),  died in 3035.
Succeeded by only son.
**Test 5**

**Comment by JukeJukestar** [comment]
> > Hes kind of supposed to be at the tip there because its a gondorian county with no lore beforehand, also so umbar (if they get his stuff) start harassing gondor from there. I tihnk the borders wouldnt look very good if they get one of the tribal counties upnorth instead. Do you have any data on how strong he gets? I havent seen him do much more than conquer 2 duchies
> 
> On the contrary actually. That's Bar Morthil. See lore we've gone with for the region [here](https://notionclubarchives.fandom.com/wiki/Bar_Morthil). It may even have a special building no?

I didnt mean that the area has no lore, its the former vacation spot for the gondorian kings - in that regard its got more lore than the entire rest of andrast! What I meant is that we have 0 lore on who else would be ruling the area, giving it to the gondorian governors in the area would make them too strong I am afraid.

I really like him having Ulond, but I have to admit I'm a bit biased here. I havent seen him do anything beyond raiding the other rulers in Andrast and conquering a few counties at most, so I dont think he has to be nerfed. It may be one of those cases where the AI pulls off something crazy every ten games, like that one time a leofring count conquered all of the Mudlands.

I also think the lore implication of using the former vacation castle of Gondor as a potential Umbar landing point (as it used to be back in 2.0) is quite good.

**Comment by JukeJukestar** [comment]
> That's right. This is pretty much the only county that has any lore in Andrast. We even have a sailing event taking place there. With a Gondorian caretaker

That should be relocalized to account for the local ruler either way, its very strange to specifically mention a gondorian caretaker when it can be conquered by any faction during the course of the game

**Comment by BriceLeduc** [comment]
It isn't. Only Gondorians would take care of a Gondorian landmark. Relocalising with Umbarean would make no sense

**Comment by BriceLeduc** [comment]
My opinion is it would be better to move him higher up the coast and place a gondorian in charge

**Comment by JukeJukestar** [comment]
I would tend to disagree,I think the balance of local andrastim tribes, Gondorian governors and Umbarean corsairs is pretty solid right now. If we put a Gondorian count in Úlond there is a pretty high chance he would be replaced by a corsair within 30 years of game start anyways due to wildmen adventures (as is the case with most other andrast rulers)

I dont quite understand why you want to nerf him/ replace him, do you still think hes too strong? Or is it lore reasons. Could you specify?

Maybe it would be a good idea to turn this into a #suggestions discussion next time, geez this is gettin long.

**Comment by JukeJukestar** [comment]
> It isn't. Only Gondorians would take care of a Gondorian landmark. Relocalising with Umbarean would make no sense

I think the sailing event could be its own issue if you want to make one. You misunderstood, I dont want to relocalize it with Umbarean, I am saying it should check the holder's culture. It doesnt make sense to have a Gondorian Governor after Mordor has been holding it for the past 100 years

**Comment by BriceLeduc** [comment]
Umbarean was an example, any non-Dunedain culture maintaining it makes 0 sense

**Comment by RedArkady** [comment]
As things are either he or Umbarean successors get too strong too often. I preferred it when the area was independent Gondorian - I don't think Gondor would tolerate Umbareans in Bar Morthil for any length of time. If we're gong to keep an Umbarean in the area I think we should move them up the coast and make sure they have heirs so it isn't inherited by Umbar proper.

**Comment by JukeJukestar** [comment]
I didnt realize you viewed Umbar conquering Andrast as an issue - thats specifically why I put him there! Back in 2.0, Úlond was Umbars go-to pirate outpost to harass Gondor with. They stopped doing it in 2.3 and because me and several other players liked Umbar-Andrast, I wanted to give them a chance at getting it back as the AI. I can easily remove his ties to his relatives so Umbar doesnt inherit if you dont like this behavior.

Do you have any examples of him and his successors getting too strong? during my test games they didnt really accomplish much until umbar inherits, which is when they usually conquer a few more counties.

I do very much think Gondor would tolerate Umbareans in bar Morthil, they literally do it in every single game - before I put the corsair there wildmen would usually conquer the county until Gondor gets strong enough to take andrast back properly.

Im a bit afraid of moving him north because it would completely change the balance in the region - He's there to be a nuisance to the gondorian governors in Tharagrondost. We would have to feudalize the Andrastim tribes upnorth or have him as a tribal umbarean (which feels weird), he would also no longer have any interaction with gondorian subjects (See test 2, i really liked that outcome and he marries gondorians a lot rn)

Feel free to join vc so we can discuss this a bit better, its hard to explain stuff in these git comments

**Comment by JukeJukestar** [comment]
> Umbarean was an example, any non-Dunedain culture maintaining it makes 0 sense

I disagree. The way we have it set up, its almost never held by Dunedain until Aragorn arrives and beats Sauron. If you give it to a gondorian count it will likely be conquered by a wildmen adventurer in most games. In ck3, anyone can conquer anything, so I dont see why its integral for the event to specify a Gondorian Governor

**Comment by BriceLeduc** [comment]
I've created a suggestion thread as you proposed, let's move the discussion there

**Comment by JukeJukestar** [comment]
For anyone readin, heres a list of our current changes we want to make:
Lorewise its mostly the same, the corsairs moved into Úlond 3 years before game start and overpowered the small gondorian garrison remaining there. now the Governors in Tharagrondost want to reclaim it!

- [ ] Nerf Úlond to a level 2 castle
- [ ] Change dynasty history a bit
- [ ] Give Tharagrondost lords a pressed claim on Úlond and a starting event detailing their fall from grace
- [ ] Give him a Gondorian wife and at least one son to inherit the title
- [ ] Possibly disinherit Umbar relatives to avoid inheritance

**Comment by JukeJukestar** [comment]
yep there we go. Close this in like a week if we dont encounter anythin broken.
investigate if umbar still inherits the county in more than like 10% of games, if they do we have to do something about that!

**Comment by savagesach** [comment]
I've done several test games, pretty much every time andrake loses ulond to atanalcar, though he does often live on in rafinfalas. Also I've never once seen umbar inherit the title.

**Comment by savagesach** [comment]
honestly in my view, andrake really doesn't need a nerf, the ai is already stupid enough that he keeps getting his army stackwiped in failed raiding ventures

**Comment by jj248** [comment]
I'll let @JukeJukestar make the call on closing this one.  Sounds like it's in a fine place now?
