### ISSUE TITLE
Khamul will join Thranduils court

### ISSUE THREAD

**Issue by blackbird5598** [MattTheLegoman/RealmsInExile#687]
### The problem

Khamul gladly joins Thranduils court & even convert religions if asked after being conquested.

### Release version

Not latest as of 2/18/2023 but the version just prior to.

### Operating system

Windows 11

### Steps to reproduce the behavior

Annex Dol Guldur & select Khamul, you will have the opportunity to invite Khamul to your court as Thranduil. Perhaps have it so that Khamul immediately goes to Barad dur after being conquested.

### Screenshots

![image](https://user-images.githubusercontent.com/125709421/219900036-50e2e101-3ad2-4cf2-8aa6-c154bc152b59.png)

**Comment by jj248** [comment]
I've put a blocker on the invite to court interactions so that only Sauron can invite Nazgul to courts.  Ready to test.

**Comment by Jauffr** [comment]
The blocker does not seem to be functioning

![Screenshot 2023-02-21 042841](https://user-images.githubusercontent.com/108106660/220334014-1128448c-8713-4106-98ef-12c656b5893d.png)
![Screenshot 2023-02-21 042901](https://user-images.githubusercontent.com/108106660/220334025-edd2999d-7826-4254-b366-0ba1c491e6a8.png)
![Screenshot 2023-02-21 043022](https://user-images.githubusercontent.com/108106660/220334032-84390ceb-8368-4ff0-8abc-3951577bdcb7.png)

**Comment by jj248** [comment]
Missed something obvious.  I was a dumdum.  Should be working now!

**Comment by Remerod** [comment]
should nazguls be able to invite other nazgouls courts? otherwise this seems to be working fine now then?

**Comment by Jauffr** [comment]
I can not invite Khamul to my court as the Witch King. I think that if a Nazgul is willing to join another Nazgul's court they should be able to be invited. Sauron can always use his strong hooks to take them back when he wants them 
![Screenshot 2023-02-23 175043](https://user-images.githubusercontent.com/108106660/221065135-577f67ca-d8d4-4b92-a4b9-2fa6a3f485c3.png)

**Comment by jj248** [comment]
Sounds reasonable.  I can add other Nazgul as valid invitees.

**Comment by jj248** [comment]
Fixed this so that Nazgul can join Nazgul courts too.  Should be ready to test.

**Comment by Jauffr** [comment]
Issue can be closed. Working as intended 
![Screenshot 2023-02-27 173417](https://user-images.githubusercontent.com/108106660/221721476-1c4d9e75-2a1a-42de-9691-cbadbd89300d.png)
