### ISSUE TITLE
Galadriels MAA are missing flavor texts

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#692]
![image](https://user-images.githubusercontent.com/76008882/219977841-59493489-cbee-4974-89e4-2699751f5108.png)

several of them are missing flavor texts. worth checking others as well.

**Comment by jj248** [comment]
I beleive almost all elven MaA are missing loc descs.  One for @VectorMaximus <3

**Comment by jj248** [comment]
Done.  Closing.
