### ISSUE TITLE
Golden Realm rulers dont inherit Tributary Status properly

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#693]
It appears that the tributary relationship is lost upon succession in the Golden Realm. This means sauron will invade them sometimes

**Comment by jj248** [comment]
I can't replicate this - going to need more details I'm afraid!

**Comment by jj248** [comment]
Closing as linked to #709

**Comment by JukeJukestar** [comment]
We noticed this during the MP, sauron attacked the second ruler of the golden realm. it may have been because they were installed by a faction? Reopen if it happens again
