### ISSUE TITLE
Elves cannot faith-convert counties

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#696]
I realize it was probably disabled so they dont convert humans, but they also cant convert elves.
This leads to situations where I cant faith convert any of my own counties to my newly created faith

![image](https://user-images.githubusercontent.com/76008882/219980360-63cce35d-6133-47ab-a21f-bf409a1bbf40.png)

Demanding conversion is also impossible, which means that due to bound by faith none of my relatives can inherit.

**Comment by jj248** [comment]
I've re-enabled this for elves and made it valid for them to only target elven culture counties.  Ready to test.

**Comment by JukeJukestar** [comment]
Did you also reenable demanding it from elven courtiers?

**Comment by jj248** [comment]
As in, through the character interaction 'Demand Conversion'?

**Comment by jj248** [comment]
Made it so that non elves cannot demand conversion of elves and elves cannot demand conversion of non-elves.

**Comment by savagesach** [comment]
I can confirm this works as intended, I'd say this issue can be closed
![image](https://user-images.githubusercontent.com/86676697/221316478-a03039ea-51f3-4105-b38e-fe63a6193c6a.png)
![image](https://user-images.githubusercontent.com/86676697/221316745-beacd57a-842e-4d83-8a67-b2455f5d2cbc.png)
![image](https://user-images.githubusercontent.com/86676697/221316970-a70861ec-f34c-44e0-9485-38ac9b4147ee.png)
![image](https://user-images.githubusercontent.com/86676697/221317246-9bd9944e-3f7c-4355-8a5b-19280669149a.png)
![image](https://user-images.githubusercontent.com/86676697/221317289-cced1345-8dd2-47b9-ae1d-80db57ace8e7.png)

**Comment by JukeJukestar** [comment]
sick, closing now
