### ISSUE TITLE
Nazgul generate Numenorean characters

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#70]
Spotted in an AI testing run.  Witch King pushed west and started giving titles to fellow Numenoreans - he also has Numenoreans in his court.

![image](https://user-images.githubusercontent.com/26043074/117628324-eb799780-b170-11eb-9922-447e66d959bd.png)

**Comment by VectorMaximus** [comment]
Nazgul are no longer Numenorean culture, so will close for now - if the bug resurfaces, we can open this.
