### ISSUE TITLE
Succession Law change for Lasgalen upon Settling

### ISSUE THREAD

**Issue by savagesach** [MattTheLegoman/RealmsInExile#701]
I was testing colonization and I noticed whenever I colonized a province as lasgalen, my succession law changed to confederate partition.
![image](https://user-images.githubusercontent.com/86676697/220042899-a19b22cb-677c-4932-adcd-98a59f9e4d98.png)
for some reason though, this effect did not happen with dorwinion or sauron 
![image](https://user-images.githubusercontent.com/86676697/220043053-6bb80770-5c7c-466a-97fb-27c0186900df.png)
![image](https://user-images.githubusercontent.com/86676697/220043228-7d611c56-ca45-411d-90ee-3ebcd086b8f2.png)

**Comment by Remerod** [comment]
Juke please assagin the project to! ;)

**savagesack** what's your discord username?

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/220246766-cf004a2c-4396-4445-874d-33ff78f161a0.png)
I tested further and it turns out that lasgalen's succession automatically changes to confederate partition in a few weeks anyway, even without settling

**Comment by jj248** [comment]
@VectorMaximus - didn't we have an issue with the AI wanting to change succession types all the time in v2.2?

**Comment by VectorMaximus** [comment]
We did, because some AI vanilla weights were favoring that succession type.

**Comment by jj248** [comment]
Looks like Elven government was missing in the eligible types for High Partition.  Pushing a fix.
