### ISSUE TITLE
Numenorean blood upgrade deception

### ISSUE THREAD

**Issue by savagesach** [MattTheLegoman/RealmsInExile#706]
![image](https://user-images.githubusercontent.com/86676697/220213467-01559a93-9762-40a3-98f3-755060f04219.png)
![image](https://user-images.githubusercontent.com/86676697/220213576-a00a4f0c-c9d4-42b4-be90-116297a4ef32.png)
I have noticed that if you marry someone with numenorean blood to someone with the same tier of blood, the game gives the impression that the blood can actually upgrade from for example remnant to strong. I am not sure how this can be rectified, but it definitely should be.

**Comment by jj248** [comment]
Tweaked so wording above shouldn't show.  Will not show for vanilla congenital traits either sadly, but I think most people know how that works and there's game concepts where it's unclear to get more info.  Ready to test.

**Comment by Jauffr** [comment]
Tweak did not fix the issue. Game still be lyin' about the blood. No matter how tender, how exquisite... A lie will remain a lie
![Screenshot 2023-02-23 182457](https://user-images.githubusercontent.com/108106660/221069367-64a30acb-8e0e-4947-82f2-36349a05a135.png)

**Comment by jj248** [comment]
I'm not sure where it still says thi... oh... the arrow... feck.

**Comment by jj248** [comment]
I've now removed these pesky upgrade arrows across the board.  Closing.
