### ISSUE TITLE
Vassalizing different religions is too easy

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#707]
Every game we see Dorwinion vassalize the logath.

I think it should be harder to vassalize different religions (not faiths nessecarily!). The wystem already accpunts for alignment, but its too easy for same alignment rulers to vassalize eachother if they have a different religion.

**Comment by jj248** [comment]
Gimme an idea of the level of negative modifier you think would help resolve and I'll implement @JukeJukestar

**Comment by Jauffr** [comment]
I am ok with where it is at right now. I would drop it by 10 though. As things are, Diplo focused character are capable of diplo vassalizing people of different religious families only if the character is at 100 opinion, friends with them, and be given religious protection (Tribal is impossible now for any non religious family partners, so the Logath are safe now) and the character to be vassalized can not have any more than a single trait that makes them less likely to accept vassalization. I would recomend dropping it to -20 to allow it to be a little more feasable to diplo vassalize non religious family members without having to min max absolutely everything even for people who have every reason to accept. Any more than that though and you run the risk of the Logath being vassalized again. -20 would still prevent the problems we see happening with the AI, while not completely spoiling the opertunities of Players deterimed to make use of the mechanic. Myself being one of them as a diplo and intrigue focused player

**Comment by jj248** [comment]
OK - tweaked down to -20.

**Comment by JukeJukestar** [comment]
Seems to be working, though I disagree with jauffre - even a god tier diplomat who is friends with the other person shouldnt be able to vassalize someone of a different religious family!? Different religion I could rarely see, but it also shouldnt happen. Different faith is fine though. 100 opinion can be gained very easily and the diplomatic court grandeur can give up to ~+30 I believe as well? Hard to say without deep testing.
Overall unlike ck2 there are so many factors that can influence it that you cant clearly say who can and cant be vassalized.

**Comment by JukeJukestar** [comment]
Reopening because its still far too easy. Just push it to -50, we dont want many situations where rulers vassalize ones with a different RELIGION (not faith)

**Comment by Jauffr** [comment]
I did not say it was far too easy. It is just barely possible with all the buffs Hawin can use to make it happen. Minus 35 at the most. 30 was just fine. Any more than that and it simply won't be possible aside from players focusing completely on that goal. 35 is already enough where Hawin can't even do it unless he just barely manages to seduce them and bump up his army size and not anger his vassals and keep his court excellent. Just don't make it impossible for players and the occasional surprise from legends like Hawin and Kathuphazgan by going too high

**Comment by jj248** [comment]
Up to -35 now.
