### ISSUE TITLE
Suggestion:   Trade Route 

### ISSUE THREAD

**Issue by ryyde** [MattTheLegoman/RealmsInExile#710]
"old" Trade Route from Moria to (south of) Erebor

I saw that many LotR maps have that road through Greenwood Forest. 
On that maps the road is called " Old Forest Road "
Maybe the trade route in another color then the one from gondor to east. Because the one i talk about maybe is not used anymore?

**Comment by JukeJukestar** [comment]
Nobody has been trading on it for the past few thousand years (Moria has fallen!). The old forest road is in game as a wasteland province woodmen can resettle.
Eventually a dynamic system where old trade routes can reappear would be dope but right now I dont think this is a good idea, suggest closing.
Maybe we can talk about more trade routes in a suggestions forum thread tho, I think having more might be interesting

**Comment by JukeJukestar** [comment]
Potentially we could have a future trade system where if moria is resettled by dwarves and the old forest road is recolonized they can slowly restore the trade route, but right now i tihnk we should close this

**Comment by ryyde** [comment]
yes alright, it was more like having that forst road as a potential trading route,  thats the only piece of land elves would allow anyone in past but also future to pass their forest...

**Comment by jj248** [comment]
Agree - nothing for v3.  Might be something to consider in v4.
