### ISSUE TITLE
Conspirator cloak asset is broken

### ISSUE THREAD

**Issue by BriceLeduc** [MattTheLegoman/RealmsInExile#711]
The conspirator's cloak does not show up in-game.
This results in situations where the conspirator is naked, and extremely skinny

**Comment by jj248** [comment]
Looks like I failed to catch a rename of the asset in a compatch.  Should be fixed now... 
![image](https://user-images.githubusercontent.com/26043074/220857684-ce91b3da-e6e6-4923-abef-aef49977b2b1.png)
