### ISSUE TITLE
Lanthir cheating on wife

### ISSUE THREAD

**Issue by savagesach** [MattTheLegoman/RealmsInExile#713]
![image](https://user-images.githubusercontent.com/86676697/220449942-df7f116c-43bc-4423-97d5-6d6c7106f54a.png)
Can we please change the situation at game start so that lanthir doesn't have a soulmate relationship with an elf that's not his wife. I don't think elves cheating on their spouses is very lore accurate, nor does it make sense gameplay wise when the avari can't even reach lasgalen because of lack of diplimatic range.

**Comment by jj248** [comment]
I'm hoping that's just an error in the history file.  Will correct if nobody beats me to it.

**Comment by jj248** [comment]
Fixed.
