### ISSUE TITLE
Hunchback DNA

### ISSUE THREAD

**Issue by Jauffr** [MattTheLegoman/RealmsInExile#715]
The wife of King Bain of Dale, has hunchback DNA that causes her descendants to sometimes look like this
![Screenshot 2023-02-22 005642](https://user-images.githubusercontent.com/108106660/220557835-5d4e780a-f85c-4484-860a-353945de4d16.png)
![Screenshot 2023-02-22 005704](https://user-images.githubusercontent.com/108106660/220557841-b7dfc7f2-2852-489c-9be9-f3c8efbba704.png)

**Comment by Jauffr** [comment]
Queen Astrid Historical ID: bainwife

**Comment by JukeJukestar** [comment]
Good you spotted this!

**Comment by jj248** [comment]
This should now be fixed.

**Comment by Jauffr** [comment]
This can be closed. As of now all characters that had a chance of passing on a recessive hunchback gene appear to be resolved
