### ISSUE TITLE
Nobody can use claim CB

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#722]
Claim CB are unavaiable for most (if not all) characters

**Comment by jj248** [comment]
Any additional info?

**Comment by Jauffr** [comment]
Only independent characters are capable of using claims for war declaration. All other CB are functioning correctly for vassals. De Jure wars function for example.
![Screenshot 2023-02-22 225959](https://user-images.githubusercontent.com/108106660/220831292-695d3211-7be6-4491-9643-ee2b982b12a9.png)
![Screenshot 2023-02-22 225920](https://user-images.githubusercontent.com/108106660/220831299-efca24da-b8e4-4ca5-9688-349d61e412aa.png)

**Comment by jj248** [comment]
Hopefully this has now been fixed.  Please test. <3

**Comment by Jauffr** [comment]
This can be closed. All subjects can now use claim CBs

**Comment by VectorMaximus** [comment]
Excellent to hear, closing.
