### ISSUE TITLE
Custom calendar localisation not functioning properly in battle or construction screens

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#73]
It seems to be an issue around calling "GUITrackItem.GetConstructTimeLeft" and "BattleSummaryWindow.GetEndDate" in the GUI.  Looking at data_types.log, their data type is CString rather than Date which *may* be part of the issue.

**Comment by jj248** [comment]
After some investigation, it doesn't look like we have the tools to easily fix this.  So thinking about it pragmatically, time left in construction is shown in the bar below so there's no real value in seeing the exact date.  Also for battles, the main info that's valuable is the battle results, not what exact date it happened.

With this in mind, I've just removed the dates in both these areas until paradox make these two functions work how we need them to.

**Comment by RedArkady** [comment]
This seems to be working fine now.

**Comment by jj248** [comment]
Great - thanks.  Closing.
