### ISSUE TITLE
Lanthir's son will not marry anyone

### ISSUE THREAD

**Issue by savagesach** [MattTheLegoman/RealmsInExile#737]
I was playing nelornieth and I noticed I cannot get Lanthir's son to marry anyone. This is because unlike human marriages, elven marriages are soley dependent on attraction. The result is that some elves cannot marry anyone at all, which is really annoying.
![image](https://user-images.githubusercontent.com/86676697/221340489-3de42b2a-2593-444f-bafe-64668f156905.png)

**Comment by jj248** [comment]
I've tweaked him to hardcode his sexuality.  Closing.
