### ISSUE TITLE
Honnin Megaliths

### ISSUE THREAD

**Issue by savagesach** [MattTheLegoman/RealmsInExile#739]
The Honnin faith (Onu) should have the megalithic construction tenet instead of monasticism, it makes sense both lore wise and gameplay wise as the Honnin were the first to build stone structures, then lost the art as they became tribal. This is represented by the fact that great megaliths can only be built upon becoming feudal.

**Comment by savagesach** [comment]
okay small change, after doing some testing, I think megalithic construction should replace pastoral isolation, not monasticism. This is because it is not possible to create a religion with both pastoral isolation and megalithic construction.
![image](https://user-images.githubusercontent.com/86676697/221351235-c7239499-4891-480f-b3ad-af1498ee3876.png)

**Comment by JukeJukestar** [comment]
I'll do this

**Comment by JukeJukestar** [comment]
Added.
Please test if it works correctly, then we can close.

**Comment by JukeJukestar** [comment]
How are megaliths represented in game, are they special buildings at holy sites? We could add one in the Rây region somewhere, which the locals wont be able to use but stands as a reminder of the Honnin

**Comment by Jauffr** [comment]
They are a duchy building

**Comment by JukeJukestar** [comment]
I see, doesnt fit too well then. lets not have any at game start

**Comment by Jauffr** [comment]
You can always replace a building yah know. More importantly, there is no reason one couldn't be built in the Honin's forest on game start I think

**Comment by savagesach** [comment]
the way megaliths work is that there are two types, megaliths and great megaliths. megaliths can be built in any temple holding, while great megaliths are duchy buildings.

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/221618398-7d33ee1c-742e-46da-9d10-1f0f5801a33a.png)

Gave them the duchy building!
If its too strong as a buff, let me know. otherwise we can close

**Comment by jj248** [comment]
Happy with this.  Closing.
