### ISSUE TITLE
Add more variations to the Shattered Earth game option.

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#76]
Currently only able to break down to independent counties.  There should also be the option to break to other title tier levels.

**Comment by jj248** [comment]
Have implemented these new options - ready to test to ensure they're functional.  They break the title structure down within the first few days of the game.

**Comment by RedArkady** [comment]
Works well, adding a lot of dynamism to the game. The 'Return of the King' even does not trigger, but I think the consensus is that this is fine. County/duchy shatter plays out quite differently. 

Recommend close - however note this bug: https://github.com/MattTheLegoman/RealmsInExile/projects/2#card-61281242

**Comment by jj248** [comment]
Great - closing. :)
