### ISSUE TITLE
Rohan can invoke the Oath of Cirion when at war with Gondor

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#77]
Decision needs a check to disable it if one party is at war with the other in any way.

**Comment by jj248** [comment]
Added an extra requirement for Gondor / Rohan to be at peace with one another to invoke the Oath.

**Comment by RedArkady** [comment]
It looks like this is fixed, but it's not reading properly on the decision screen.

![Crusader Kings III Screenshot 2021 05 19 - 17 23 55 36](https://user-images.githubusercontent.com/20355423/118848934-22655100-b8c7-11eb-992c-04ad3b263268.png)

**Comment by jj248** [comment]
I hadn't added trigger localisations for the not at war with Gondor / Rohan triggers.  Updated now.

**Comment by RedArkady** [comment]
This is displaying properly now. Recommend close.

**Comment by jj248** [comment]
Excellent - thanks.  Closing.
