### ISSUE TITLE
Faramir does not marry if the Stewards win the 'King Slaying' civil war

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#79]

**Comment by jj248** [comment]
I have added the marriage events for Faramir and Eomer at the end of all event pathways so they don't get stuck being unmarried if Aragorn doesn't end up on the throne.

**Comment by RedArkady** [comment]
Faramir now marries. Recommend close.

**Comment by jj248** [comment]
Excellent - thank you.  Closing.
