### ISSUE TITLE
Desert Agriculture upgrade - disallowed but reason not stated

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#83]
![Crusader Kings III Screenshot 2021 05 16 - 18 57 38 45](https://user-images.githubusercontent.com/20355423/118407588-54817380-b679-11eb-91ba-15e42d4fb59d.png)

**Comment by jj248** [comment]
I think is just that the province has been given a building which requires desert terrain in the history file in a province which is not a desert, thus blocking the upgrade.  Will look at fixing.

**Comment by jj248** [comment]
Have gone through the history files and picked up (hopefully) all the incorrectly picked buildings.

**Comment by RedArkady** [comment]
This still seems to be an issue:

![Crusader Kings III Screenshot 2021 06 01 - 17 17 23 88](https://user-images.githubusercontent.com/20355423/120357409-52681780-c2fd-11eb-8aa9-52394ab773f7.png)

**Comment by RedArkady** [comment]
Fixed! Recommend close.

**Comment by jj248** [comment]
Great - thanks.  Closing.
