### ISSUE TITLE
'title lost (to you)' message stuck on screen, requiring exit to main menu

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#87]
![Crusader Kings III Screenshot 2021 05 17 - 18 29 33 72](https://user-images.githubusercontent.com/20355423/118541648-da6cef80-b749-11eb-9358-b5d487456d93.png)

**Comment by RedArkady** [comment]
FYI this was on a shattered run, on succession, and it's only happened to me once. Feel free to ignore/close it for the time being, I'll see if I can replicate it on another run at some point.

**Comment by jj248** [comment]
Not important enough to be fixed ahead of v2.1 release.  Moving to backlog for v2.2.

**Comment by jj248** [comment]
Have investigated - no obvious fix that I can see as I can't see where you can cull the messages.  Only an issue for duchies + and I strongly suspect that people only use it at the county level anyway.  Going to run a community poll to find out.

**Comment by jj248** [comment]
Still early days in the poll, but results seem to suggest what I suspected.  Will disable other options and only reopen if the poll results look to change: 
![image](https://user-images.githubusercontent.com/26043074/150960453-fb53924c-0af0-474f-b117-9426f127352e.png)
