### ISSUE TITLE
Wraith culture group for Nazgûl

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#91]
Add Wraith culture group to contain Nazgul.  Should contain 3 cultures (though the latter two can be disabled for now):

 - Ringwraith: which would be specifically for the Ringwraiths and as such would need a very limited list of names/dynasties - similar to the Maiar
 - Barrow-wight: for those of the Barrow-downs, with dunedain and Breeland names
 - Morgul-wight: which are those of Minas Morgul and Dol Guldur, taking from Gondorian, Rohirrim, etc

Specific things we'll need to consider when adding are:
 - Take measures to stop Ringwraith characters being generated for landed Nazgul.
 - Update innovations to be appropriate.
 - Consider appropriate MaAs

**Comment by jj248** [comment]
Outstanding issue with courtiers spawning as Nazgul - will pick this up and make sure they make Uruks instead.

**Comment by VectorMaximus** [comment]
Innovations have been added, but appropriate MAA and culture spawning Ringwraith courtiers (as previously mentioned by Jamie and Issue #102) remains to be completed

**Comment by jj248** [comment]
Applied fixes as conversion events weren't on regular yearly action so weren't firing. Names were still old Istari names.  Should resolive #102 .

I've also stopped Nazgul from being able to convert to local culture and reduced the rate at which that happens across the board by half.

**Ready to test.**  Be on the lookout for stray Ulairi characters that aren't Nazgul, orcs in Nazgul courts with non-orc names, Nazgul converting cultures away from Ulairi and any weird behaviour of AI regarding culture conversion to local culture.

**Comment by jj248** [comment]
Post v1.4 patch the Nazgul are no longer being assigned their culture correctly and the error log states that they are defined as having no faith, despite this being defined.

**Comment by jj248** [comment]
Fixed - ready to test again.

**Comment by JukeJukestar** [comment]
Currently I havent seen any Nazgul courtiers - they generate ungur-hai I believe. However, this also applies to the golden king in abrakhan.

**Comment by jj248** [comment]
This has been my experience too and I know Juke's played enough to have seen if something were amiss (even did a Golden King run).  So taking this issue as done and closing.  Thanks!
