### ISSUE TITLE
Orc buildings localisation

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#92]
A large number of Orc buildings remain unlocalised.  Given v2.1's focus on Uruks - this should be addressed if possible.

**Comment by MattTheLegoman** [comment]
Not finishing the Orc building descriptions.

**Comment by RedArkady** [comment]
Missing localisation added:
# Raiding Camps
# Siege Works
# Hunting Outposts
# Scouting Posts

**Comment by Remerod** [comment]
checked it when Redarkady updated it, and double checked now, all localization for Raiding Camps, Siege Works, Hunting Outposts & Scouting Posts seems to be in order to me.

**Comment by Remerod** [comment]
I was given permission to close this, so that's what i'll do just that ;)
