### ISSUE TITLE
Some unlocalised items in barbershop and Gondorian crown not present.

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#93]

**Comment by jj248** [comment]
Should now be no missing localisation.  I've also added FP1 assets to the Barber Shop and made sure that Imperial Rohan gets their fancy new crown.

**Comment by JukeJukestar** [comment]
This is still the case as of 9.7.2022 during FoI compatch testing.

Namely Gondorian cloaks are unavailable to all rulers in the barbershop,
Strangely, royal cloaks are only available to king and emperor tier characters and not to counts or dukes as well it seems.

**Comment by BriceLeduc** [comment]
Royal cloaks being only available to Kings and Emperord is not a bug, it's a vanilla setting

**Comment by JukeJukestar** [comment]
In that case change the vanilla setting to allow for counts and dukes to use them cause its stupid if they can use any other king or emperor gear exept the cloaks

**Comment by jj248** [comment]
Closing this and linking to be covered as part of #559
