### ISSUE TITLE
Anti-Sauron uruk cults

### ISSUE THREAD

**Issue by VectorMaximus** [MattTheLegoman/RealmsInExile#94]
Additional flavor and a goal for anti-Sauron orc players to pursue.

**Comment by VectorMaximus** [comment]
New "Pardahûnúk" faith implemented for Orc players who wish to go against Sauron, with an accompanying decision to form an empire-tier Orc Horde if independent and above a certain realm size.

**Comment by RedArkady** [comment]
Works well as far as I can  - I have nothing intelligent to add!

**Comment by jj248** [comment]
Great - closing.
