### ISSUE TITLE
Decisions to form independent anti-Sauron Uruk realm

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#95]
* Decision: Form independent anti-Sauron realm (switch realm's faith to anti-Sauron, Forces of Evil faith)

**Comment by RedArkady** [comment]
Good stuff, adds a fun new dynamic. Could consider giving them access to some of the Uruk MaA from the start.

**Comment by VectorMaximus** [comment]
Finished, closing
