### ISSUE TITLE
Parth Celebrant/Thorlorien borders not following the river

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#98]

**Comment by RedArkady** [comment]
![Crusader_Kings_III_Screenshot_2021 05 30_-_19 35 48 36](https://user-images.githubusercontent.com/20355423/120461330-d23fc180-c391-11eb-8b30-afea284261f8.png)

**Comment by jj248** [comment]
Correction made.  Parth Celebrant has claimed its land South of the river.

**Comment by RedArkady** [comment]
Fixed! Recommend close.

**Comment by jj248** [comment]
Merci beaucoup.  Je le ferme!
